getsentry/symbolicator

Cargo.lock
Cargo.toml
src/actors/objects/http.rs
src/http.rs
src/types.rs

This adds support for providing custom headers when performing a fetch from an HTTP
source for authorization information and it adds support for non absolute redirects.
This also drops cookies and authorization when forwarding away from the same origin.

feat: Added HTTP headers for auth and improved redirect code

---

src/actors/objects/http.rs
src/actors/objects/paths.rs
src/actors/objects/s3.rs
src/types.rs
tests/integration/test_basic.py
tests/integration/test_s3.py

unsure if casing should only apply to particular path segments, but I assume it just applies to the entire path

feat: Add casing parameter to source config

---

src/endpoints/proxy.rs
src/types.rs

This adds the SSQP defined lookup keys for non windows platforms to the
proxy.

feat: Added non windows ssqp support to proxy

---

src/actors/cficaches.rs
src/actors/symcaches.rs

fix: Do not report object parsing errors twice

---

Cargo.lock
Cargo.toml
src/actors/cficaches.rs
src/actors/common/cache.rs
src/actors/objects/mod.rs
src/actors/symcaches.rs
symsorter/Cargo.toml

This discards symcaches and cficaches with an outdated version (actually, any version that is not current) and computes them again.

ref(cache): Regenerate outdated caches automatically

---

Cargo.lock
symsorter/Cargo.toml
symsorter/src/app.rs

I don't have enough motivation to figure out how to fix the concurrency support
in symsorter.  But since I converted much stuff now I really do not need this
concurrency support any more.

feat(symsorter): Remove concurrency support for symsorter

---

src/actors/objects/mod.rs

Extracted from #80, preferrably deploy this with #82 such that we get new, better symcaches.

fix: Prefer symbol tables over nothing

---

Cargo.lock
Cargo.toml
README.md
src/actors/objects/gcs.rs
src/actors/objects/http.rs
src/actors/objects/sentry.rs
src/app.rs
src/config.rs
src/http.rs
tests/integration/conftest.py
tests/integration/test_basic.py

feat: Block reserved IPs by default

---

Cargo.lock
Cargo.toml
src/actors/snapshots/tests__add_bucket-2.snap
src/actors/snapshots/tests__add_bucket.snap
src/actors/snapshots/tests__apple_crash_report.snap
src/actors/snapshots/tests__minidump_linux-2.snap
src/actors/snapshots/tests__minidump_linux.snap
src/actors/snapshots/tests__minidump_macos-2.snap
src/actors/snapshots/tests__minidump_macos.snap
src/actors/snapshots/tests__minidump_windows-2.snap
src/actors/snapshots/tests__minidump_windows.snap
src/actors/snapshots/tests__remove_bucket-2.snap
src/actors/snapshots/tests__remove_bucket.snap

See mitsuhiko/insta#46
Makes the repo workable on Windows as a nice side effect :)

test(insta): Upgrade insta to fix snapshot paths

---

Cargo.lock
Cargo.toml
src/actors/snapshots/tests__add_bucket-2.snap
src/actors/snapshots/tests__add_bucket.snap
src/actors/snapshots/tests__apple_crash_report.snap
src/actors/snapshots/tests__minidump_linux-2.snap
src/actors/snapshots/tests__minidump_linux.snap
src/actors/snapshots/tests__minidump_macos-2.snap
src/actors/snapshots/tests__minidump_macos.snap
src/actors/snapshots/tests__minidump_windows-2.snap
src/actors/snapshots/tests__minidump_windows.snap
src/actors/snapshots/tests__remove_bucket-2.snap
src/actors/snapshots/tests__remove_bucket.snap
src/actors/symbolication.rs
src/app.rs
src/main.rs
src/test.rs

Updates the test suite to spawn an actual HTTP symbol server. This allows us to test actual downloads.

test: Modernize symbolication tests and update insta

---

Cargo.lock
Cargo.toml
src/actors/objects/common.rs
src/types.rs
src/utils/paths.rs

This is in preparation of separating the object actor from download logic.

ref(objects): Refactor prepare_download_paths and remove itertools

---

src/actors/objects/http.rs
src/utils/http.rs

This is in preparation of separating the object actor from download logic.

ref(http): Refactor HTTP redirects

---

symsorter/Cargo.lock
symsorter/Cargo.toml
symsorter/src/app.rs

feat(symsorter): Added improved symsorter for the new unified format

---

src/actors/symbolication.rs
src/endpoints/applecrashreport.rs
src/endpoints/minidump.rs
src/utils/multipart.rs

Less complex and still performant.

ref: Load minidump into memory

---

cloudbuild.yaml

Ported logic from https://github.com/getsentry/sentry/blob/master/docker/cloudbuild.yaml

build(docker): Push images to Docker Hub too

---

src/actors/cficaches.rs
src/actors/objects/mod.rs
src/actors/symbolication.rs
src/actors/symcaches.rs
src/utils/futures.rs

This temporarily makes things worse, but will help to migrate the entire code base to futures 0.3

ref(futures): Migrate threadpool to futures 0.3

---

docs/advanced/source-bundles.md
docs/advanced/symbol-server-compatibility.md
docs/api/index.md
mkdocs.yml
src/actors/snapshots/tests__minidump_linux-2.snap
src/actors/snapshots/tests__minidump_macos-2.snap
src/actors/snapshots/tests__minidump_windows-2.snap
src/utils/paths.rs

This adds support for looking up source bundles from more sources.

feat: Added source bundles to more symbol server sources

---

docs/advanced/source-bundles.md
docs/advanced/symbol-server-compatibility.md
symsorter/README.md
symsorter/src/app.rs

This came up as a suggestion from a conversation i had on discord for how to make symsorter more useful.

feat: Added source support to symsorter

---

src/actors/objects/gcs.rs

fix(gcs): Properly refresh expired tokens

---

src/actors/objects/gcs.rs

I'm a little unsure of this metrics choice.  The sum of these is probably a proxy for number of requests made?  But that's really not obvious which is why I don't like this so much.  Which makes me wonder if it should really be tracked in a metric in the caller.  The `token.requests` metric would then stand on its own.

feat(metric): Add metrics to track OAuth token usage

---

Cargo.lock
src/actors/symbolication.rs

This is an approximation since we have to use SystemTime rather than
Instant because the latter is not serialiseable.  It's probably good
enough to give some indication though.

Add a metric showing spawn time for procspawn

---

src/actors/symbolication.rs

Demangles a mangled function name explicitly if symbolication fails using the following rules:
- Only demangle if either `symbol` or `function` are set, but not both
- If demangling fails, leave the fields
- If demangling succeeds, write the demangled name into `function`
- Write the mangled name into `symbol`
cc @HazAT

fix: Demangle functions when symbolication fails

---

src/actors/common/cache.rs

Refactors the cache code and fixes race conditions in cache handling: 
- Most importantly, it keeps the lock while checking and inserting into the cache, and creating a computation future. 
- The response is sent into the channel *after* dropping it from the map. This ensures that clients retrieving an existing channel always get a response.
- Instead of panicking, emit an error if computation fails for any reason. This is usually only the case if the arbiter restarts or a panic occurs. Otherwise, we always receive an explicit Result and send that into the channel.
Follow-up to https://github.com/getsentry/symbolicator/pull/224
Adds cache changes from https://github.com/getsentry/symbolicator/pull/112

ref(cache): Avoid races and leaks in file handling

---

tests/integration/conftest.py

~TODO: env var changes in Travis.~

test: Use the new symbol bucket

---

src/actors/symbolication.rs

This fixes a particular case where we reported that the C++ symbol `_Task_impl` cannot be demangled.
This happens because `_T` is detected as `Swift` symbol. The original debug file declared it as `C++`, meaning its an unmangled name in C++ code. In this case, detection resolves a false-positive which should be ignored.

fix: Do not report false-positives in demangling

---

src/services/download/gcs.rs
src/services/download/s3.rs
src/services/download/sentry.rs
src/sources.rs

This reduces some knowledge the callers have on this as well.

ref: Make some fields in sources private

---

src/config.rs
src/sources.rs
tests/integration/test_basic.py

Some of the fields sent in can be unkonwn it appears.  Let's be more lenient.

fix: Allow unknown fields

---

src/services/download/sentry.rs

This fixes a bug in the Sentry downloader: When a module neither specifies a code identifier nor a debug identifier, the downloader previously listed all files from the project. Instead, we should not issue a search and instead return an empty result set.

fix(downloader): Only search sentry with filters

---

docs/index.md

This was wrong and didn't get rendered correctly.  Thanks markdown.

docs: fix bullet points indentation

---

Cargo.lock
Cargo.toml
src/app.rs
src/cache.rs
src/cli.rs
src/config.rs
src/logging.rs
src/main.rs
src/server.rs

ref: Replace failure with anyhow for CLI errors

---

symsorter/Cargo.lock
symsorter/Cargo.toml
symsorter/src/app.rs
symsorter/src/utils.rs

Also updated symbolic dependency version because of the lifetime inference problem.

ref: Replace failure with anyhow in symsorter

---

Cargo.lock
Cargo.toml
src/services/download/mod.rs
src/utils/sentry.rs

meta: Bump sentry and use upstream SentryFutureExt

---

.vscode/launch.json
src/actors/cficaches.rs
src/actors/objects/mod.rs
src/actors/symbolication.rs
src/actors/symcaches.rs
src/logging.rs
src/types.rs

the next iteration on top of #269 

ref: Convert symbolicator actors to thiserror

---

Cargo.lock
Cargo.toml
src/actors/cficaches.rs
src/actors/objects/mod.rs
src/actors/symbolication.rs
src/actors/symcaches.rs
src/endpoints/proxy.rs

ref: Use failure-less symbolic

---

.craft.yml
cloudbuild.yaml

ci(docker): Rename latest tag to nightly

---

.github/workflows/ci.yml

ci: Correctly name toolchain being installed

---

src/actors/symbolication.rs
src/endpoints/applecrashreport.rs

This does not go as far as #179 but cleans up some things nevertheless

ref: Make some of the symbolication fns async

---

src/utils/hex.rs

Looks like we do not need a macro here.

ref: demacro HexValue

---

wasm-split/src/main.rs

ref: Unwrap instead of match

---

src/services/download/mod.rs
src/sources.rs
src/test.rs

ref(sources): Introduce a SourceId newtype

---

.github/workflows/nightly.yml
src/config.rs
src/utils/http.rs

Some nightly clippy warnings that seem sensible.
This also gives a unique name for each clippy run, as this is used for
some caching and is probably the reason we don't get nice clippy
results currently.
----

style(clippy): Unused result and contains

---

.craft.yml
.github/workflows/release.yml

ci(release): Add support for release via getsentry/publish repo

---

Cargo.lock
Cargo.toml

build: Update uncritical dependencies

---

Cargo.lock
Cargo.toml
src/utils/sentry.rs

ref: Update Sentry SDK and vendor failure integration

---

src/utils/addr.rs

ref(clippy): Remove needless question mark

---

Cargo.lock
Cargo.toml
src/test.rs
src/utils/http.rs

test: Switch to using warp for the symbol server

---

Cargo.lock
Cargo.toml
src/services/download/gcs.rs

We used to be on a custom git version, but we should be able to use a
normal release by now.

ref(deps): Upgrade jsonwebtoken crate

---

src/utils/paths.rs

ref(clippy): Avoid redundant slicing

---

Makefile

build: Replace virtualenv in the Makefile with venv

---

Cargo.lock

This pulls in a fix for pdb handling

fix: Update symbolic

---

Dockerfile

Follow-up to #398 and #400, which aligns the build sequence with the original script. The initial change lead to an empty binary.
Also switches from the `rust/slim-stretch` base image to `debian/stretch-slim` and installs Rust manually. Since the official Rust image is no longer updated, we have to install Rust ourselves to build with the latest stable compiler. This is now required after #399.

fix(build): Update build order and build with latest Rust

---

Cargo.lock
crates/process-event/Cargo.toml
crates/process-event/src/main.rs

feat: Create a tool to feed minidumps and events to symbolicator

---

Dockerfile

We only want to build the main crate and ignore any others.  This
sadly means for now that we need to build without --locked but CI
already ensures that our dependencies won't change.
This also harcodes the Rust version, otherwise this is lost at the
mercy of docker's caching and never really upgraded.

build(docker): Ignore other crates

---

crates/symbolicator/src/utils/multipart.rs

ref: Log request options

---

Cargo.lock

build: Update symbolic

---

crates/symbolicator/src/services/symbolication.rs

fix: Improve stacktrace metrics classification

---

crates/symbolicator/src/services/bitcode.rs

Wraps fetching bcsymbolmap files in a sentry scope so its scope props do not leak out to normal symcache errors that are being captured.

fix: Avoid auxdif props to leak to symcache Errors

---

crates/symbolicator/src/services/symbolication.rs

We report and error and save the minidump whenever the new stackwalking method takes 5 seconds or longer.

ref: Report slow stackwalking runs as errors

---

CHANGELOG.md
Cargo.lock

Update symbolic to correctly apply bcsymbolmaps to symbol and filenames coming from DWARF.

ref: Update symbolic

---

CHANGELOG.md
crates/symbolicator/src/config.rs
crates/symbolicator/src/services/download/mod.rs
docs/index.md

This addresses [NATIVE-57](https://getsentry.atlassian.net/browse/NATIVE-57).

feat: Make timeout for downloading configurable

---

crates/symbolicator/src/server.rs

ref: Increase internal download concurrency

---

crates/symbolicator/src/cache.rs

This makes the checking on cache files a little more lenient: as long as the file begins with the correct set of bytes then it's a valid malformed cache entry (despite its name).
This should make it easier to merge and deploy https://github.com/getsentry/symbolicator/pull/502, particularly if it goes bad: if it turns out that #502's changes need to be reverted then the cache won't be completely broken if this PR's changes are around.

feat(cache): Be less strict about the contents of malformed cache files so they're easier to extend

---

crates/symbolicator/src/services/symbolication.rs

This addresses https://getsentry.atlassian.net/browse/NATIVE-170.

feat: Report number of in-flight requests when a new one is made

---

crates/symbolicator/src/services/download/mod.rs

ref(download): Simplify debug logging output

---

crates/symbolicator/src/services/cacher.rs

Previously the whole cache lookup was being deduplicated by a channel indirection.
This splits that apart and makes only the actual computation deduplicated.
This opens up the road to be able to both eagerly compute, and lazily recompute cached items.
This does not completely avoid the `Arc`s, and it had to do quite a bit of extra work to avoid using `self`, as using that would get us into lifetime troubles.

ref: Move deduplication logic to CacheItemRequest::compute

---

crates/symbolicator/src/endpoints/applecrashreport.rs
crates/symbolicator/src/endpoints/minidump.rs
crates/symbolicator/src/server.rs
crates/symbolicator/src/services/cficaches.rs
crates/symbolicator/src/services/download/mod.rs
crates/symbolicator/src/services/mod.rs
crates/symbolicator/src/services/objects/data_cache.rs
crates/symbolicator/src/services/symbolication.rs
crates/symbolicator/src/services/symcaches.rs
crates/symbolicator/src/test.rs
crates/symbolicator/src/utils/futures.rs

ref: Replace ThreadPool with tokio runtime

---

docs/index.md

doc: Document recently added options

---

crates/symbolicator/src/services/symbolication.rs

ref: Move iterative stackwalking into its own method

---

Dockerfile

whoops, we haven't done this for ages

build(rustc): Bump rust compiler version

---

crates/symbolicator/src/services/objects/meta_cache.rs

This is terrible for grouping, we should use sentry directly and put
this information on the scope.

ref: Do not put cache keys in errors

---

crates/symbolicator/src/cache.rs

ref: simplify some tests and file truncating

---

crates/symbolicator/src/services/shared_cache.rs

This adds some counters for bytes, on the metrics-side of things we
can turn that into a rough transfer rate to give us some idea of how
much we're transferring.

ref(shared-cache): Counts bytes to/from shared cache

---

crates/symbolicator/src/services/download/mod.rs
crates/symbolicator/src/services/download/s3.rs

This should also improve our sentry error grouping for these.

ref(s3): Improve error reporting a little

---

Dockerfile

Nothing but the bleeding edge.

build(rustc): Bump rust version

---

docs/advanced/shared-cache.md
mkdocs.yml

Some basic pointers, this is an advanced thing after all.
NATIVE-248

docs: Document the shared cache

---

crates/symbolicator/src/services/cacher.rs

Given that the cache system has this it should probably be respected.
NATIVE-248

feat(shared-cache): Respect CacheItemRequest::should_load

---

crates/process-event/Cargo.toml
crates/symbolicator/Cargo.toml
crates/symsorter/Cargo.toml
crates/wasm-split/Cargo.toml

build: Bump rust edition

---

crates/symbolicator/src/services/shared_cache.rs

This allows us to create error ratios, error ratios are good and we
need more of them.

feat(metrics): Add status tag to shared_cache metrics

---

crates/symbolicator/src/services/cacher.rs
crates/symbolicator/src/utils/paths.rs
crates/symsorter/src/app.rs

ref(clippy): Some nightly clippy fixes

---

crates/symbolicator/src/services/shared_cache.rs

We pile up a lot of futures when this was misbehaving.  This makes
sure we put some reasonable limits on these things.

ref(shared-cache): Have a timeout around getting auth tokens

---

crates/symbolicator/src/services/download/sentry.rs

ref(clippy): Avoid needless string creation

---

Cargo.lock
crates/symbolicator/Cargo.toml
crates/symbolicator/src/endpoints/error.rs

A regular `cargo update` combined with a bit of breaking change updates to the Axum parts.

ref: Update dependencies, esp Axum

---

crates/symbolicator/src/services/shared_cache.rs

ref(shared-cache): a tiny bit more logging

---

Cargo.lock

deps: Bump dependencies, in particular symbolic

---

Cargo.lock
crates/symbolicator/Cargo.toml
crates/symbolicator/src/endpoints/mod.rs
crates/symsorter/Cargo.toml

meta: Bump sentry-rust to released version

---

CHANGELOG.md

doc: Update changelog

---

crates/symbolicator/src/services/symbolication.rs

This changes `StackWalkMinidumpResult` to be in line with https://github.com/getsentry/symbolicator/pull/645 in preparation of comparing stackwalking implementations.
Instead of vectors-of-pairs `all_modules` and `referenced_modules`, the struct contains a map `modules` (corresponding to `all_modules`) and a set `missing_ids`.

ref(symbolication): Restructure StackWalkMinidumpResult

---

crates/symbolicator/src/services/shared_cache.rs

This is like, surprisingly difficult.  But hopefully this configures
the shared cache errors better.  Specifically we were receiving errors
which had the GCS bucket name and key in them, meaning that each error
is unique rather than de-duplicated.

ref(shared-cache): Configure sentry errors

---

Cargo.toml
wrk_minidump.lua

meta: Add a wrk script to benchmark local symbolicator

---

crates/symbolicator/src/services/symbolication.rs

ref: Resolve an outdated by-value Self

---

Cargo.lock
crates/symbolicator/src/services/symbolication.rs

rust-minidump: Update rust-minidump

---

crates/symbolicator/src/services/snapshots/symbolicator__services__symbolication__tests__minidump_windows_rust_minidump.snap

test(rust-minidump): Accept windows test snapshot

---

crates/symbolicator/src/services/symbolication.rs

This fixes up the stacktraces returned by breakpad by renaming the `eflags` register to `efl`. Without doing this, we get a ton of spurious differences between the two in our stackwalking experiments.

feat(symbolication): Ignore eflags/efl in comparisons

---

crates/symbolicator/src/services/symbolication.rs

This factors the comparison between breakpad and rust-minidump out into its own function and replaces instances of "old" and "new" with the clearer "breakpad" and "rust_minidump".

ref(symbolication): Clean up comparison code a bit

---

crates/symbolicator/src/services/cacher.rs
crates/symbolicator/src/services/symbolication.rs

ref: Pacify clippy

---

crates/symbolicator/src/services/symbolication.rs

ref(symbolication): Don't return empty CodeIds

---

crates/process-event/src/main.rs

feat(process-event): Add --rust-minidump flag

---

Cargo.lock
crates/symbolicator/Cargo.toml
crates/symbolicator/src/endpoints/mod.rs
crates/symbolicator/src/services/symcaches.rs

ref: Update dependencies

---

.github/dependabot.yml

ci: Configure dependabot to follow our commit messages style

---

Cargo.lock
crates/process-event/src/main.rs
crates/symbolicator/Cargo.toml
crates/symbolicator/src/services/symbolication/mod.rs

Still waiting for a release of this.

ref: Adapt to rust-minidump Cpu changes

---

crates/symbolicator/src/services/symbolication/mod.rs

ref: Add cfi file to scope on parsing

---

crates/symbolicator/src/services/symbolication/mod.rs

This resolves a FIXME by avoiding a bunch of string allocations and parsing a debug-id which can be expensive

ref: Avoid an expensive computation

---

.github/workflows/dependabot.yml

ci(dependabot): We need to squash merge

---

.github/workflows/dependabot.yml

ci(dependabot): Auto merge minor updates as well

---

crates/symbolicator/src/services/minidump.rs

fix: Apply clippy lint

---

.github/workflows/ci.yml

fix(ci): reorder sentry setup to earlier (startup race?)

---

Dockerfile

fix: Unbreak Docker build with symbolicator-crash

---

.github/workflows/build.yml
Dockerfile
cloudbuild.yaml

same as #827 just with a `release` branch so that cloudbuild runs

build: Fetch recursive submodules for cloudbuild build

---

.github/workflows/update-deps.yml

See https://github.com/getsentry/sentry-unity/issues/788 for context
sample PR: https://github.com/vaind/sentry-symbolicator/pull/2

ci: automatic submodule dependency update

---

CHANGELOG.md
Cargo.lock
Dockerfile
crates/symbolicator/src/services/symcaches/mod.rs
tests/integration/test_basic.py

See the README and symcache history for the important changes

deps: Update deps, in particular symbolic with a ton of SymCache fixes

---

docs/advanced/symbol-server-compatibility.md

doc: fix a documentation link for debuginfod

---

.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/weekly.yml

- Remove usage of abandonen actions-rs
- Update rust-cache@v2
- Use stable rust for coverage builds

ci: Modernize CI setup a bit

---

crates/symbolicator/src/services/download/mod.rs

should help with https://github.com/getsentry/team-stacktrace-private/issues/16

fix: Surface Permissions problems for Sentry internal Symbol Source

---

.github/workflows/stackaid.yml

This action will generate a stackaid.json file, listing the dependencies that Sentry wants to fund on StackAid. FYI, I'm one of the @stackaid founders helping @chadwhitacre setup Sentry's funding.

Add action to generate stackaid.json

---

crates/symbolicator-service/src/services/symbolication/apple.rs
crates/symbolicator-service/src/services/symbolication/mod.rs
crates/symbolicator/src/service.rs

ref: Remove special handling of Apple Perse errors from SymbolicationError

---

crates/symbolicator-service/src/cache.rs

Resets the duration when we just touched the file, plus makes that a documented constant.

ref: Correctly refresh TouchIn expiration on touch

---

crates/process-event/src/main.rs
crates/symbolicator-service/src/services/cacher.rs
crates/symbolicator-service/src/services/download/gcs.rs
crates/symbolicator-service/src/services/download/locations.rs
crates/symbolicator-service/src/services/download/mod.rs
crates/symbolicator-service/src/services/download/s3.rs
crates/symbolicator-service/src/services/minidump.rs
crates/symbolicator-service/src/services/objects/data_cache.rs
crates/symbolicator-service/src/services/symbolication/process_minidump.rs
crates/symbolicator-service/src/types/objects.rs
crates/symbolicator-service/src/utils/addr.rs
crates/symbolicator-sources/src/paths.rs
crates/symbolicator-sources/src/sources.rs
crates/symbolicator-stress/src/main.rs
crates/symbolicator/build.rs
crates/symbolicator/src/endpoints/metrics.rs
crates/symbolicator/src/logging.rs
crates/symbolicator/src/service.rs
crates/symbolicli/src/main.rs
crates/symsorter/src/app.rs

ref: Fix clippy lints

---

.github/workflows/image.yml
Dockerfile

Add image workflow

---

Cargo.lock
crates/symbolicator-service/src/services/bitcode.rs
crates/symbolicator-service/src/services/download/filesystem.rs
crates/symbolicator-service/src/services/download/gcs.rs
crates/symbolicator-service/src/services/download/http.rs
crates/symbolicator-service/src/services/download/mod.rs
crates/symbolicator-service/src/services/download/s3.rs
crates/symbolicator-service/src/services/download/sentry.rs
crates/symbolicator-service/src/services/fetch_file.rs
crates/symbolicator-service/src/services/il2cpp.rs
crates/symbolicator-service/src/services/objects/data_cache.rs
crates/symbolicator-service/src/services/objects/meta_cache.rs
crates/symbolicator-service/src/services/objects/mod.rs
crates/symbolicator-service/src/types/objects.rs
crates/symbolicator-sources/Cargo.toml
crates/symbolicator-sources/src/lib.rs
crates/symbolicator-sources/src/remotefile.rs
crates/symbolicator-sources/src/sources.rs
crates/symbolicator-sources/src/sources/filesystem.rs
crates/symbolicator-sources/src/sources/gcs.rs
crates/symbolicator-sources/src/sources/http.rs
crates/symbolicator-sources/src/sources/s3.rs
crates/symbolicator-sources/src/sources/sentry.rs

Move `RemoteFile` into `symbolicator-sources`

---

crates/symbolicator/src/endpoints/minidump.rs
crates/symbolicator/src/endpoints/snapshots/symbolicator__endpoints__minidump__tests__integration_microsoft.snap

test: Run minidump e2e tests on CI

---

crates/symbolicator-stress/src/main.rs

Now maintains the original sorting order of the workloads

ref: Improve stresstest output slightly

---

crates/symbolicator-service/src/cache.rs
crates/symbolicator-service/src/services/fetch_file.rs
crates/symbolicator-service/src/services/objects/data_cache.rs
crates/symbolicator-service/tests/integration/source_errors.rs

ref: Stop writing legacy cache markers

---

.github/workflows/update-deps.yml

TODO: someone with permissions please update the secret name after setting it up

ci: update updater

---

.github/workflows/update-deps.yml

ci: Fix github token

---

crates/symbolicator-service/src/services/cacher.rs
crates/symbolicator-service/src/services/shared_cache.rs

Instead of using a `tokio::File`, this now uses a `ByteView`, which simplifies things and also makes `lookup_local_cache` fully sync.

ref: Make `SharedCache` store a `ByteView`

---

crates/symbolicli/README.md

doc(symbolicli): How to enable logging

---

Cargo.lock
crates/symbolicator-service/Cargo.toml

deps: Update sentry-rust to 0.29.2

---

crates/symbolicator-service/src/caching/memory.rs

This turns metrics of the form `caches.{name}.foo` into `caches.foo` with a `cache => name` tag.

ref(metrics): Turn cache names into tags

---

crates/symbolicator-service/src/caching/memory.rs

fix(metrics): Missed a metric when turning cache names into tags

---

crates/symbolicator-service/src/services/symbolication/sourcemap.rs

This refactors the the `collect_stacktrace_artifacts` funtion to get rid of some nested `if let`s. It also incorporates the `get_sourcemap_reference` function into `resolve_sourcemap_url`.

refactor collect_stacktrace_artifacts

---

crates/symbolicator-service/src/services/symbolication/module_lookup.rs

This makes the formatting a little less confusing.

ref: Restructure module_lookup a bit

---

docs/advanced/symbol-lookup.md

doc: Add portable pdbs to symbol lookup

---

docs/advanced/symbol-server-compatibility.md

doc: Add portable pdbs to symbol server compatibility

---

crates/symbolicator-service/src/services/symbolication/sourcemap.rs

- fix: Rewind source_file after locating sourcemap reference
Note:
> @Swatinem I would recommend to transform the NamedTempFile to a ByteView prior to working with it
(which is over my skills without too much time investment)
- ref: Use fold_function_name after extracting it from token

Rewind source_file after locating sourcemap and fold_function_name

---

crates/symbolicator-service/src/services/symbolication/sourcemap.rs

`SourcemapCache`s are computed in parallel for each `abs_path` in the request, using `join_all`.

ref(sourcemap): Enable concurrent smcache computation

---

gocd/pipelines/symbolicator-canary.yaml
gocd/pipelines/symbolicator-lpq.yaml
scripts/create-sentry-release

https://github.com/getsentry/symbolicator/pull/1016#issuecomment-1421272942

cd: separate canary deployments

---

crates/symbolicator-service/src/services/symbolication/mod.rs
crates/symbolicator-service/src/services/symbolication/module_lookup.rs

refactor: let get_context_lines() take RawFrame 

---

crates/symbolicator-service/src/services/cficaches.rs
crates/symbolicator-service/src/services/symcaches/mod.rs

ref: Remove fallback CacheVersions

---

Cargo.lock
crates/symbolicator-service/Cargo.toml
crates/symbolicator-service/src/services/sourcemap.rs
crates/symbolicator-service/tests/integration/sourcemap.rs

feat: Handle BASE64 encoded sourcemaps

---

crates/symbolicator-service/src/services/symbolication/process_minidump.rs

fix: Improve error for missing/broken minidump module stream

---

Cargo.lock
crates/process-event/Cargo.toml
crates/symbolicator-service/Cargo.toml
crates/symbolicator-service/src/services/sourcemap_lookup.rs
crates/symbolicator-sources/Cargo.toml
crates/symbolicator/Cargo.toml
crates/symbolicli/Cargo.toml
crates/symsorter/Cargo.toml

This is a first stab at the simplified flow described in https://github.com/getsentry/symbolicator/issues/1054.

Implement a skeleton to work with Artifact Bundles

---

crates/symbolicator-service/src/services/sourcemap_lookup.rs

This turns `FileKey` into an enum with cases for `MinifiedSource`, `Source`, and `SourceMap`. In each case, different combinations of `abs_path` and `debug_id` are required or optional.
It also changes the parameters of `get_sourcemapcache` from `key: FileKey` to `(abs_path: &Url, debug_id: Option<DebugId>)` because the `abs_path` is definitely required. Alternatives would be to
1. leave it as it is and return an error if `key.abs_path()` is `None`, or
2. introduce a type specifically for the key of a `MinifiedSource`.

ref: Make FileKey an enum

---

crates/symbolicator-service/src/services/symbolication/js.rs

This parses a `raw_frame`'s `abs_path` into a URL once at the start of the loop and reuses that result. Previously we parsed multiple times, but if the first time failed, we `continue`d anyway so the second parse could never fail.

ref: Parse abs_path only once in symbolicate_js

---

crates/symbolicator-service/src/caching/cleanup.rs
crates/symbolicator-service/src/caching/config.rs
crates/symbolicator-service/src/caching/memory.rs
crates/symbolicator-service/src/caching/mod.rs
crates/symbolicator-service/src/services/caches/downloads.rs
crates/symbolicator-service/src/services/caches/mod.rs
crates/symbolicator-service/src/services/caches/sourcefiles.rs
crates/symbolicator-service/src/services/caches/versions.rs

This might be useful for downloading individual source files.

feat: Add a cache for arbitrary unvalidated downloads

---

gocd/pipelines/symbolicator-lpq.yaml

The label was added in https://github.com/getsentry/ops/pull/6135

CI: Add lpq pipeline

---

gocd/pipelines/symbolicator-lpq.yaml

Pipeline names need to be unique.

fix: Rename lpq pipeline

---

Cargo.lock
crates/wasm-split/Cargo.toml
crates/wasm-split/src/main.rs

wasmbin had various improvements to the API and the docs, including addition of few more "well-known" custom sections since, so this simplifies the code quite a bit.
Unfortunately, I didn't find any tests so would leave it up to the reviewer.

Upgrade wasmbin

---

crates/symbolicator-service/src/services/sourcemap_lookup.rs
crates/symbolicator-service/src/services/symbolication/js.rs

This adds and documents a couple of shortcuts we do when we have a `DebugId`:
- We will not collect/query for file stems on Sentry.
- We assume the file will be found in one of the prefetched `ArtifactBundle`s
- We will not fall back to looking up by filename in `ArtifactBundle`s.
- We will not fall back to scraping from the Web.
- We assume the `SourceMap` has embedded sources.

ref: Enforce assumptions around DebugId

---

crates/symbolicator-service/src/services/sourcemap_lookup.rs
crates/symbolicator-service/src/services/symbolication/js.rs

Adds a bunch of metrics, mostly related to usage of bundles and artifacts, and also adds detailed docs to how lookup of files is supposed to happen.

Add metrics and docs to SourceMap processing

---

crates/symbolicator-service/src/services/download/sentry.rs

Previously, we were filtering Sentry API requests by `file_type`.
This was suboptimal, as it leads to having multiple queries for executable, debuginfo (bcsymbolmap, il2cpp) and sourcebundle for one DebugId where now one query gives us all the files.
The query will also now prefer `debug_id` over `code_id`, as the Sentry API does the same thing.
This way, we should be able to much better utilize the Sentry API query cache, apart from doing a lot less requests to begin with.

Only do one Sentry API lookup per `DebugId`

---

crates/symbolicator-service/src/services/sourcemap_lookup.rs
crates/symbolicator-service/src/services/symbolication/js.rs
crates/symbolicator-service/tests/integration/sourcemap.rs
crates/symbolicator/src/endpoints/symbolicate_js.rs

Add `release` to JS requests and use it

---

crates/symbolicator-service/src/services/symbolication/js.rs
crates/symbolicator-service/src/types/mod.rs

ref: https://github.com/getsentry/sentry/blob/02bf7f0df65bd662a4caca0c4e53aa281aea1488/src/sentry/lang/javascript/processor.py#L580-L608

ref: Port get_function_for_token from monolith

---

crates/symbolicator-service/tests/integration/sourcemap.rs

Just a helping hand for our needs.

test: Add a manual js symbolication test that eases with debugging

---

gocd/pipelines/symbolicator-canary.yaml
gocd/pipelines/symbolicator-lpq.yaml
gocd/pipelines/symbolicator.yaml

Update to new k8s deploy script

---

crates/symbolicator-service/src/services/sourcemap_lookup.rs

- Add some early returns to lookup by bundle or artifact.
- Avoid another lookup when an API request did not yield new data (bundles or artifacts).
- Do not parse artifact bundles (aka Object files) again but use the existing ObjectHandle.

Optimize JS File Lookup

---

.github/workflows/ci.yml
.github/workflows/image.yml
.github/workflows/lint-pipelines.yml

Fix the GHA concurrency settings

---

crates/symbolicator-service/src/services/sourcemap_lookup.rs

Normalize double-slashes when joining paths

---

crates/symbolicator-service/src/types/objects.rs

Remove unused mut flagged by clippy

---

crates/symbolicator-service/src/services/sourcemap_lookup.rs

Fixes https://github.com/getsentry/sentry/issues/48924

Collect more metrics how a JS artifact was found

---

CHANGELOG.md
Cargo.lock
crates/symbolicator-service/Cargo.toml
crates/symbolicator-service/src/services/download/s3.rs
crates/symbolicator-sources/Cargo.toml

Upgrade aws-sdk-rust from 0.52.0 to release 2023-05-24

---

crates/symbolicator-service/src/services/download/mod.rs
crates/symbolicator-service/src/services/sourcemap_lookup.rs

ref(js): Bail in scraping if there's no valid host

---

crates/symbolicator-sources/src/paths.rs
crates/symbolicator/src/endpoints/proxy.rs
crates/symbolicator/src/main.rs

Fix symstore proxy path parsing

---

crates/symbolicator-service/src/services/sourcemap_lookup.rs

feat(js): Only scrape from http sources

---

gocd/generated-pipelines/symbolicator-next-monitor.yaml
gocd/generated-pipelines/symbolicator-next-us.yaml
gocd/templates/bash/deploy.sh

Correct k8s-deploy script name

---

Cargo.lock
crates/symbolicator-service/src/services/sourcemap_lookup.rs
crates/symbolicator/src/main.rs
crates/symbolicli/src/main.rs
crates/symbolicli/src/settings.rs

- Fixes a clippy lint
- Reformats using nightly rustfmt
- Does a `cargo update`

Crate maintenance

---

crates/symbolicli/README.md
crates/symbolicli/symboliclirc.example

docs(symbolicli): Add example config file

---

crates/symbolicator-service/src/services/download/mod.rs

Does this suffice to make the error and the project identifiable?

feat: Emit error for sentry:project source

---

gocd/generated-pipelines/rollback-symbolicator.yaml
gocd/templates/jsonnetfile.json
gocd/templates/jsonnetfile.lock.json
gocd/templates/symbolicator.jsonnet

Noticed that the rollback pipeline will not work without an elastic profile id.

Update pipedream lib for rollback agent

---

crates/symbolicator-service/src/caching/cleanup.rs
crates/symbolicator-service/src/caching/fs.rs

This will give a summary of how much was removed and retained for each cache directory.

Add more logs to cleanup process

---

crates/symbolicator-service/src/services/sourcemap_lookup.rs

The original idea of file-stem trimming was to find both `foo.min.js` and `foo.map` with just one request, as the stem of those two is `foo`.
However the simplistic "split at first `.`" fails for situations when we have `main.$HASH.min.js`, where the `$HASH` part was being trimmed off. However the API would have way too many matches for just `main` in that case, and might thus not return the match that we are interested in.
Therefore, we are only trimming known suffixes, and keep other `.`-separated parts intact. This might increase the number of API requests we do, but should yield better results.

Improve file-stem trimming

---

gocd/generated-pipelines/rollback-symbolicator.yaml
gocd/generated-pipelines/symbolicator-customer-2.yaml
gocd/pipelines/symbolicator-canary.yaml
gocd/pipelines/symbolicator-lpq.yaml
gocd/templates/jsonnetfile.json
gocd/templates/jsonnetfile.lock.json

NOTE: I've also moved the lpq and canary pipelines to the end of the list of pipelines in the UI since they are used less frequently.

Add customer-2 to pipedream

---

.github/workflows/validate-pipelines.yml

see https://github.com/getsentry/relay/pull/2376

ci: only render gocd pipelines if relevant files are changed

---

gocd/generated-pipelines/symbolicator-customer-1.yaml
gocd/generated-pipelines/symbolicator-customer-2.yaml
gocd/generated-pipelines/symbolicator-customer-3.yaml
gocd/generated-pipelines/symbolicator-customer-4.yaml
gocd/generated-pipelines/symbolicator-customer-5.yaml
gocd/generated-pipelines/symbolicator-customer-6.yaml
gocd/templates/pipelines/symbolicator.libsonnet

Allow ST deploys to skip manual approval

---

CHANGELOG.md
Cargo.lock
crates/symbolicator-service/Cargo.toml
crates/symbolicator-service/src/services/download/s3.rs
crates/symbolicator-sources/Cargo.toml

Fixes https://github.com/getsentry/symbolicator/issues/1281.

Update aws-sdk-rust to release-2023-08-03

---

crates/symbolicator-service/src/services/sourcemap_lookup.rs

Simplify scraping errors and add NOTE about caching

---

crates/symbolicator-service/src/caching/cache_error.rs

Fix nightly clippy lints

---

cloudbuild.yaml

See https://cloud.google.com/build/docs/api/reference/rest/v1/projects.builds#Build.MachineType
The docs were quite hard to find for this.

Use proper cloudbuild machineType

---

Cargo.lock

build: Update reqwest

---

.github/workflows/ci.yml

Use `setup-sentry` defaults

---

Cargo.lock

Do a `cargo update`

---

.github/dependabot.yml
CHANGELOG.md

Adds dependabot for updating Github Actions.

build: add dependabot for github actions

---

crates/symbolicator/src/cli.rs

You can take a look at those here: https://sentry.my.sentry.io/organizations/sentry/performance/?landingDisplay=all&project=5&query=&statsPeriod=14d

Increase percentage of sampled transactions

---

Cargo.lock
crates/symbolicator-stress/Cargo.toml
crates/symbolicator-stress/src/stresstest.rs

This adds percentiles / quantiles to the stresstest output.
Pretty much just a small change to get more experience with `DDSketch`.

Use `DDSketch` to compute percentiles in stresstest

---

Cargo.lock
Cargo.toml
crates/symbolicator-service/Cargo.toml
crates/symbolicator-service/src/lib.rs
crates/symbolicator-service/src/logging.rs
crates/symbolicator-stress/Cargo.toml
crates/symbolicator-stress/src/logging.rs
crates/symbolicator-test/Cargo.toml
crates/symbolicator/Cargo.toml
crates/symbolicator/src/logging.rs
crates/symbolicli/Cargo.toml

Also consolidates all the usage sites and removes unused feature flags

Move `tracing` init into its own file

---

crates/symbolicator-proguard/src/interface.rs
crates/symbolicator-proguard/src/symbolication.rs
crates/symbolicator-proguard/tests/integration/proguard.rs

This is a port of `JavaStacktraceProcessor.process_frame`. It's still missing `in_app` handling.

feat(proguard): Implement frame remapping

---

Cargo.lock
crates/symbolicator-proguard/Cargo.toml
crates/symbolicator-proguard/src/interface.rs
crates/symbolicator-proguard/src/service.rs
crates/symbolicator-proguard/src/symbolication.rs

Also adds some docs and comments.

ref(proguard): Accumulate errors in symbolication

---

Cargo.toml
crates/symbolicator-js/Cargo.toml
crates/symbolicator-native/Cargo.toml
crates/symbolicator-proguard/Cargo.toml
crates/symbolicator-service/Cargo.toml
crates/symbolicator-stress/Cargo.toml
crates/symbolicator-test/Cargo.toml
crates/symbolicator/Cargo.toml
crates/symbolicli/Cargo.toml

Fixes https://github.com/getsentry/symbolicator/issues/1406

chore: update tokio to latest version

---

crates/symbolicator-js/src/lookup.rs

See https://github.com/rust-lang/rust-clippy/issues/12757.

chore: Silence buggy clippy lint

---

cloudbuild.yaml

faster caching, pull only occurs when needed

ref: use buildkit to build docker image

---

cloudbuild.yaml

gcr is deprecated and will be going away soon

ref: dual-write images to artifact registry

---

docs/api/proxy.md

docs: Add note about source layouts to proxy docs

---

.craft.yml
cloudbuild.yaml
gocd/templates/bash/cloudbuild-checks.sh
gocd/templates/bash/deploy.sh

now using artifact registry everywhere \o/

ref: remove gcr.io support

---

Cargo.lock
crates/symbolicator-service/Cargo.toml
crates/symbolicator-stress/Cargo.toml
crates/symbolicli/Cargo.toml

I've given @boshen 's cargo-shear a try: https://github.com/Boshen/cargo-shear

chore: remove unused dependencies

---

crates/symbolicator/src/endpoints/error.rs

See the comment in the change for the rationale.

fix: Don't report max requests errors to Sentry

---

Cargo.lock
crates/symbolicator-service/Cargo.toml
crates/symbolicator-service/src/metrics.rs

As that project in its current for is dead, lets remove sending metrics via the Sentry SDK
---
This is on top of #1493

Remove Sentry Metrics

---

gocd/templates/jsonnetfile.json
gocd/templates/jsonnetfile.lock.json

chore: Update gocd jsonlib to 2.13

---

crates/symbolicator-service/src/config.rs
crates/symbolicator/src/cli.rs

Fix: https://github.com/getsentry/team-ingest/issues/536#issue-2524571045
OPS PR: https://github.com/getsentry/ops/pull/12279#issue-2556618300

WIP: feat(metrics): Add region tag

---

crates/symbolicator-native/src/caches/symcaches.rs

We frequently log SymCache parsing failures, but the logs don't tell us which file we failed to parse. I'm adding some fields to the logs that will hopefully let us track down the files and inspect them.

feat: Add information to SymCache parsing failures

---

.github/workflows/build.yml

f/u fix to https://github.com/getsentry/symbolicator/pull/1521
changes were trivial enough i didn't do a test run but that would have been good... so here's one https://github.com/getsentry/symbolicator/actions/runs/11375365974/job/31645896976?pr=1538

fix(ci): update actions/upload-artifact to v4

---

Cargo.lock
Cargo.toml
crates/process-event/Cargo.toml
crates/symbolicator-proguard/Cargo.toml
crates/symbolicator-sources/Cargo.toml
crates/symbolicator/Cargo.toml
crates/symbolicli/Cargo.toml

Updates symbolic to 12.13.1 which contains an update Swift demangler.

ref(symbolic): Update symbolic to 12.13.1

---

Cargo.lock
Cargo.toml

This should fix the windows build issue.

ref(symbolic): Update symbolic to 12.13.2

---

.github/workflows/image.yml
Dockerfile

build: build symbolicator as multarch image

---

.github/workflows/image.yml

Forgot to push the intermediate images.

build: Also push intermediate builder images

---

crates/symbolicator-js/src/lookup.rs
crates/symbolicator-js/src/metrics.rs

A number of metrics (files found/not found, &c.) are now tagged with whether the file in question had a debug ID at all. Moreover, we also count
- how many projects had any files with debug IDs
- how many projects had any files with debug IDs *that couldn't be found*.

feat(js): Expand metrics about debug IDs

---

crates/symbolicator-service/src/metrics.rs

#1600 added aggregation for set metrics but neglected to actually emit them.

fix(metrics): Actually emit set metrics

---

Cargo.lock
Cargo.toml

ref: https://github.com/getsentry/sentry/issues/79268

chore(symbolic): Update symbolic to 12.13.4

---

crates/symbolicator-service/src/caches/versions.rs
crates/symbolicator-service/src/caching/cache_key.rs
crates/symbolicator-service/src/caching/tests.rs

ref: Add new cache path layout

---

CHANGELOG.md
crates/symbolicator-js/src/interface.rs
crates/symbolicator-js/src/symbolication.rs
crates/symbolicator-js/src/utils.rs
crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__e2e_react_native.snap
crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__e2e_source_no_header.snap
crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__no_source_contents.snap
crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__sourcemap_embedded_source_expansion.snap
crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__sourcemap_source_expansion.snap
crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__webpack.snap
crates/symbolicli/src/main.rs

This has been ported to Sentry in https://github.com/getsentry/sentry/pull/86995

feat(js): Remove `is_in_app`

---

Cargo.lock
Cargo.toml

We last updated our reqwest fork about a year ago.

deps: Update reqwest

---

CHANGELOG.md

docs(changelog): Add missing changelog entry for concurrent downloads

---

crates/symbolicator-service/src/download/mod.rs

Slightly better instrumentation to track down the few errors that do occur.

ref(download): Better instrumentation for range request errors

---

crates/symbolicator-service/src/download/index.rs

This removes the tracing error from `fetch_index`, which would be emitted every time even for cached results. It also adds an error for the last ID download (only if uncached) and moves the error for failing to download a segment into `download_index_segment`.

fix(index): Improve index download errors

---

crates/symbolicator-service/src/download/destination.rs

fixes https://github.com/getsentry/symbolicator/actions/runs/14476275271/job/40609145479

fix(windows): Fix compilation errors for windows

---

crates/symbolicator-service/src/download/mod.rs

To this end, we turn `status_to_error` into an async fn `response_to_error` that downloads the body and adds it as an extra.
This would also let us easily address the existing TODO about using the response body for the error details, but I'm leaving it as a future PR.

feat(download): Add response body as an extra for errors

---

CHANGELOG.md
Cargo.lock
crates/symbolicator-service/Cargo.toml

Add SOCKS proxy support via environment variables
```bash
export HTTP_PROXY=socks5://localhost:1080
export HTTPS_PROXY=socks5://localhost:1080
```

Add socks proxy support

---

crates/symbolicator-service/src/download/sentry.rs

Depends on: https://github.com/getsentry/sentry/pull/95651
Fixes: https://github.com/getsentry/symbolicator/issues/1731
Discussion ongoing about feasibility (and side effects) of the change in the Sentry PR.

fix(native): Lookup symbols bei either debug or code id from Sentry

---

crates/symbolicator-js/src/lookup.rs

In further pursuit of observability, this adds the `file_key` to the scope as an extra in `get_file`.
ref: INGEST-446.

feat(js): Add file key as extra

---

crates/process-event/src/main.rs
crates/symbolicator-js/src/bundle_lookup.rs
crates/symbolicator-js/src/lookup.rs
crates/symbolicator-js/src/sourcemap_cache.rs
crates/symbolicator-js/src/utils.rs
crates/symbolicator-native/src/symbolication/minidump_stacktraces.rs
crates/symbolicator-native/src/symbolication/module_lookup.rs
crates/symbolicator-native/src/symbolication/process_minidump.rs
crates/symbolicator-native/src/symbolication/symbolicate.rs
crates/symbolicator-proguard/src/service.rs
crates/symbolicator-proguard/src/symbolication.rs
crates/symbolicator-service/src/caching/cleanup.rs
crates/symbolicator-service/src/caching/memory.rs
crates/symbolicator-service/src/download/destination.rs
crates/symbolicator-service/src/download/mod.rs
crates/symbolicator-service/src/download/sentry.rs
crates/symbolicator-service/src/objects/candidates.rs
crates/symbolicator-service/src/objects/data_cache.rs
crates/symbolicator-service/src/objects/mod.rs
crates/symbolicator-sources/src/paths.rs
crates/symbolicator/src/service.rs

Reverts getsentry/symbolicator#1751
Revert of the Revert.

ref(beta): Fix beta clippy lints (#1750)

---

CHANGELOG.md

I hope this combines properly with the auto generated changelog, there is a previous section like this so I assume it is going to work.

docs(changelog): Add stderr breaking change
