- src/actors/objects/mod.rs
- src/actors/symcaches.rs
This updates metrics around cache files:
- `fetch_object.*` and `fetch_symcache.*` renamed to `objects.*` and `symcaches.*`, respectively
- Adds `objects.size` and `symcaches.size`
- Ensures that written files are flushed (including metadata), before moving on
> feat: Add metrics for cache file sizes

- src/actors/objects/mod.rs
- src/actors/symbolication.rs
- src/actors/symcaches.rs
We want to capture the real `Fail` without any wrapper `Fail`s attached, because:
* due to how error chains are currently grouped in Sentry (least specific error is the one shown in title)
* in async envs, breadcrumbs are probably better when capturing close to the error
> fix: Call capture_fail in every step of the pipeline

- Cargo.lock
- Cargo.toml
- src/actors/cficaches.rs
- src/actors/objects/mod.rs
- src/actors/symbolication.rs
- src/actors/symcaches.rs
- src/app.rs
- src/config.rs
- src/endpoints/minidump.rs
- src/endpoints/mod.rs
- src/endpoints/proxy.rs
- src/endpoints/symbolicate.rs
- src/types.rs
This lets one configure a list of sources in the config file which is used
as a default for the symbolicate request.  It also adds a new proxy mode which
is on by default which will serve up symbols downloaded from one of the source
servers.  It will always decompress the symbols which lets one use this with
visual studio and other debuggers as a source even if the source server format
is not necessarily the correct format.
> feat(proxy): Added basic symstore proxy mode

- src/endpoints/proxy.rs
- src/types.rs
This uses the global scope for the proxy and removes the proxy scope.
> feat: Use global scope for proxy

- src/actors/cache.rs
- src/actors/cficaches.rs
- src/actors/objects/mod.rs
- src/actors/symcaches.rs
- src/app.rs
- src/cache.rs
- src/config.rs
- src/lib.rs
* CacheActor will look at a file, and if it's considered expired, will just overwrite it.
* `symbolicator cleanup` will go through all caches synchronously and delete files it considers expired.
> feat: Add concept of cache expiry and a subcommand to delete expired files

- README.md
- src/actors/objects/paths.rs
- src/types.rs
This improves SSQP/SymStore compatibility by implementing the
different casing rules for signatures and pdb filenames for
SymStore and SSQP.  There are many existing SymStores like Unity
and Google that are stored on case sensitive file systems and as
such need the exact casing rules that the Microsoft client sends.
These are not the rules that SSQP defines.  As such this now
adds a second layout to control them.
Fixes #36
Fixes #35
> feat(casing): Added SSQP directory layout support

- Cargo.lock
- Cargo.toml
- build.rs
The old crate for the git version forces a rebuild constantly.  This implementation
now only watches the git index.
> fix: Avoid pointless rebuilds

- src/actors/objects/common.rs
- src/actors/objects/http.rs
- src/actors/objects/mod.rs
- src/actors/objects/s3.rs
- src/endpoints/proxy.rs
- src/lib.rs
- src/utils/mod.rs
- src/utils/paths.rs
This makes it easier to reuse this code outside of the object lookup.
> ref: Move part of path code into utils

- Cargo.lock
- Cargo.toml
- src/utils/paths.rs
- tests/integration/test_s3.py
This fixes an issue where PE code identifiers where not parsed correctly when the had an uneven number of characters. This can happen, however, due to the way they are formatted. 
The actual fix is contained in symbolic.
> fix: Compute proper code identifiers for lookups

- src/actors/objects/mod.rs
- src/utils/mod.rs
- src/utils/objects.rs
Mismatching code identifiers is not an error, it should be reported as object status. However, there's currently no clean way to accomplish this. We can revisit this when we refactor object identifiers and messages.
For the time being, the old logic is moved to an unused utility method so we can use it again later.
> ref: Do not validate object identifiers

- Cargo.lock
- Cargo.toml
- src/types.rs
This really shouldn't happen, but there's also no reason not to handle empty strings gracefully.
> ref: Skip empty identifiers gracefully

- Cargo.lock
- Cargo.toml
- src/actors/objects/mod.rs
- src/utils/objects.rs
Sources may contain multi-arch object files (such as Fat MachO), for which we currently throw an object parse error. This PR adds support for those archives by unpacking just the one object that we might be interested in. 
Note that we intentionally do not validate identifiers for the non-fat case.
> fix(objects): Support multi-arch archives

- src/actors/objects/http.rs
- src/actors/objects/mod.rs
- src/actors/objects/s3.rs
- src/actors/objects/sentry.rs
- src/http.rs
I don't quite understand the problem but it seems Sentry is just slow to respond here. Maybe we want this for external buckets someday too, but I think we generally give the customer less connectivity guarantees to external services. For now just make sure we can roll Symbolicator out without regressing.
> fix: Bump download timeouts

- Dockerfile
Enables release builds with debug information. Locally, release builds still do not contain debugging information for faster builds and smaller target directory sizes.
> build(docker): Build with debug information

- src/endpoints/minidump.rs
- src/endpoints/proxy.rs
- src/endpoints/symbolicate.rs
This should resolve some instances of scope data being all over the place.
I wonder if we could make sentry_actix use the right hub at the point the handler creates the futures, but probably not.
> fix: Actually use sentry_actix's hub

- README.md
People who try to get Sentry's native processing pipeline running will inevitably go to this repo.
> doc: Document for Sentry users how to set up Symbolicator

- src/actors/objects/http.rs
- src/http.rs
- tests/integration/conftest.py
- tests/integration/test_basic.py
Two commits here:
* First one un-breaks redirects in general: We used the old URL instead of the one in headers
* Now redirects worked, but MSDL returned 400 Bad Request on the second request. It seems that `ClientRequest::set_url` does not set the correct host header. Refactor to set correct URL in request ctor.
> fix: Un-break redirects

- src/actors/symbolication.rs
Logs errors to Sentry if we don't know an architecture as opposed to silently swallowing it. In theory, this should never happen, but evidently it does:
https://sentry.io/organizations/sentry/issues/1029737004
> ref(minidump): Log errors for unknown architectures

- Cargo.lock
- Cargo.toml
- src/actors/symbolication.rs
Fixes two issues in minidump processing:
- Includes getsentry/symbolic#146 to process minidumps without thread lists
- Backfills the system info architecture from modules if it cannot be extracted from the minidump
> fix(minidump): Be more lenient in minidump processing

- src/actors/symbolication.rs
- src/types.rs
Work around clients that send images without end addr or images that are zero sized.
> fix: Use debug images with no end addr

- .gitignore
- src/actors/cficaches.rs
- src/actors/objects/common.rs
- src/actors/objects/filesystem.rs
- src/actors/objects/gcs.rs
- src/actors/objects/http.rs
- src/actors/objects/mod.rs
- src/actors/objects/s3.rs
- src/actors/objects/sentry.rs
- src/actors/snapshots/symbolication__actors::symbolication::test_add_bucket-2.snap
- src/actors/snapshots/symbolication__actors::symbolication::test_remove_bucket-2.snap
- src/actors/symcaches.rs
- src/app.rs
- src/endpoints/proxy.rs
- tests/integration/test_basic.py
(symcache is used as synonym for symcache/cficache)
**We recently discovered that global symcaches could be used on symbolicator even though the corresponding source was not enabled.** This is another manifestation of #19, where we previously were fine with implementing a few workarounds such as shorter cache retention.
1. Refactor symcache lookup to simulate an object lookup every time. This means that symcaches use the same exact cache key as their backing object.
2. Introduce another caching layer to avoid downloading and parsing objects every time we look up a symcache. The new cache is stored in `{cache_dir}/object_meta/` and contains all parameters necessary for deciding which object should be used: `has_debug_info`, `has_unwind_info` and `has_symbols`.
3. Introduce an in-memory …
> ref: Perform object lookup for every symcache lookup

- src/actors/cficaches.rs
- src/actors/common/cache.rs
- src/actors/objects/mod.rs
- src/actors/symcaches.rs
With #80 we know ahead of time in which scope a potential cache hit will
be, since every cache lookup is now tied to a source (and therefore we
can look at is_public earlier). This allows us to simplify Cacher such
that it no longer needs to look at two filepaths.
Channel deduplication never worked properly for deduplicating lookup of
globally stored cache items (cache lookups were effectively only
deduplicated per-project/per-local-scope). This commit fixes that
indirectly.
> fix: Deduplicate channels for global objects

- .gitignore
- Makefile
- docs/background-and-principles.md
- docs/caching.md
- docs/index.md
- docs/symbol-lookup.md
- docs/symbol-server-compatibility.md
- docs/symbolication-api.md
- docs/system-architecture.md
- mkdocs.yml
Use mkdocs because it's quite close to raw markdown files. Intending to host this on either readthedocs or github pages.
This is most of the stuff copied from Notion, quickly skimmed over for correctness (but not for good structure or clarity)
> doc: Add design docs

- src/actors/symbolication.rs
- src/types.rs
We are seeing CPU load patterns that we cannot correlate to much of the other metrics that we currently have. Maybe CPU goes up because the requests have more frames/images on average?
> feat: Add metrics for debug_status, unwind_status, modules count, frames count

- src/actors/snapshots/tests__actors::symbolication::tests::test_minidump_linux-2.snap
- src/actors/snapshots/tests__actors::symbolication::tests::test_minidump_macos-2.snap
- src/actors/snapshots/tests__actors::symbolication::tests::test_minidump_windows-2.snap
- src/actors/symbolication.rs
- src/utils/paths.rs
A proper path looks like this: Qt5Core.pdb/6CA082053866490D87E82C42650B67F71/Qt5Core.sym
Before this change a path like this was generated:  Qt5Core.sym/6CA082053866490D87E82C42650B67F71/Qt5Core.pdb
> Fix breakpad symbol path

- src/actors/snapshots/tests__actors::symbolication::tests::test_add_bucket-2.snap
- src/actors/snapshots/tests__actors::symbolication::tests::test_minidump_windows.snap
- src/actors/snapshots/tests__actors::symbolication::tests::test_remove_bucket.snap
- src/actors/symbolication.rs
- src/types.rs
This allows to ingest partially symbolicated stacktraces. The main reason for this are apple crash reports, which already contain function and file names. However, this now also works for JSON payloads (for consistency).
As part of this PR, I restructured the minidump symbolication path. It is still functionally equivalent to what was there before, but split into smaller functions with a clear defined interface. We can take further refactoring from there.
> ref: Allow to ingest partially symbolicated requests

- src/actors/symbolication.rs
We do not have concerns about Symbolicator performance, but Sentry has
issues handling infinitely large responses.
> fix: Set a hard limit on amount of stacktrace frames

- README.md
- src/http.rs
Let's revisit IPv6 security when people actually need IPv6. Right now it's unclear which IP ranges are local and which are not.
> fix: Ban IPv6 network calls

- src/service/objects/gcs.rs
- src/service/objects/http.rs
- src/service/objects/sentry.rs
Fixes a (potential) regression in #106.
The new actix web client no longer wraps the payload stream in the timeout, but the timeout still runs while the request might be pending in the outgoing connector queue. The default timeout is 5s, which would mean that all systems would have to respond within 5s minus the time that it takes for a queued request to be sent. 
We can consider adding a slightly higher timeout of 10s, but I'm currently torn between our options.
> fix(timeout): Disable timeouts for all web requests

- docs/index.md
- src/config.rs
On our Docker images, we already define `/data` as a persistent volume, even more, it is quite tricky to mount a new cache directory as a volume with the right symbolicator user so make that the default on Docker. This also allows us to run symbolicator with the default config in getsentry/onpremise#220.
> feat(config): Default cache_dir to /data on Docker

- Cargo.lock
- Cargo.toml
- build.rs
- src/cli.rs
- src/logging.rs
- src/server.rs
- src/service/cache.rs
- src/service/cficaches.rs
- src/service/objects/filesystem.rs
- src/service/objects/gcs.rs
- src/service/objects/http.rs
- src/service/objects/mod.rs
- src/service/objects/s3.rs
- src/service/symbolication.rs
- src/service/symcaches.rs
- src/utils/multipart.rs
Fixes a bunch of issues:
- **Fix panics in HTTP2 connections**
- Replaces the `sentry` log integration logger with a custom one to capture breadcrumbs only for logs that pass `RUST_LOG`.
- Fixes race conditions in deduplication channels in the symbolication service and cacher.
- Fixes hub propagation for symbolication requests
- Logs errors in the symbolication error with stack traces.
> fix: Avoid panics and improve error handling

- src/server.rs
Add a metric to better track symbolicator restarts.
> fix: Report server start-up

- Cargo.lock
- Cargo.toml
- src/service/snapshots/tests__apple_crash_report.snap
- src/service/symbolication.rs
- src/types.rs
- tests/integration/test_applecrashreport.py
Many AppleCrashReports do not have application specific information, but they specify an exception type and subdata. We can leverage this to populate the crash reason and details.
> feat: Extract proper reason from Apple Crash Reports

- build.rs
- src/app.rs
Release information is currently not available in Sentry. This ensures that the release field is properly set to the commit hash.
> fix(sentry): Set the correct sentry release

- src/logging.rs
The default Sentry breadcrumb logger does not consider the effective log filter that is configured using `RUST_LOG`. As a result, it is not possible to log breadcrumbs with different levels for specific crates.
In Symbolicator, we need debug level breadcrumbs, but only for Symbolicator's own logs. All other crates should be logged with the respective default filter (which is `WARN` in most cases).
> fix(sentry): Apply effective log filter to breadcrumbs

- tests/integration/conftest.py
Backport of bugfixes in the `hitcounter` fixture implementation:
- 46cb54c1d9ff0a65ed15968c4f432502b0e18c39 
- 803c3bd5826cc6e78ddb3da4c2315d43664f9607
> test(integration): Fix hitcounter implementation

- .travis.yml
Caches were not working for symbolicator on Travis. 
I believe `cache: cargo` only works if the language is set to `rust`. In our case, we use `python` so that we can run integration tests. Build times are around 11 minutes for tests at the moment, and I believe we can bring them down to roughly 4 minutes with caches.
Example: https://travis-ci.com/getsentry/symbolicator/jobs/242364591
> ci(travis): Fix Rust caches

- .travis.yml
- Dockerfile
There is a suspected regression in OpenSSL `1.1.1c` used on Debian buster-slim that might cause a memory leak. We suspect that this might have to do with HTTP2 connections, but it has not been confirmed yet.
cc @BYK
> build(docker): Revert to debian stretch-slim

- .travis.yml
Sad but true; Caching is slower than downloading and recompiling.
> ci(travis): Remove caches to improve build times

- Cargo.lock
- Cargo.toml
- Dockerfile
- scripts/create-sentry-release
This moves to server-side symbolication for errors and crashes happening in symbolicator. This will allow us to use **source context** and improve runtime-performance of errors, as symbolicator does not have to load its own debug information when stack unwinding.
> ref: Strip debug information for server-side symbolication

- docker-entrypoint.sh
To enable this functionality, the container has to be run in the privileged mode, and `SYMBOLICATOR_DEBUG` environment variable must be set to "1".
> feat: Add an option to collect core dumps

- docs/advanced/symbol-server-compatibility.md
- src/types.rs
- src/utils/paths.rs
This adds support for the debuginfod and deived debug information file path structure.
What's nice about debuginfod is that they also have a format for how to find sources.
This let us use a dialect of the debuginfod format (dubbed unified) as a recommended
standard for linux/mac where users currently do not have a good default naming scheme.
Refs #141
> feat: Added debuginfod and unified support

- .travis.yml
The old test job first builds the test target and then rebuilds the binary target to run integration tests. Since this is running serially, it might take longer than needed. By running two jobs, we might speed up builds slightly.
> ci: Split tests into separate jobs

- src/actors/objects/mod.rs
- tests/integration/test_basic.py
Also add a few log stmts to be able to debug this.
> fix: Do not let IO errors of sentry index request bubble up

- Cargo.toml
- src/actors/cficaches.rs
- src/actors/common/cache.rs
- src/actors/objects/filesystem.rs
- src/actors/objects/gcs.rs
- src/actors/objects/http.rs
- src/actors/objects/mod.rs
- src/actors/objects/s3.rs
- src/actors/objects/sentry.rs
- src/actors/symbolication.rs
- src/actors/symcaches.rs
- src/endpoints/applecrashreport.rs
- src/endpoints/minidump.rs
- src/endpoints/proxy.rs
- src/endpoints/requests.rs
- src/endpoints/symbolicate.rs
- src/macros.rs
- src/metrics.rs
- src/test.rs
- src/utils/futures.rs
- src/utils/http.rs
- src/utils/multipart.rs
- src/utils/sentry.rs
This is required so that we can enable the `async-await` feature on `futures` and then use macros like `select!`.
> build: Rename futures dependency

- symsorter/Cargo.lock
- symsorter/Cargo.toml
- symsorter/src/app.rs
- symsorter/src/config.rs
- symsorter/src/main.rs
- symsorter/src/utils.rs
This adds a flag called `--multiple-bundles` so that one can point symsorter directly at a device support folder and it derives the bundle id from the first level of recursion.
> feat(symsorter): Add multi bundle support for easier sorting

- src/actors/snapshots/tests__minidump_macos.snap
- src/actors/symbolication.rs
Fixes lookups for images referenced from macOS Minidumps from `unified` sources.
For MachO images, the Breakpad processor does not emit a code identifier. However, `symbolic` defines the code identifier as the contents of `LC_UUID`, which is equivalent to the debug identifier. This is required by the `unified` source, since it always keys files by the code identifier.
The byproduct of this is that we now backfill code identifiers into debug images of macOS minidumps. This doesn't yield more information, but it creates parity with the other platforms. Note that we do not yet cross-convert debug ids and code ids for MachO files.
> fix: Unified source lookups for Darwin Minidumps

- .travis.yml
- Cargo.lock
- Cargo.toml
- symsorter/Cargo.lock
This fixes the following issues:
- https://github.com/gimli-rs/cpp_demangle/pull/194
- https://github.com/getsentry/symbolic/pull/201
- https://github.com/getsentry/symbolic/pull/202
- https://github.com/getsentry/symbolic/pull/207
- https://github.com/getsentry/symbolic/pull/208
- https://github.com/getsentry/symbolic/pull/214
- https://github.com/getsentry/symbolic/pull/216
Symbolic cannot be released just yet due to a git dependency, but these fixes are urgent to deploy.
Ref https://github.com/getsentry/symbolic/pull/215
> build: Temporarily use symbolic branch

- Cargo.lock
- Cargo.toml
- src/endpoints/healthcheck.rs
- src/server.rs
- src/utils/futures.rs
The most important here is the CPU-intensive threadpool which is no
longer the same size all the CPUs available.  The IO-bound threadpools
are still overcommited in that there are two threads per CPU core.
The num_cpus crate was already an indirect dependency, now it is a
direct dependency under the same version number as before.
Lastly add a cude measure of the healthchecks in the form of a metrics
counter.  This is not ideal as it's the server's side point of view
but will give some indication.  I'm be tempted to add the timestamp as
a field but not sure this makes much sense in Datadog's model.
> Reduce the threadpool sizes

- src/actors/symbolication.rs
- src/app.rs
- src/server.rs
This newtypes the error in the ServiceState but doesn't bother in the
SymbolicationActor itself.  It's a bit more graceful compared to the
plain .expect() which is probably nice.
> Propagate the spawn error from the process pool up at startup

- .travis.yml
- Cargo.lock
- Cargo.toml
- src/actors/cficaches.rs
- src/actors/common/cache.rs
- src/actors/objects/mod.rs
- src/actors/symbolication.rs
- src/actors/symcaches.rs
- src/app.rs
- src/cli.rs
- src/endpoints/healthcheck.rs
- src/server.rs
- src/test.rs
- src/types.rs
- src/utils/futures.rs
This moves minidump processing and demangling into subprocesses.
I would run this as an experiment first and see how the performance impact is. This does not yet use any pools because the async support does not yet allow that. Also demangling is incredibly inefficient because we spawn for each function name. This should become a batch job but that requires bigger changes in how the code is structured.
> feat: Process minidumps in subprocesses

- Cargo.lock
Commit cf0d91fd80915c9bcf545d2235ca9b1b96cf7a8c bumped
apple-crash-report-parser but forgot to include the cargo.lock
changes.
> fix: Update cargo.lock for commit cf0d91f

- Makefile
The CI uses these targets to build and run the tests and using this
will ensure that CI doesn't pass a change which forgot to update
Cargo.lock.  This likely doesn't affect people's workflow much as the
build target doesn't use --locked.
> feat: Require no Cargo.lock changes when running tests

- src/actors/objects/http.rs
- src/utils/http.rs
Building the HTTP request could fail when the URI provided is invalid,
which apparently sometimes happens.  This caters for this and
propagates the correct error up.
> fix(download): Do not panic on malformed URIs

- src/actors/symbolication.rs
- src/endpoints/applecrashreport.rs
- src/endpoints/minidump.rs
- src/endpoints/requests.rs
- src/endpoints/symbolicate.rs
- src/utils/futures.rs
This simplifies symbolication task creation and also prevents races or task leaks:
- Most notably, this introduces `CallOnDrop`, a type that executes a callback when it is dropped. Instead of relying on the symbolication future to call its final `then` callback, we move `CallOnDrop` into the future, which eventually evicts the task from the global computation map. This is safer when the future is dropped without polling.
- When creating a new symbolication task, we assume that there are no UUID collisions.
- The signature of `create_symbolication_request` has been simplified since it is infallible.
- All use of `impl Future` has been removed in favor of boxed future types. This should help with compilation times, and also makes the code slightly more readable in some areas.
There are two …
> ref(symbolication): Avoid races and leaks in task handling

- src/actors/objects/http.rs
Some symbol server layouts, such as SSQP and Microsoft's SymStore, contain file names in the path. These paths do not necessarily have to be valid URL paths and may contain special characters. To join them, the path must be percent-encoded.
This switches from `Url::join`, which assumes a valid URL path, to `Url::path_segments_mut`, which percent-encodes the path properly.
> fix(download): Percent-encode HTTP paths with unicode names

- src/actors/symbolication.rs
- src/utils/http.rs
Instead of silently ignoring when a function cannot be demangled, log it to Sentry. This only reports an error if the language can be explicitly detected to avoid false-positives in case there are unmangled names marked as some other language.
> ref: Report failed function demangling to Sentry

- pytest.ini
This shows a summary of tests which are skipped, failed etc at the end
of the test output.
> test: Show pytest report summary by default

- src/actors/symbolication.rs
The future was being recorded as task_name=minidump_stackwalk even
though it has nothing to do with this.  This could account for thecase where the minidump_stackwalk duration graph looks a bit weird at times.
> fix(monitoring): Give this a unique task_name metric tag

- docs/index.md
- src/actors/symbolication.rs
- src/app.rs
- src/cache.rs
- src/config.rs
This adds a feature which saves minidumps when the process processing
them crashes.  It also improves the metrics reporting these failures
to contain more information about the failure.
The crashed minidumps are stored in the cache directory and have a
default cache timeout of 24h.
Todo:
The way this is jammed into the symbolication "actor" is not ideal,
and as can be seen from `join_procspawn()` this is by far a nice API.
It could be worth splitting this off into a minidump service which
might be able to encapsulate this a bit better.
The other thing which isn't overly nice is how this pretends to be an
entirely normal cache directory, but it only uses one of the fields.
I could be better to create a new config struct for the minidumps
cache instead.  And perhaps it should not be an item …
> feat(minidump): Save minidumps which crash during processing

- src/actors/symbolication.rs
- src/app.rs
- src/cache.rs
The diagnostics cache directory was not created.  It seems all the
cache directories are created on the fly at runtime.  This changes
this to create all the cache directories at startup, ensuring the
application fails to start when it can not create one of the caches.
> fix: Create cache directories at startup

- src/actors/symbolication.rs
- src/services/download/http.rs
- src/services/download/mod.rs
- src/test.rs
- src/utils/futures.rs
- src/utils/http.rs
The `future_metrics!` macro is `futures v0.1` only and hinders adoption of `futures v0.3`. What it does should be part of the services interface so integrate it into the `RemoteThread::spawn` call.
> ref: Remote thread timeout

- src/macros.rs
- src/services/download/http.rs
- src/services/download/mod.rs
- src/utils/futures.rs
- src/utils/http.rs
This converts the HTTP downloader to futures03 using async fn code.
No functional change.
> Convert inner implementation of HTTP downloader to async fn code

- Cargo.toml
- src/services/download/mod.rs
- src/services/download/s3.rs
This is just a first step, as a newer rusoto has native support
for async/await, which we do not yet use.
A next step in this refactoring would probably be to directly stream
from an `AsyncRead` into an `AsyncWrite`, without manually dealing
with streams.
> ref: Update S3 downloader to async/await

- src/services/download/http.rs
- src/services/download/mod.rs
- src/services/download/sentry.rs
- src/utils/futures.rs
Upgrades the sentry downloader to use async fn internally.
This also adds a generic timed_task utilitiy to the futures module and
an extenstion trait to use it more ergonomically.
> Convert the sentry downloader to async fn

- src/actors/symbolication.rs
Some minidumps are missing debug IDs and skipping them results in not
even all modules showing up which results in even more confusing crash
reporting.
> fix: Do not skip modules without debug id

- Cargo.lock
- Cargo.toml
- src/cli.rs
Panic capturing is enabled by default now
> build: Update sentry dependency

- Cargo.lock
- Cargo.toml
- src/actors/symbolication.rs
This is a companion to:
* https://github.com/getsentry/symbolic/pull/255
* https://github.com/gimli-rs/cpp_demangle/pull/207
We can temporarily point this to a git dependency in order to figure out what an effect this has on our demangling failure rate.
> fix: Use symbolic with increased demangler recursion limit

- src/actors/symbolication.rs
- src/utils/hex.rs
Follow-up to #247. Minidumps can specify shared memory regions in the module list. These are undesired for symbolication purposes. The only exception is when a stack frame references an address from such a module.
This PR introduces `CodeModulesBuilder` which allows to track valid modules and references into them. In the end, only modules with valid identifiers or with references are kept.
> fix: Exclude irrelevant modules from minidumps

- src/services/download/s3.rs
This shows the S3 object in the same format as aws cli uses.
> Improve S3 logging output

- Makefile
- pytest.ini
- tests/integration/conftest.py
- tests/integration/test_basic.py
The hitcounter is refactored to be more modular.  It is now more
encapsulated in an object rather than have a free closure variable
bound to itself.  This work also adds some more docstrings so that
pytest --fixtures shows more useful output.
The hitcounter now also avoids raising failures in the teardown,
instead using a mechanism to raise them during the call step of the
testrun protocol.
test_timeouts gets an explicit sleep step.  Its 10 iterations need to
take longer than its 1s timeout.  This should reduce flakyness and
hopefully remove the need for pytest-rerunfailures.
test_reserved_ip_addresses gets a more readable variable name and also
an additional assert to ensure the local proxy is (not) hit.
The Service fixute helper just does linear backoff instead of
exponential.  There is …
> Refactor hitcounter fixture, disable pytest-rerunfailure

- Cargo.lock
Depend on a new symbolic version which works with rustc 1.46.
> build: New symbolic dependency

- src/actors/symbolication.rs
- src/cache.rs
- src/utils/futures.rs
Especially the cache cleanup tasks emit very verbose log output. INFO logs are
supposed to give consumers a high level insight into current operations, and as
such some of the current messages should be made DEBUG, instead.
> fix: Lower log levels to reduce verbose output

- src/cache.rs
Removes the file path from the message to allow Sentry to group all errors
together. Additionally, the error was reported twice.
> fix(sentry): Change cleanup error message for grouping

- .github/workflows/danger.yml
- dangerfile.js
Creates the following comment when the changelog is missing:
---
> meta(gha): Add a danger lint for changelog entries

- .craft.yml
- CHANGELOG.md
`symbolicator:0.2.0` was missing from Docker Hub as it was not defined in Craft as a publish target. This PR adds it. Whoever releases Symbolicator will now need write access to https://hub.docker.com/r/getsentry/symbolicator
> ci(craft): Add docker target to craft

- Cargo.lock
- Cargo.toml
- src/actors/objects/mod.rs
- src/app.rs
- src/cache.rs
- src/cli.rs
- src/config.rs
- src/server.rs
- src/services/download/filesystem.rs
- src/services/download/gcs.rs
- src/services/download/http.rs
- src/services/download/mod.rs
- src/services/download/s3.rs
- src/services/download/sentry.rs
I think @jan-auer had a few ideas about making these errors better, especially around authentication errors on upstream services (gcs, s3), so this might be a good idea to figure out what we want to do here.
> ref: Replace failure with thiserror in the download service

- CHANGELOG.md
- docs/index.md
- src/app.rs
- src/config.rs
This can be useful when Symbolicator is not the only service running on the machine (e.g. in Kubernetes environment).
> feat: Add an option to configure subprocess pool size

- src/actors/objects/mod.rs
Doesn't change anything but simplify the caller.  As there's only one
might as well depend on the NamedTempFile struct.
----
> ref(objects): Simplify decompression calls

- .github/workflows/ci.yml
- src/actors/objects/mod.rs
- src/services/mod.rs
This adds a check to ensure the rust doc comments are correct and can
be used to internally document the application.
> ci: Check rust doc comments on CI

- conftest.py
- tests/integration/conftest.py
Because this does things globally to the pytest process it needs to be
loaded before any test collection.  Thus it should be in the topmost
conftest.py, in this case the toplevel of the repo.
This currently works on CI because it invokes pytest with the path to
the integration tests, triggering the peculiarities of pytest plugin
loading which will now load a conftest in this directory before
collecting tests.  However when you interactively run pytest you might
not want to bother passing this argument all the time, let alone
realise this is the problem why pytest mysteriously fails.
----
> test: Move conftest.py to repo toplevel

- Cargo.lock
- Cargo.toml
- src/actors/symbolication.rs
- src/services/download/mod.rs
- src/types.rs
This avoids duck-typing an integer as a timestamp.
Additionally this upgrades chrono and sorts dependencies in cargo.toml
alphabetically.
----
> ref: Use a more strongly-typed timestamp

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/endpoints/applecrashreport.rs
- src/endpoints/minidump.rs
- src/endpoints/proxy.rs
- src/endpoints/symbolicate.rs
- src/logging.rs
- src/server.rs
- src/utils/sentry.rs
This is vendoring in the old sentry-actix integration, as the new SDK only supports actix-web 3
> ref: Upgrade to upcoming sentry SDK version

- .github/workflows/ci.yml
- Makefile
- conftest.py
- tests/integration/conftest.py
When an external person makes a PR they do not get access to the
credentials in the environment variables and the tests will fail.  So
we now check we're actually running as getsentry to still allow
skipping for external contributors.
This also removes the --ci flag, as we are now depending on Github
Actions environment variables we might as well depend on them to
detect running in CI in general.
> test: Be more liberal when skipping credentials

- src/actors/symbolication.rs
This moves the creation of MinidumpState into a std::convert::From
impl which simplifies the stackwalking code itself by moving boring
stuff out of the way.
It also removes get_object_type_from_minidump() completely forcing the
get_referenced_modules() code to build a full MinidumpState to get
this information.  That's a few wasteful allocations but avoids more
special purpose code matching strings.
----
> ref(stackwalk): simplify MinidumpState creation

- src/actors/symbolication.rs
std::convert::From is meant to consume values to turn them into
something else.  This is more a constructor.
----
> ref: Use better idioms

- CHANGELOG.md
- src/actors/cficaches.rs
- src/actors/common/cache.rs
- src/actors/objects/mod.rs
- src/actors/symbolication.rs
- src/cache.rs
- src/services/download/mod.rs
When the objects actor downloads files it ranks them and chooses the
highest ranking file.  However before returning we must make sure the
file can actually be used for the requested purpose.
In particular this avoids asking for CFI but only getting a (64-bit)
PDB but no PE file.  This file does not actually provide the requested
info, which then confuses the CfiActor because it tries to use it as a
CFI file, even though the file does not have CFI.
> fix(objects): Make sure returned files can be used for purpose

- CHANGELOG.md
- src/actors/snapshots/tests__minidump_windows.snap
- src/actors/symbolication.rs
We report unwind information as missing, even if it is not required for stack walking on platforms or builds where a frame pointer is available. Since this is not an error and the user should not be alerted to this, we should report as unused, instead.
> fix: Report unused missing unwind info as unused

- .craft.yml
- .github/workflows/build.yml
- Makefile
Uses Craft's GitHub artifact provider instead of Zeus.
> ci(gha): Publish artifacts to GHA

- .github/workflows/danger.yml
- dangerfile.js
- src/actors/snapshots/tests__add_bucket.snap
Makes several improvements to Danger checks:
- Skips danger checks on draft PRs entirely.
- Shows a suggestion for the changelog entry for simple copy-paste.
- Warns when snapshots change that Sentry tests probably need updating.
> ci(danger): Improve danger warnings

- tests/integration/conftest.py
The intention is that we allow to skip these tests when they are being
executed from a fork in CI but they still fail when on the credentials
are missing on the main repo.
> test: Try skipping on missing credentials for forks again

- src/actors/symbolication.rs
Nightly CI clippy complains about this, seems fair enough.
> ref: Initialise struct at once

- Cargo.toml
Speeds up compilation of debug builds by removing debug information, which we usually don't require during development and testing. In cases where stack traces and debug information are required, they can be enabled by setting `debug = true` locally.
> build: Skip debug information in dev builds

- src/actors/cficaches.rs
- src/actors/common/cache.rs
- src/actors/objects/mod.rs
- src/actors/symbolication.rs
- src/cache.rs
- src/config.rs
- src/logging.rs
- src/macros.rs
- src/metrics.rs
- src/services/download/filesystem.rs
- src/services/download/gcs.rs
- src/services/download/http.rs
- src/services/download/mod.rs
- src/services/download/s3.rs
- src/services/download/sentry.rs
- src/services/mod.rs
- src/sources.rs
- src/test.rs
- src/types.rs
- src/utils/futures.rs
- src/utils/http.rs
- src/utils/sentry.rs
Since intra-doc-links are stable now, this adopts them across the code base. There are still comments where code structures are referred to without links, which will be updated in the future.
> doc: Use intra doc links consistently

- CHANGELOG.md
- tests/integration/test_wasm.py
- wasm-split/Cargo.lock
- wasm-split/src/main.rs
See comment in source for justification but in general we need to understand the original file layout to calculate the offset to the code section. This means we can't remove that information but need to retain it.
I filed an issue in the webassembly toolchain repo for discussions: https://github.com/WebAssembly/tool-conventions/issues/155
> feat(wasm-split): Retain all sections in debug companion

- src/actors/symbolication.rs
The error kind has only been used in tests and did not convey any semantic meaning. By switching to `anyhow::Result` for tests, we can avoid it alltogether.
> ref(symbolication): Remove stale error kind

- CHANGELOG.md
- src/types.rs
If an object passed through procspawn can not correctly deserialise it
will just hang forever, probably triggering the overal symbolication
task timeout.
> fix(procspawn): Ensure deserialisation

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- Makefile
- src/main.rs
- symsorter/Cargo.lock
- symsorter/src/main.rs
- symsorter/src/utils.rs
- wasm-split/src/main.rs
This makes sure everyone invokes clippy locally the same way as on CI
and doesn't get any surprises.
> ci(clippy): Enable clippy::all all in source code

- CHANGELOG.md
- src/endpoints/applecrashreport.rs
- src/endpoints/minidump.rs
- tests/integration/test_applecrashreport.py
- tests/integration/test_basic.py
- tests/integration/test_minidump.py
For forward compatibility, Symbolicator must always ignore unknown
fields in requests. This is the default for JSON payloads, but
multipart/form-data parsing used to emit an error for unknown field.
This PR adopts the leniency policy for multipart/form-data requests and
ignores all unknown fields.
> fix(endpoints): Always ignore unknown multipart fields

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/actors/symbolication.rs
- src/endpoints/applecrashreport.rs
- src/endpoints/minidump.rs
- src/endpoints/symbolicate.rs
This will create a new sentry session for each symbolication task, and flag that as `abnormal` in case it hits a timeout. Otherwise sessions will be closed when the hub/future they were created on is dropped.
> feat: Track Sessions for each request

- src/actors/cficaches.rs
- src/actors/common/cache.rs
- src/actors/objects/data_cache.rs
- src/actors/objects/meta_cache.rs
- src/actors/objects/mod.rs
- src/actors/symbolication.rs
- src/actors/symcaches.rs
- src/macros.rs
- src/metrics.rs
- src/utils/futures.rs
This refactors the cache actor to futures 0.3, as this involves a
trait this requires touching everything using this trait.  No attempt
at changing the code-style itself or moving to async/await has been
made, now that everything is on futures 0.3 this can be done in
smaller parts where more careful thought can be put into this.
Instead changes have been tried to keep to just the minimum required
for the futures conversion, only laying the groundwork for more
improvements later.
The trait itself has been changed to return Pin<Box<dyn Future ...>>,
since you can not do async/await in traits this matches the signature
that the async-trait crate generates.  This allows seamless
integration in future async/await code, without the Pin currently a
few Unpin requirements would already break. …
> ref(cache): Convert to futures 0.3

- src/actors/objects/data_cache.rs
- src/app.rs
- src/services/download/gcs.rs
- src/services/download/mod.rs
This is a work-in-progress proof of concept for creating stateful downloaders rather than storing caches in global static data structures. This will allow to unit-test the downloaders more easily.
As part of this, I noticed that we largely do not to return `impl Future` and can use `async fn` directly. This is possible even in the case of the `download` function, although it is made harder by the thread pool. Since the pool requires `'static` futures, we cannot spawn any async function that takes `&self`. This requires one of the following workarounds:
1. Get rid of the thread pool and move resource delegation up the call hierarchy. Probably the most desirable solution, but also exceeds the scope of this PR.
2. Use [`async-scoped`](https://docs.rs/async-scoped) to spawn a future with a …
> ref(downloader): Make the GCS downloader a stateful struct

- src/services/download/mod.rs
- src/services/download/s3.rs
Continuation of https://github.com/getsentry/symbolicator/pull/329 and additionally introduces metrics to measure the cache hit rate for S3 clients.
> ref(downloader): Make the S3 downloader a stateful struct

- src/cache.rs
FS operations on my machine have taken a little longer today, which resulted in sporadic test failures. By increasing the timeout, we can at least reduce the chance for this happening.
The proper fix for this would be to control the clock.
> test: Increase timeouts for slow FS operations

- src/utils/futures.rs
> ref(clippy): No trailing semicolon on enum in function

- src/services/download/filesystem.rs
- src/services/download/http.rs
- src/services/download/mod.rs
Continues work from #330 for the HTTP download source. This is in preparation of moving to reqwest.
> ref(downloader): Make HTTP and FS downloaders stateful structs

- src/actors/objects/mod.rs
- src/services/download/mod.rs
- src/services/download/sentry.rs
Continuation of #330 and #337. This time, the signature of `list_files` had to be changed to allow delegating the Sentry index operation to a thread pool.
> ref(downloader): Make the sentry downloader a stateful struct

- Cargo.toml
- src/actors/symbolication.rs
- src/endpoints/proxy.rs
- src/metrics.rs
- src/services/download/s3.rs
- src/utils/futures.rs
- src/utils/http.rs
Since tokio 1.0 is out, we will slowly start to migrate over. See #335 for part
of this effort. In order to do this, we need to load both tokio versions
side-by-side, which requires aliasing the old version to `tokio01`.
> build: Alias tokio as tokio01

- symsorter/Cargo.lock
- symsorter/Cargo.toml
- symsorter/src/app.rs
Uses `rayon` to move file handling and source bundle creation into a thread
pool. The main thread walks the given paths and continuously produces paths into
the thread pool. In the worker threads, the file is opened, inspected, and
potentially processed. The maximum number of concurrent files at any given time
therefore is `ncpu`.
Note that this is optimized for sorting directories with a high density object
files.
> ref(symsorter): Implement multi-threading

- src/actors/symbolication.rs
- src/services/download/sentry.rs
- src/utils/futures.rs
Introduces two new future utilities:
- `measure` function allows to time futures and their results. It is
supposed to eventually replace the other uses of the `future_metrics!`
macro, too.
- `timeout_compat` creates a timeout around a future that can run on a
`tokio 0.1` executor. This is to transition to the new `tokio 1.0`
timeout function.
Both utilities are introduced in preparation of #335.
> ref(utils): Introduce measure util for futures

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/app.rs
- src/services/download/gcs.rs
- src/services/download/http.rs
- src/services/download/mod.rs
- src/services/download/s3.rs
- src/services/download/sentry.rs
- src/test.rs
- src/utils/futures.rs
- src/utils/http.rs
Introduces Tokio 1 in the downloader module, migrates to reqwest, and updates to the latest version of rusoto for S3. Downloaders share the same HTTP client and run in a single-threaded runtime. At this point, the new runtime is only used by the downloaders.
Since reqwest does not allow to hook into the resolver, this uses a patched version: jan-auer/reqwest@62edd49 until reqwest adds the required APIs.
> ref(downloader): Upgrade downloaders to tokio 1.0

- .github/workflows/periodic.yml
The workflow rename is so that it makes a bit more sense.  The job
renames are another attempt at getting github to show the annotations
correctly.  If this still doesn't work perhaps just using the cargo
action is a better option.
> ci(periodic): Rename workflow and job names

- .github/workflows/periodic.yml
It's useful to be able to run the periodic workflow instead of having
to wait until the next time it triggers.  Apparently this needs to be
explicitly enabled.
> ci(periodic): Allow manually triggering the workflow

- .github/workflows/periodic.yml
Giving up on this.
Run clippy with the cargo action.  The annotations from the clippy
action end up in the wrong place and github can't figure this out.
Running the cargo action still annotates via stdout plus it doesn't
run the actualy command with json output so humans can read it anyway.
> ci(periodic): Use cargo action for clippy

- .github/workflows/ci.yml
- src/cache.rs
Switches to the standard cargo action for running clippy lints since it
emits sane CI output while still creating annotations in GitHub.
> ci: Run clippy via the cargo action

- src/services/download/filesystem.rs
- src/services/download/gcs.rs
- src/services/download/http.rs
- src/services/download/locations.rs
- src/services/download/s3.rs
In preparation of upgrading the `url` crate, this PR applies a few
syntactic changes to location utilities and downloaders. There is no
change in behavior.
- Move constants to the top of the code file
- Make location utilities methods on `SourceLocation`
- For brevity, use shorter `format!` statements
> ref(downloader): Cleanup location utilities

- Cargo.lock
- Cargo.toml
- src/services/download/filesystem.rs
- src/services/download/gcs.rs
- src/services/download/http.rs
- src/services/download/locations.rs
- src/services/download/s3.rs
- src/services/download/sentry.rs
- src/sources.rs
Updates the URL crate to 2.2.0. This allows us to pass the URL directly to the web client without going through a second parse stage.
With version 2, the `url::percent_encoding` module is no longer exposed. Instead, we have to use `Url::path_segments_mut` to construct a URL with encoded path segments.
> feat: Update `url` to 2.2.0

- Cargo.lock
- Cargo.toml
- src/actors/snapshots/symbolicator__actors__symbolication__tests__add_bucket-2.snap
- src/actors/snapshots/symbolicator__actors__symbolication__tests__add_bucket.snap
- src/actors/snapshots/symbolicator__actors__symbolication__tests__apple_crash_report.snap
- src/actors/snapshots/symbolicator__actors__symbolication__tests__minidump_linux.snap
- src/actors/snapshots/symbolicator__actors__symbolication__tests__minidump_macos.snap
- src/actors/snapshots/symbolicator__actors__symbolication__tests__minidump_windows.snap
- src/actors/snapshots/symbolicator__actors__symbolication__tests__remove_bucket-2.snap
- src/actors/snapshots/symbolicator__actors__symbolication__tests__remove_bucket.snap
- src/actors/snapshots/symbolicator__actors__symbolication__tests__wasm_payload.snap
Insta has updated its dependency on `serde_yaml`, which ships a change in string
rendering. For this reason, this forces an update to `serde_yaml` and updates
all snapshots.
> build: Update insta and yaml

- Cargo.lock
- Cargo.toml
- src/services/download/gcs.rs
- src/services/download/http.rs
- src/services/download/sentry.rs
- src/utils/futures.rs
The `tokio-retry` crate has a dependency on an old version of the tokio runtime. We do not need any tokio-specific functionality, only the delay.
The exponential backoff was currently configured with a start delay of _10ms_ and limited to 3 retries in total. This does not result in significant variance, so we can get rid of the exponential part entirely. We can bring this back in a similar fashion with the `backoff` crate however, which even has bindings for futures.
> ref(utils): Replace tokio_retry with constant-time backoff

- src/services/download/sentry.rs
The sentry source is already special and this makes it easier to
parse the URI without having to know the internals.
> Provide a specific URI scheme for the sentry source

- Cargo.lock
- Cargo.toml
- src/actors/common/cache.rs
- src/actors/symbolication.rs
- src/endpoints/applecrashreport.rs
- src/endpoints/minidump.rs
- src/endpoints/proxy.rs
- src/endpoints/requests.rs
- src/endpoints/symbolicate.rs
- src/server.rs
- src/services/download/gcs.rs
- src/services/download/http.rs
- src/services/download/mod.rs
- src/services/download/s3.rs
- src/test.rs
- src/utils/futures.rs
- src/utils/http.rs
- src/utils/multipart.rs
Removes all use of the actix crate, specifically the `actix::spawn` function.
Since we no longer use actix web client, we can run on bare `tokio` runtimes.
This allows us to use `tokio::spawn` directly.
Additionally, this PR removes the futures test mode. It used to spawn all
futures on the same thread rather than thread pools. In Rust 1.49, capturing
test output from threads was fixed, so this is no longer necessary.
Finally, this replaces all use of `actix::ResponseFuture` with our own typedef,
until the transition to new-style futures is complete.
> ref: Remove all use of the actix crate

- src/actors/symbolication.rs
- src/app.rs
- src/server.rs
- src/services/download/mod.rs
- src/test.rs
> ref: Use a single tokio runtime and tokio::test

- src/actors/objects/mod.rs
- src/endpoints/proxy.rs
This was struct was only dereffing to the ByteView, which in turn
derefs to [u8].  Use the ByteView directly, which is an Arc clone
itself anyway.
> ref(proxy): remove unnecessary struct

- src/actors/symbolication.rs
The error reporting here was all truncated to "cancelled" or "timeout"
with no extra information, resulting in opaque errors like "internal
errror" with no other information.  This changes a number of functions
over to anyhow::Error with cause chainging.  Only top-level timeouts
are still propagated as SymbolicationError::Timeout with some inner
onces being mapped to anyhow::Error, which now maps into
SymbolicationError::Canceled.
Error reporting in the request future now also logs the error instead
of only capturing it in Sentry.  This allows also getting the errors
during test runs and other debugging.
> ref(symbolication): Preserve and propagate errors better

- src/actors/common/cache.rs
- src/actors/objects/data_cache.rs
- src/macros.rs
We no longer have any code which needs the futures 0.1 version of
tryf!, this has entirely moved to async/await code.  Likewise the
tryf03! is entirely replaced by async/await code.
Only the tryf03pin! macro remains as we still have some async code in
traits.  This has now been renamed back to the simpler tryf! as there
should never be a need to bring the other variations back.
> ref(futures): Remove unused macros

- Cargo.toml
- src/services/download/filesystem.rs
- src/services/download/mod.rs
Now that all the downloaders run on tokio 1.0 they can and should use
the async filesystem operations provided.  Finally releasing us from
potentially blocking operations.
> ref(downloaders): Use tokio's async filesystem operations

- src/app.rs
- src/endpoints/applecrashreport.rs
- src/endpoints/minidump.rs
The minidump and apple crash report endpoints pass an I/O threadpool without actually using it. Removing this allows to clean up the service state and remove I/O pools entirely from the public interface.
> ref(endpoints): Remove redundant I/O pools from functions

- Cargo.lock
- Cargo.toml
- src/actors/symbolication.rs
- src/endpoints/applecrashreport.rs
- src/endpoints/minidump.rs
- src/macros.rs
- src/utils/multipart.rs
- src/utils/sentry.rs
Adds a `compat_handler` macro that converts async handler functions into a
legacy future and binds the `sentry::Hub` from the actix request.
The only functional difference in this PR is that we no longer record the CRC32
of the minidump, since we have never and will not require this context.
> ref(endpoints): Rewrite multipart in async/await

- src/endpoints/applecrashreport.rs
- src/endpoints/healthcheck.rs
- src/endpoints/minidump.rs
- src/endpoints/proxy.rs
- src/endpoints/requests.rs
- src/endpoints/symbolicate.rs
- src/macros.rs
- src/utils/futures.rs
> ref(endpoints): Port remaining endpoints to async/await

- src/actors/cficaches.rs
- src/actors/objects/data_cache.rs
- src/actors/symcaches.rs
- src/endpoints/applecrashreport.rs
- src/endpoints/minidump.rs
- src/endpoints/symbolicate.rs
- src/services/download/locations.rs
- src/sources.rs
- src/types/mod.rs
- src/utils/sentry.rs
Introduces a convenience method to run `configure_scope` directly on a type that
implements the trait. Since the purpose of this trait is not to write a scope,
and rather configure it, it is now renamed to `ConfigureScope`.
> ref(utils): Improve the configure scope trait

- src/services/mod.rs
- src/services/objects/meta_cache.rs
- src/services/objects/mod.rs
The service state used to create an I/O threadpool that was passed into the
objects and download services. The pool has been removed from the Download
service since, and is not used in the objects actor. Therefore, it is dead code
and can be removed.
> ref(service): Remove unused I/O threadpool

- src/services/download/filesystem.rs
- src/services/download/gcs.rs
- src/services/download/http.rs
- src/services/download/locations.rs
- src/services/download/mod.rs
- src/services/download/s3.rs
- src/services/download/sentry.rs
- src/services/objects/meta_cache.rs
- src/services/objects/mod.rs
- src/sources.rs
- src/types/objects.rs
- src/utils/paths.rs
Nightly clippy starts warning about this.  As long as it stays
consistent that seems like a reasonable thing.
> ref(clippy): Do not use capitalised acronyms

- tests/integration/conftest.py
The Microsoft symbol server has started returning `transfer-encoding: chunked`
for its `404` responses. Our HitCounter proxy uses to return this header to the
caller, but at the same time responds with `HTTP/1.0`. This is invalid and
causes the HTTP client in Symbolicator to fail.
This problem does not occur in production code. The fix is to configure the WSGI
test server for `HTTP/1.1`.
> fix(test): Enforce HTTP/1.1 to support proxying to MSDL

- Cargo.lock
- Cargo.toml
- src/services/download/gcs.rs
Reverts getsentry/symbolicator#376
Let's do this on Monday and not leave a dangerous commit on master in the mean time.
> Revert "ref(deps): Upgrade jsonwebtoken crate"

- src/utils/paths.rs
While this code wasn't unsafe due to the checks it is always safer not
to manually slice strings.
An alternative here was to use .trim_end_matches() which allows
chaining the operations without the .unwrap_or() calls in between and
is thus a bit more readable.
However it is no longer strictly the same since it would remove this
patter from the end as many times as it occurs instead of only once.
In practice we're unlikely to notice the difference I guess, but still
this is more correct.
> ref(paths): Avoid manual slicing

- CHANGELOG.md
- Cargo.lock
This incorporates pull request getsentry/symbolic#323.
> build: Bump symbolic to fix large public records

- tests/integration/conftest.py
The mechanims used to select a free port for symbolicator to listen on
was racy and lead to flaky tests due to ports being in used.  This
insteads configures symbolicator to use port 0, ensuring that its
server gets a unique port number from the kernel without races.  The
port number is then extracted from the logs printed.
To do this the simplest way involves starting a thread, in fact this
is one of the modes that subprocess.Popen.communicate() uses
internally anyway so this isn't terrible.  Forever reading line by
line once started is perhaps not great but these are just tests after
all.
> fix(tests): Fix a race condition in integration tests

- CHANGELOG.md
- Cargo.lock
This incorporates the symbolic fix in https://github.com/getsentry/symbolic/commit/4f371639dde89b734d84d4731d265946fa526053 into symbolicator.
> build: Bump symbolic to fix endless loop

- Cargo.lock
- Cargo.toml
- src/services/download/gcs.rs
We used to be on a custom git version, but we should be able to use a
normal release by now.
> ref(deps): Upgrade jsonwebtoken crate

- src/services/snapshots/symbolicator__services__symbolication__tests__minidump_windows.snap
- src/services/symbolication.rs
The minidump stack unwiding starts the building of the module info
which is eventually sent back in the symbolication response.  This
consolidates this code by introducing a few more helpers making the
main stackwalking code smaller and separating concerns a bit better.
This makes one change:
- The unwind_status field is now marked as "unused" even when CFI for
the module was found, before it was only marked as unsued if the
CFI was missing.  This behaviour is more correct, the features map
still indicates the presence of the CFI for the module.
No snapshot updates required in sentry
> ref(minidump): Consolidate building of module info

- CHANGELOG.md
- Cargo.lock
This incorporates getsentry/symbolic#326, which adds support for `debug_addr` indexes in DWARF functions.
> build: Bump symbolic for improved DWARF handling

- src/utils/paths.rs
It seems nightly clippy prefers you to flatten the iterator instead of
using if let inside.  Must admit it looks a little cleaner.
> ref(clippy): Flatten iterator instead of if let

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/cache.rs
- tests/integration/test_basic.py
The code used to update the mtime wasn't actually updating the mtime
as nothing was ever written to the file, it was only opened.  This
pulls in a new library which seems to do a better job at this.
There is now an explicit unit test for this, before this was tried to
be covered by an extra iteration in an integration test but this was
occasionlly flaky and did not take into account the mtime needed to be
out of date for more than an hour.
> fix(cache): Update the mtime when it is 1h out of date

- src/utils/paths.rs
Instead of using a for loop and flattening an iterator, we can simply unroll the
loop and match the two arms manually.
> ref: Unroll loop with two items

- src/services/cficaches.rs
- src/services/mod.rs
- src/services/objects/mod.rs
- src/services/symbolication.rs
- src/services/symcaches.rs
This is simpler and reduces the need for some clones.  It also finally
frees the object cache's .find() to not needlessly consume self.
> ref(symcache): Rewrite as async-await code

- src/services/symbolication.rs
- src/utils/hex.rs
- src/utils/paths.rs
- src/utils/sentry.rs
- Construct structs in same order as they are defined.
- Use str::parse() instead of manual radix parsing.
- Use Option::map() instead of manual equivalent.
> ref(clippy): weekly nightly clippy fixes

- CHANGELOG.md
- src/services/download/sentry.rs
Currently we only retry failures during fetching of the headers
instead of also retrying after failures during streaming of the body.
This makes us not very resilient against sentry workers going down.
----
This is part of #395 but without adding the circuit breaker.
> fix(download): Retry entire sentry download on failure

- symsorter/Cargo.toml
- wasm-split/Cargo.lock
- wasm-split/Cargo.toml
This fixes two issues with the workspace build:
1. Aligns the version of `symbolic` used in `symbolicator` and `symsorter`. This
allows to run a single `cargo update -p symbolic` to update both versions,
and ensures identical behavior for sorting and lookups.
2. Marks `wasm-split` as a workspace. Without, it refuses to build as cargo
thinks the crate is a workspace member that is not listed in the workspace
root. In a follow-up, we can make this a workspace member.
> build: Update workspace to fix build

- src/middlewares.rs
The bare trait usage syntax is deprecated.
> ref(clippy): Use <dyn Fail> for trait

- Cargo.lock
- src/main.rs
- symsorter/Cargo.toml
- symsorter/src/main.rs
- wasm-split/src/main.rs
This is disabled by default, so enable it explicitly.
> build(lints): Warn for unused crate dependencies

- Cargo.lock
- Cargo.toml
- src/services/bitcode.rs
- src/services/download/filesystem.rs
- src/services/download/gcs.rs
- src/services/download/http.rs
- src/services/download/mod.rs
- src/services/download/s3.rs
- src/services/download/sentry.rs
This logs a single sentry error for bcsymbolmap failures.  We lose the
log entry though.  But the error contains both the full error chain as
well as more context on what went wrong with it.
To make the functions more robust it changes the file_type arg to not
take a list, this way the error logging doesn't need to take care of
this and is also more type-strict.  It has some lifetime implications
in the downloader which gets cleaned up a little bit.
> fix(symcache): Better error reporting for bcsymbolmap failures

- src/services/bitcode.rs
- src/services/download/filesystem.rs
- src/services/download/gcs.rs
- src/services/download/http.rs
- src/services/download/locations.rs
- src/services/download/mod.rs
- src/services/download/s3.rs
- src/services/download/sentry.rs
- src/services/objects/data_cache.rs
- src/services/objects/meta_cache.rs
- src/services/objects/mod.rs
- src/types/objects.rs
This struct is now no longer only used to locate object files on
sources (symbol servers) but generally it can be any Debug Information
File.  Hence it makese sense to name things better.
This is purely a renaming commit, no other changes are made.
> ref(naming): Rename ObjectFileSource to RemoteDif

- src/services/download/gcs.rs
- src/services/download/locations.rs
- src/services/download/s3.rs
The S3 and GCS URIs can have keys which may need percent-encoding.
This yields equivalent but slightly nicer URIs to copy-paste.
> feat(difs): percent-encode URIs shown in DIF candidates

- wasm-split/src/main.rs
The `--strip` option of wasm-split leaves symbol names intact. Specifically, it does not remove the ["name" custom section
](https://webassembly.github.io/spec/core/appendix/custom.html#name-section). This may be desired in some cases, but it significantly increases the size of the wasm bundle and potentially leaks source info to users.
This PR adds a `--strip-names` flag to remove the "name" section as well.
I considered adding a flag (e.g. `--strip-by [NAME]`) to strip arbitrary custom sections matching NAME (which confusingly, could be "name"), but decided against it. Let me know if that would be preferable.
I haven't yet had the chance to verify that our wasm bundle still works with sentry itself after removing the name section, but I'm guessing it will. I won't merge here until that …
> Add --strip-names option to wasm-split

- Cargo.lock
- crates/wasm-split/Cargo.toml
- crates/wasm-split/src/main.rs
This is purely to streamline with other workspace members.
Old help:
```
Usage: wasm-split <input> [-o <out>] [-d <debug-out>] [--strip] [--strip-names] [-q] [--build-id <build-id>]
Adds build IDs to wasm files. This tool can both add missing build IDs and split a WASM file into two: a main binary and a debug companion file.  The debug companion file will contain all sections of the original file. This is necessary as DWARF processing requires knowing the location of all sections (specially the code section) to calculate offsets. This prints the embedded build_id in hexadecimal format to stdout.
Options:
-o, --out         path to the output wasm file. If not provided the same file
is modified in place.
-d, --debug-out   path to the output debug wasm file. If not provided the
debug data …
```
> ref(wasm-split): Use structopt instead of argh

- .craft.yml
- .github/workflows/build.yml
- CHANGELOG.md
Performs a full workspace build and adds `symsorter` and `wasm-split` to the list of published binaries. They are not stripped for so that backtraces can be enabled when needed.
> build: Publish symsorter and wasm_split

- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/services/symbolication.rs
- crates/symbolicator/src/types/mod.rs
This adds a flag `compare_stackwalking_methods` to `RequestOptions` that causes `stackwalk_minidump_with_cfi` to run both the old and new implementations and report the respective runtimes if they output the same stacktrace. The intention is to enable this flag for a proportion of requests.
> feat: Test old and new stackwalking implementations

- .dockerignore
- Dockerfile
With the workspace crates cargo needs to see all the Cargo.toml files
which contributed to the workspace Cargo.lock otherwise it will try
and re-generate the lockfile.  This makes sure we insert all the
Cargo.toml files before building the dependencies.
> fix(docker): Ensure lockfile is not regenerated

- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/services/symbolication.rs
- crates/symbolicator/src/types/mod.rs
Reverts getsentry/symbolicator#413
The `get_referenced_modules_from_minidump` function is calling the wrong stackwalker currently which makes all symbolications fail hard because every subprocess panics.
> Revert "feat: Test old and new stackwalking implementations"

- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symsorter/Cargo.toml
We think we no longer need the demanger branch as this should be
sufficiently improved.  But there might still be demangler
regressions.
This includes the symcache fix for large number of files.
> build: Depend on released symbolic

- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symsorter/Cargo.toml
We saw a 4x regression in the number of demangling failures going with the officially released versions. Not sure we want to take that for now.
> fix: Switch demangling fixes back on

- CHANGELOG.md
- crates/symbolicator/src/services/symbolication.rs
This collects metrics on the number of scanned or unsymbolicated frames,
those referencing unmapped modules, and stack traces that do not end in
well known thread bases or contain any of the mentioned bad frames.
> feat: Implement new Symbolication Metrics

- .gitignore
- crates/symbolicator/src/sources.rs
- crates/symsorter/src/app.rs
- crates/symsorter/src/config.rs
- local.example.yml
- Creates an example symbolicator config that includes a local source and the public microsoft server, with a link to more publicly available sources.
- Makes symsorter more suited to sort into a local filesystem source by removing the need to specify a bundle id, and removing a delay related to compression.
> ref: Make symsorter more suited for local development

- crates/symbolicator/src/services/bitcode.rs
- crates/symbolicator/src/sources.rs
- crates/symbolicator/src/utils/paths.rs
This FileType is actually part of the public API as it can be used in
the configuration of a source to only use a source for certain
filetypes.  So we should have some meaningful name which won't be
wrong and confuse in the future without being too restrictive.
Calling it "PList" is just too generic, so that's a bad choice.
Since all other filetype use the snake_case convention there's no need
to diverge as it would only create confusion (the sourcebundle boat
has sadly sailed).
These changes are fine currently since none of this has been released
yet.
> ref(api): Rename the PList filetype

- crates/process-event/src/main.rs
Nightly clippy points out that as the std::mem::replace() is with
Default::default we can as well use std::mem::take().
> ref(clippy): Prefer std::mem::take()

- Dockerfile
We shouldn't be affected by this bug, but let's track the latest
anyway.
> build: Bump Rust version to 1.52.1

- crates/symbolicator/src/endpoints/symbolicate.rs
- crates/symbolicator/src/services/symbolication.rs
- Tag all metrics with the platform (based on module type) and the origin (minidump vs other)
- Collect metrics for:
- Unparsable modules
- Short (<5 frames) stack traces
- Add more metrics for unsymbolicated frame by their frame trust
- Collect frame metrics after scanning heuristic
> feat: Fine-tune symbolication metrics

- crates/symbolicator/src/services/bitcode.rs
- crates/symbolicator/src/services/download/mod.rs
- crates/symbolicator/src/services/download/sentry.rs
- crates/symbolicator/src/services/objects/mod.rs
- crates/symbolicator/src/services/symbolication.rs
These are fixes to improve the downloading of BCSymbolMap and
associated PList files from the sentry source.  The sentry source did
not filter files by type, assuing they are all object files.  This is
no longer the case with BCSymbolMap and PList files introduced.
Related PRs:
https://github.com/getsentry/sentry/pull/25712
https://github.com/getsentry/sentry-cli/pull/952
https://github.com/getsentry/symbolic/pull/373
> fix(bcsymbolmap): downloading BCSymbolMaps from sentry

- crates/symbolicator/src/services/symbolication.rs
This moves some metrics outside the check for the `compare_stackwalking_methods` flag so they will always be emitted.
> ref(symbolication): Unconditionally emit metrics

- crates/symbolicator/src/services/symbolication.rs
This refactors `stackwalk_minidump_with_cfi` so that the original stackwalking procedure is run in an external process and then, if `compare_stackwalking_methods` is enabled, the new one is run in another external process.
Questions:
- Is it right to put everything into one future?
- Is this sufficient to prevent failures in the new method from interfering with production?
- Where/how should error reporting to sentry take place?
Local tests indicate that it works correctly, but I could be missing something.
> fix(symbolication): Isolate new stackwalking procedure

- CHANGELOG.md
- crates/symbolicator/src/cache.rs
Some caches were missed from the cleanup.  Re-write this to ensure the
compiler at least warns if you forget this.  Also add a test to ensure
cleanup actually happens.
> fix(caches): Clean up all the caches

- crates/symbolicator/src/services/symbolication.rs
This reports an error to sentry and saves the minidump if the new method returns a different stackwalking result than the old one.
This also contains two other minor changes (in separate commits):
1. `StackwalkingOutput` implements `PartialEq`, simplifying the comparison
2. `save_minidump` and `join_procspawn` take the `cache` argument by reference instead of by value. This saves some cloning.
> ref: Report different stackwalking results as sentry errors

- Cargo.lock
This is to incorporate this commit: https://github.com/getsentry/symbolic/commit/abfd6f83bb0bc0f83ce7064b5087f68daaa751ea in which `WindowsUnwindRules` is based on a new `NestedRangeMap` struct.
> build: Update symbolic

- crates/symbolicator/src/services/cacher.rs
- crates/symbolicator/src/services/download/locations.rs
- crates/symbolicator/src/services/download/s3.rs
- crates/symbolicator/src/types/mod.rs
- crates/symbolicator/src/utils/sentry.rs
- crates/symsorter/src/app.rs
Weekly clippy release!  This weeks edition is how to make your
compiler lenient in what it accepts so you can make your linting do
some work.
The compiler was dereferencing these immediately to match the actual
types needed.
> ref(clippy): Avoid unused references

- CHANGELOG.md
- Cargo.lock
This updates includes bumps to a few dependencies (goblin, gimli, wasm stuff),
as well as specific fixes to extract or hand-roll CFI for apple system symbols.
> ref: Update symbolic

- CHANGELOG.md
- crates/symbolicator/src/endpoints/snapshots/symbolicator__endpoints__minidump__tests__basic.snap
- crates/symbolicator/src/services/snapshots/symbolicator__services__symbolication__tests__minidump_windows.snap
- crates/symbolicator/src/services/symbolication.rs
Instead of two times, it will now do up to 5 stack walks, trying to load increasing CFI on each iteration.
> fix: Convert stackwalking/cfi loading into a fixpoint iteration

- crates/symbolicator/src/services/symbolication.rs
> fix: Stop capturing a Sentry Error for each Missing Module

- crates/symbolicator/src/services/symbolication.rs
This is immediately auto-derefed by the compiler already.  Thanks
clippy.
> fix(clippy): remove borrowing of reference

- crates/symbolicator/src/services/snapshots/CAUTION.md
- dangerfile.js
Fixes the snapshot directory used by Danger bot. Also adds a sanity check to ensure Danger is checking the correct directory for snapshot changes.
If the directory does not exist, Danger fails the build with:
If snapshots have changed, Danger warns with:
> fix(ci): Update snapshot directory for Danger checks

- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/metrics.rs
- crates/symbolicator/src/services/download/locations.rs
- crates/symsorter/Cargo.toml
The recent switch of symbolic to nom parsing creates a lockfile conflict, so might as well do a `cargo update`.
Apart from this, this also updates a few packages explicitly. The new `cadence` and `url` version needed some code changes to avoid using deprecated features.
> ref: Update dependencies/lockfile

- CHANGELOG.md
- crates/symsorter/src/app.rs
- crates/symsorter/src/utils.rs
Files that symsorter was unable to generate a valid, nonempty debug identifier (i.e. 000...000) for were being written to disk as if they were successfully parsed and sorted. Chances are if the debug identifier is empty, then the debug info is unusable. Not emitting these saves some manual cleanup work on the user's end since they don't have to prune these directories.
Related: #465
> fix(symsorter): Don't emit files with empty debug identifiers

- crates/symbolicator/src/sources.rs
> fix: Avoid rustdoc complaining about bare url

- crates/symbolicator/src/services/symbolication.rs
Commit 41b838f changed the `SourceLookup::get_object_index_by_addr`
function to return a stable module index value, independent of the inner
Vec's ordering. This updates the debug sessions collection to be keyed
on the same module index.
The specific commit making the above change in #301 is 2a19481.
> fix(sources): Find debug session from module index

- crates/symbolicator/src/services/objects/data_cache.rs
The source tags are relevant to the download part, but having them
also part of the object scope means they end up in errros about the
processing like CFI errors and write errors.  Yet they have nothing to
do with them.  This means that when you search for the source tags you
currently get these unrelated errors.  So remove this.
The source tags for downloads are added in
`<FetchFileDataRequest as CacheItemRequest>::compute()` and are
unchanged here.
> ref(sentry): Remove source tags from object sentry scope

- crates/symbolicator/src/services/symbolication.rs
We saw an increase in "Unknown" platform recently, so lets look at more than just the
first module for its type.
> fix: Look through more modules for type information

- crates/symbolicator/src/services/symbolication.rs
As specified in https://getsentry.atlassian.net/browse/NATV-30?atlOrigin=eyJpIjoiOTI4ZjUyZDM3Y2I3NDg3ZThmYjJhZGI1OTViNTBkNjEiLCJwIjoiaiJ9, the new stackwalking method is allowed to take at most 1.5× as long as the old one to be considered ready for production.
> ref: Error when the new stackwalking method takes 1.5x as long as the old one

- Cargo.lock
- crates/symbolicator/Cargo.toml
There is a new nightly clippy lint that complains about code generated
by the old thiserror.  The new version fixes this lint.
https://rust-lang.github.io/rust-clippy/master/index.html#nonstandard_macro_braces
> ref(deps): bump thiserror dependency

- Dockerfile
We need to do this manually these days, because of how our Docker
setup is.
> build(rustc): bump compiler to 1.53

- mkdocs.yml
It looks like `site_url` is now required in a mkdocs config. Without it, `use_directory_urls` will not work, and links to specific pages must target the actual file in order to fetch useful content. Running `make docs` without the changes in this PR spits out the following warning:
```
WARNING  -  Config value: 'site_url'. Warning: This option is now required. Set to a valid URL or an empty string to avoid an error in a future release.
WARNING  -  Config value: 'site_url'. Warning: The 'use_directory_urls' option has been disabled because 'site_url' contains an empty value. Either define a valid URL
for 'site_url' or set 'use_directory_urls' to False.
```
Links targeting directories without `site_url` and `use_directory_urls` set properly will break in unexpected ways, e.g. opening …
> meta(mkdocs): Fill in a missing mandatory config value

- CHANGELOG.md
- crates/symbolicator/src/metrics.rs
- crates/symbolicator/src/services/download/gcs.rs
- crates/symbolicator/src/services/download/http.rs
- crates/symbolicator/src/services/download/locations.rs
- crates/symbolicator/src/services/download/mod.rs
- crates/symbolicator/src/services/download/s3.rs
- crates/symbolicator/src/services/download/sentry.rs
- crates/symbolicator/src/utils/futures.rs
This begins measuring requests and download throughput related to source-fetching in order to determine what a good set of default timeouts for such requests should be.
The changes can be broken down into three major parts:
1. The addition of `MeasureSourceDownload`, which is a modified version of `MeasureGuard` focused on source downloads
2. Logging stream throughput and duration in `download_stream` via `MeasureSourceDownload`
3. Logging the initial GET request's duration in every type of download source
Source downloads from the local filesystem have been skipped as it is unlikely that any meaningful or useful information will come from logging information about those.
Open questions and notes will be left directly on the diff.
> feat(download): Measure how long it takes to download sources

- CHANGELOG.md
- crates/symbolicator/src/cache.rs
- crates/symbolicator/src/services/download/locations.rs
- crates/symbolicator/src/services/objects/data_cache.rs
- crates/symbolicator/src/test.rs
Currently, when a file that should be downloaded can't be found, `FetchFileDataRequest::compute` returns `Ok(CacheStatus::Negative)` to signal that the download shouldn't be retried for a while. This change extends this behavior to download errors. There is also a unit test, but I still need to figure out the easiest way to get the download to fail.
> feat: Cache download failures

- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/cli.rs
This switches sessions to request-mode to pre-aggregate them
> ref: Update Sentry SDK

- CHANGELOG.md
- crates/symbolicator/src/config.rs
- crates/symbolicator/src/services/download/filesystem.rs
- crates/symbolicator/src/services/download/gcs.rs
- crates/symbolicator/src/services/download/http.rs
- crates/symbolicator/src/services/download/mod.rs
- crates/symbolicator/src/services/download/s3.rs
- crates/symbolicator/src/services/download/sentry.rs
- crates/symbolicator/src/services/objects/data_cache.rs
This adds a configuration option `streaming_timeout` (name, default value, and documentation subject to change) that controls how long it may take to download 1GB from `http`, `sentry`, and `s3` sources.
Unfortunately this requires a fair bit of refactoring. Currently the timeout logic is contained in `DownloadService::download`, which delegates the download to one of 5 other methods based on the type of source and wraps the whole thing in a timeout future. With these changes, the timeout can't be known in `DownloadService::download`, but only in the individual download methods. This means that the timeout logic must be pushed into those methods.
There's an additional problem that I haven't solved yet in the `sentry` case: the `download_source` method calls another method …
> feat: Add streaming_timeout configuration option

- CHANGELOG.md
- crates/symbolicator/src/cache.rs
- crates/symbolicator/src/services/download/locations.rs
- crates/symbolicator/src/services/objects/data_cache.rs
- crates/symbolicator/src/test.rs
This reverts commit eb7f3077152297d9115b96e7db624e7299cd220b.
The change leads to a regression on the user end because files with download errors will show up as not found. See also [here](https://getsentry.atlassian.net/browse/NATIVE-58?atlOrigin=eyJpIjoiMDVmYTg3Zjk2NmZiNDUwYWI1OWYwYTlhZTJkZDEyYmIiLCJwIjoiaiJ9).
> Revert "feat: Cache download failures (#484)"

- CHANGELOG.md
- crates/symbolicator/src/config.rs
- crates/symbolicator/src/services/download/gcs.rs
- crates/symbolicator/src/services/download/http.rs
- crates/symbolicator/src/services/download/mod.rs
- crates/symbolicator/src/services/download/s3.rs
- crates/symbolicator/src/services/download/sentry.rs
- docs/index.md
Does what it says on the tin. This uses the same timeout as the maximum timeout on the entire download, just to stay mostly consistent for now. I expect we may change some of these defaults as more measurements of actual durations start filtering in from https://github.com/getsentry/symbolicator/pull/483's changes.
I considered pulling out the three timeouts into their own dedicated config in the same way `CacheConfigs` have their own dedicated structure, but I wasn't sure if that was overkill for this. Open to doing exactly that if any of us feel strongly enough about doing this though.
> feat(download): Allow configuring the timeout on the initial HEAD request on a source download

- CHANGELOG.md
- crates/symbolicator/src/config.rs
- docs/index.md
Adds some tests for symbolicator's config focused on download timeouts. Also includes some nitpicky changes to the changelog and documentation.
> feat(config): Add tests for config values

- crates/symbolicator/src/services/download/mod.rs
This fixes a bug where the timeouts returned by `content_length_timeout` were way too short because of truncating integer division. Moreover, the minimum returned timeout is increased to 10s.
> fix: Use floats for timeout calculation

- CHANGELOG.md
- crates/symbolicator/src/cache.rs
- crates/symbolicator/src/services/download/locations.rs
- crates/symbolicator/src/services/objects/data_cache.rs
- crates/symbolicator/src/test.rs
This re-applies the changes in https://github.com/getsentry/symbolicator/pull/484, with one difference: Download failures are stored as `CacheStatus::Malformed` instead of `CacheStatus::Negative`.
This is meant to be a stopgap against repeatedly re-downloading files. A known caveat to the changes in this diff is that it is currently not possible in a cached failure to distinguish between download failures and malformed object files. A follow-up PR that attempts to address that drawback will be opened later.
> Restore caching of download failures

- CHANGELOG.md
- crates/symbolicator/src/config.rs
See title. This obviously isn't final, but based on about a week's worth of data so far it seems like lowering the timeout to 15s should be reasonable and allow the 95th percentile of requests to complete without timing out.
> feat(download): Set default timeout for a download's HEAD request to 15s

- crates/symbolicator/build.rs
By moving the crate into `crates` the build script now no longer finds the git index and recompiles permanently. The better way to prevent this is to use `rerun-if-env-changed`.
> fix: prevent useless recompilations

- CHANGELOG.md
- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/endpoints/applecrashreport.rs
- crates/symbolicator/src/endpoints/minidump.rs
- crates/symbolicator/src/services/symbolication.rs
- crates/symbolicator/src/utils/multipart.rs
Instead of passing (and serializing) a byte buffer to procspawn, this will rather create a tempfile and pass that path via procspawn.
This seems to be a small win when processing a 20M minidump, though note that I was timing `cargo run -p process-event` so timings include overhead from both cargo and uploading of the minidump.
before:
Time (mean ± σ):      1.611 s ±  0.041 s    [User: 274.8 ms, System: 102.0 ms]
Range (min … max):    1.548 s …  1.697 s    10 runs
after:
Time (mean ± σ):      1.526 s ±  0.024 s    [User: 275.7 ms, System: 101.5 ms]
Range (min … max):    1.496 s …  1.573 s    10 runs
Due to some error handling and borrowcheck shenanigans, the minidumps are now persisted in the diagnostics cache for *all* errors during processing, while previously timeouts were ignored.
> fix: Avoid serializing minidumps over procspawn

- CHANGELOG.md
- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/cli.rs
- crates/symbolicator/src/config.rs
- crates/symbolicator/src/metrics.rs
- docs/index.md
This is an adaptation of https://github.com/getsentry/relay/pull/625/files. This is intended to address https://getsentry.atlassian.net/browse/NATIVE-129.
> feat(metrics): Add option to send hostname with every metric

- CHANGELOG.md
- crates/symbolicator/src/services/symbolication.rs
Our lack of support for `DW_CFA_undefined` can lead to conditions where we read a garbage return address via CFI. We observed this specifically for the `_start` function as generated for some linux compiler/libc combinations.
This works around this by explicitly skipping a trailing unmapped frame following `_start`.
Fixes https://getsentry.atlassian.net/browse/ISSUE-1247
> fix: Skip trailing garbage frames after `_start`

- CHANGELOG.md
- crates/symbolicator/src/cache.rs
- crates/symbolicator/src/services/objects/data_cache.rs
- crates/symbolicator/src/services/objects/mod.rs
- crates/symbolicator/src/services/symbolication.rs
- crates/symbolicator/src/services/symcaches.rs
- crates/symbolicator/src/types/objects.rs
This is the start of a series of PRs whose end goal is to allow symbolicator to separate download errors from IO and conversion errors. The end goal is to be able to apply different expiration strategies and include additional diagnostic information to these entries in order to make it easier to debug why a source file might be missing. 
The PRs are being broken down as follows:
1. 👉 Introduce the new cache status without changing the existing functionality, convert the new status to Malformed if needed (#509) 👈 you are here
2. Extend both the new cache status and the Malformed cache status to accept an arbitrary string that describes the root cause of the issue (#510)
3. Identify and split out code paths that should be using the new cache status without changing their return value (#511) …
> feat(cache): Add a new cache status `CacheSpecificError`

- crates/symbolicator/src/cache.rs
This PR was quickly shoved in between the original first (#509) and second (#510) PRs to avoid review churn.
This is a member of a series of chained PRs:
1. Introduce the new cache status without changing the existing functionality, convert the new status to Malformed if needed (#509)
1. 👉 Update cache expiration strategy selection so different caches will expire entries triggered by cache-specific problems after a timeout that makes sense for the cache (#516) 👈 you are here
1. Extend both the new cache status and the Malformed cache status to accept an arbitrary string that describes the root cause of the issue (#510)
1. Identify and split out code paths that should be using the new cache status without changing their return value (#511)
1. Begin actually using the new cache status by …
> `CacheStatus::CacheSpecificError` entries have different timeout behaviours based on the type of cache they belong to

- CHANGELOG.md
- crates/symbolicator/src/cache.rs
- crates/symbolicator/src/services/bitcode.rs
- crates/symbolicator/src/services/cficaches.rs
- crates/symbolicator/src/services/objects/data_cache.rs
- crates/symbolicator/src/services/objects/meta_cache.rs
- crates/symbolicator/src/services/objects/mod.rs
- crates/symbolicator/src/services/symbolication.rs
- crates/symbolicator/src/services/symcaches.rs
- crates/symbolicator/src/types/objects.rs
Welcome to part 2 of my PR series on making symbolicator's cache statuses gooder. **Before reviewing or merging this PR, you may be interested in taking a look at part 1 first for some context: https://github.com/getsentry/symbolicator/pull/509**
If you've already seen #509 or you're brave enough to be look at these changes as-is because you reviewed an eerily similar set of changes in a previous PR, then let's continue.
This belongs to the following chain of PRs:
1. Introduce the new cache status without changing the existing functionality, convert the new status to Malformed if needed (#509)
1. Update cache expiration strategy selection so different caches will expire entries triggered by cache-specific problems after a timeout that makes sense for the cache (#516) 
1. 👉 Extend both the …
> feat(cache): Stuff error messages into `Malformed` and `CacheSpecificError` cache files

- crates/symbolicator/src/services/download/gcs.rs
- crates/symbolicator/src/services/download/http.rs
- crates/symbolicator/src/services/download/mod.rs
- crates/symbolicator/src/services/download/s3.rs
- crates/symbolicator/src/services/download/sentry.rs
- crates/symbolicator/src/services/objects/data_cache.rs
This is part 3 of a series of PRs focused on cache statuses. Like the others, if you haven't taken a look at the previous PRs and have no context on these changes, it may be helpful to take a look at those first: #509 #510 
1. Introduce the new cache status without changing the existing functionality, convert the new status to Malformed if needed (#509)
1. Update cache expiration strategy selection so different caches will expire entries triggered by cache-specific problems after a timeout that makes sense for the cache (#516) 
1. Extend both the new cache status and the Malformed cache status to accept an arbitrary string that describes the root cause of the issue (#510)
1. 👉 Identify and split out code paths that should be using the new cache status without changing their return value …
> feat(cache): Infrastructure to distinguish between errors caused by malformed objects vs cache-specific errors

- CHANGELOG.md
- crates/symbolicator/src/cli.rs
- crates/symbolicator/src/config.rs
- crates/symbolicator/src/metrics.rs
- docs/index.md
Analogous to https://github.com/getsentry/symbolicator/pull/513.
Symbolicator obtains the environment from its Sentry client, which in turn determines it based on the `SENTRY_ENVIRONMENT` variable or the build config if that's not set.
This addresses https://getsentry.atlassian.net/browse/NATIVE-165.
> feat(metrics): Add option to send environment with every metric

- crates/symbolicator/src/services/download/gcs.rs
- crates/symbolicator/src/services/download/mod.rs
The previous debug-print would expose all the sensitive credentials in our logs.
This is https://getsentry.atlassian.net/browse/NATIVE-175
> fix: Do not debug-print RemoteDif

- CHANGELOG.md
- crates/symbolicator/src/services/download/gcs.rs
- crates/symbolicator/src/services/download/http.rs
- crates/symbolicator/src/services/download/mod.rs
- crates/symbolicator/src/services/download/s3.rs
- crates/symbolicator/src/services/download/sentry.rs
- crates/symbolicator/src/services/objects/data_cache.rs
- crates/symbolicator/src/services/objects/mod.rs
- crates/symbolicator/src/test.rs
- tests/integration/test_basic.py
If we know that the reason why we weren't able to download a file was due to permissions we now record that fact and return it in the symbolication response.
This bases itself off of #512 to avoid conflicts with the download error work that's currently open in PRs.
> feat(cache): Mention when a download failure is due to insufficient permissions

- CHANGELOG.md
- crates/symbolicator/src/config.rs
- crates/symbolicator/src/endpoints/applecrashreport.rs
- crates/symbolicator/src/endpoints/minidump.rs
- crates/symbolicator/src/endpoints/mod.rs
- crates/symbolicator/src/endpoints/symbolicate.rs
- crates/symbolicator/src/services/mod.rs
- crates/symbolicator/src/services/symbolication.rs
This adds a symbolicator config option `max_concurrent_requests: Option<usize>` that limits the number of requests symbolicator processes concurrently; any incoming requests beyond this number will be rejected. When this happens, `create_symbolication_request` returns a `MaxRequestsError` that is later converted to a `503` (`Internal Server Error`) status code by actix_web.
The option's default value is currently `None`, which corresponds to the status quo of never rejecting requests. The default will change once we have gathered some production data about request numbers.
(Also there's a bonus unrelated clippy fix)
> feat: Add config option for max concurrent requests

- crates/symbolicator/src/cache.rs
- crates/symbolicator/src/services/bitcode.rs
- crates/symbolicator/src/services/cacher.rs
- crates/symbolicator/src/services/cficaches.rs
- crates/symbolicator/src/services/download/locations.rs
- crates/symbolicator/src/services/objects/data_cache.rs
- crates/symbolicator/src/services/objects/meta_cache.rs
- crates/symbolicator/src/services/objects/mod.rs
- crates/symbolicator/src/services/symcaches.rs
This makes a few methods of `Cacher` properly async, and moves some things around in preparation of multiple cachekey lookups.
This is preparation for https://getsentry.atlassian.net/browse/NATIVE-182
> ref: Make parts of Cacher properly async

- crates/symbolicator/src/services/download/mod.rs
- crates/symbolicator/src/services/symbolication.rs
This adds a unittest which checks the paths for ELF DIFs are generated
correctly.  Trivial, but it helped me understand a user's issue.
> test: Unitest for creating ELF DIF lookup paths

- crates/symbolicator/src/services/symcaches.rs
This is a cheap attempt to make the test less flaky by simply giving
it a much larger timeout.
See #512 where this was flaky.
> test: Increase timeout for less flaky test

- crates/symbolicator/src/metrics.rs
- crates/symbolicator/src/services/bitcode.rs
- crates/symbolicator/src/services/cacher.rs
- crates/symbolicator/src/services/cficaches.rs
- crates/symbolicator/src/services/download/mod.rs
- crates/symbolicator/src/services/download/sentry.rs
- crates/symbolicator/src/services/objects/data_cache.rs
- crates/symbolicator/src/services/symbolication.rs
- crates/symbolicator/src/services/symcaches.rs
- crates/symbolicator/src/utils/futures.rs
This is also removes that macro completely, and is a prerequisite to making cache computation futures `Send`, so we can get rid of the `spawn_compat` nonsense in a followup.
> ref: Replace last future_metrics usage with measure

- crates/symbolicator/src/cache.rs
- crates/symbolicator/src/services/cacher.rs
This implements the proposed cache versioning scheme, and will try to look up fallback cache versions if no current version is found.
It tries the fallback cache keys in order and uses the first one it finds. If so, it will schedule a computation task (on the same thread pool, but not awaiting its result).
If no cache is found, the computation is done eagerly.
Should cover https://getsentry.atlassian.net/browse/NATIVE-180 and https://getsentry.atlassian.net/browse/NATIVE-182.
The next followup on this would be to create a separate bounded compute pool for these background tasks. An extremely simple solution for "bounded queue" would be to just have an `AtomicUsize` that does the bounding, and still spawn the tasks on the current runtime.
> ref: Make it possible to use outdated caches

- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/metrics.rs
- crates/symbolicator/src/services/symbolication.rs
- crates/symbolicator/src/utils/futures.rs
- crates/wasm-split/Cargo.toml
The only thing that needed changes was replacing some deprecated cadence APIs
> meta: Update dependencies

- .github/workflows/ci.yml
We refactored [`setup-sentry`](https://github.com/getsentry/sentry/pull/28281) to be able to compose actions better. This workflow was only copying `setup-sentry` which now include `setup-python`.
> build(ci): Fix sentry integration test due to refactored actions

- crates/symbolicator/src/cache.rs
> fix: Clamp lazy-computation options to avoid misconfiguration

- crates/symbolicator/src/server.rs
We have recently observed a number of stack overflows.
It looks like the default tokio Runtime thread size is 2M, which is lower than the default 8M,
and Rust is known to use more stack space (in favor of heap allocations).
> fix: Increase Runtime stack size

- crates/symbolicator/src/services/bitcode.rs
- crates/symbolicator/src/services/cficaches.rs
- crates/symbolicator/src/services/download/mod.rs
- crates/symbolicator/src/services/download/sentry.rs
- crates/symbolicator/src/services/mod.rs
- crates/symbolicator/src/services/objects/data_cache.rs
- crates/symbolicator/src/services/objects/mod.rs
- crates/symbolicator/src/services/symbolication.rs
- crates/symbolicator/src/services/symcaches.rs
- crates/symbolicator/src/utils/futures.rs
Now that the main symbolicator runs on the IO pool, it is not necessary to spawn download tasks on that same pool and await those tasks. Just await those futures directly.
This also simplifies things around taking ownership of self and arguments.
This also introduces a `CancelOnDrop` wrapper which is wrapped around spawns that are otherwise never canceled when the outer future is being timed out.
> ref: Avoid spawning separate download tasks (NATIVE-191)

- crates/symbolicator/src/services/objects/data_cache.rs
#512 downgraded our log from `error` to `debug`, but that means we stopped reporting download errors to S4S.
This brings back S4S logging of download errors, but still skips unactionable permissions errors.
> fix: Log Download Errors internally

- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/endpoints/mod.rs
- crates/symbolicator/src/services/minidump.rs
- crates/symbolicator/src/services/mod.rs
This adds support for reading our custom minidump extension, and transforming it into `types::RawStacktrace` which we will use in a followup PR to combine with the stacktrace that was extracted via breakpad.
The PR also contains a documentation of the binary format of our extension.
> feat: Extract client-side stack traces from Minidumps (NATIVE-195)

- crates/symbolicator/src/services/minidump.rs
- crates/symbolicator/src/services/symbolication.rs
Overrides the breakpad-processed stack traces by client-side stack traces extracted from our minidump extension if those are available.
> feat: Prefer client-side stack traces over breakpad ones (NATIVE-196)

- crates/symbolicator/src/endpoints/symbolicate.rs
Does what it says on the tin. This applies a 5MB limit to `/symbolicate`'s request body. If this check fails, an axum `Rejection` is returned which will be automatically converted and returned as an error response.
> ref(symbolication): Re-apply 5MB limit to request bodies

- Cargo.lock
Symbolic has a bug where it tried to split a string not on a UTF-8
character boundary.  This pulls in that fix.  It also bumps some other
symbolic dependencies.
> deps(symbolic): Bump symbolic version for UTF-8 char split bug

- crates/symbolicator/src/utils/sentry.rs
Tags are indexed and we don't need to be able to search on these.
Plus adding a `sentry.project_id` in the tags is highly confusing wrt
request.scope.  Originally this stuff was exposed in the context as
part of the http headers, so lets at least do this partially again.
> ref: Expose the sentry HTTP headers in the context, not tags

- CHANGELOG.md
- crates/symbolicator/src/services/download/sentry.rs
- crates/symbolicator/src/services/snapshots/symbolicator__services__symbolication__tests__add_bucket-2.snap
- crates/symbolicator/src/services/snapshots/symbolicator__services__symbolication__tests__apple_crash_report.snap
- crates/symbolicator/src/services/snapshots/symbolicator__services__symbolication__tests__minidump_linux-2.snap
- crates/symbolicator/src/services/snapshots/symbolicator__services__symbolication__tests__minidump_linux.snap
- crates/symbolicator/src/services/snapshots/symbolicator__services__symbolication__tests__minidump_macos-2.snap
- crates/symbolicator/src/services/snapshots/symbolicator__services__symbolication__tests__minidump_macos.snap
- crates/symbolicator/src/services/snapshots/symbolicator__services__symbolication__tests__minidump_windows-2.snap
- crates/symbolicator/src/services/snapshots/symbolicator__services__symbolication__tests__minidump_windows.snap
- crates/symbolicator/src/services/snapshots/symbolicator__services__symbolication__tests__remove_bucket.snap
- crates/symbolicator/src/sources.rs
- tests/integration/test_basic.py
~~A first shot at fixing a regression where we're no longer fetching
ELF DIFs for minidumps generated on Windows, likely caused by
#414.~~
Symbolicator now requests all known debug file types when encountering a minidump generated by a native executable. This means that minidumps produced by PEs, Machos and ELFs will trigger a search for PDBs, dSYMs, and ELFs if possible.
> fix: Fetch ELF debug files as well just to be safe if it is a Windows minidump

- tests/integration/conftest.py
- tests/integration/test_basic.py
This makes a few quality of (my) life changes to the integration tests so it's a little easier to update and customize them as needed. I've had to muck around in this code a few times now and I'm hoping these changes make it easier to understand what's going on, and how to change the test code in response to a change in symbolicator. 
A major motivation behind the changes is to try to structure things in a way so that the tests don't need to mutate objects too much in order to get the correct expected data to assert against.
- Consolidate common parts of the stack trace and the modules into shared variables
- Merge redundant helpers that construct results for failed symbolication attempts
- Prefer passing in specific configs for error results as opposed to referring to named constants …
> ref: Minor integration test changes

- CHANGELOG.md
- Cargo.lock
This does a `cargo update` which also pulls in an updated `symbolic` which can deal with broken flutter 2.5 debug files.
> meta: Bump dependencies

- crates/symbolicator/src/services/minidump.rs
- crates/symbolicator/src/services/symbolication.rs
This uses the `function` property instead of `symbol`, which is ultimately what sentry uses.
It also avoids flagging modules as `unwind: missing` which were included in client-walked stacks, but which were *really* missing in the previous breakpad-based walk.
Additionally, it moves the error-reporting of invalid minidumps *after* the breakpad-based walk, to not log errors in case breakpad isnt able to process the minidump either.
> fix: Output correct function for client-side frames (NATIVE-150)

- crates/symbolicator/src/services/bitcode.rs
- crates/symbolicator/src/services/download/filesystem.rs
- crates/symbolicator/src/services/download/gcs.rs
- crates/symbolicator/src/services/download/http.rs
- crates/symbolicator/src/services/download/mod.rs
- crates/symbolicator/src/services/download/s3.rs
- crates/symbolicator/src/services/download/sentry.rs
- crates/symbolicator/src/services/objects/data_cache.rs
While seeing this, I became curious how much stuff we needlessly clone all the time.
> ref: Avoid using owned PathBuf if a &Path is enough

- CHANGELOG.md
- Dockerfile
I have tested and this gets build fine, but I don't know how to test the functionality of docker images.
This was first brought up in getsentry/onpremise#1128.
> Use rust:bullseye-slim as base image

- CHANGELOG.md
- crates/symbolicator/src/cache.rs
- crates/symbolicator/src/services/shared_cache.rs
- crates/symbolicator/src/test.rs
> feat: Upload concurrency and backpressure control for shared cache

- CHANGELOG.md
- crates/symbolicator/src/cache.rs
- crates/symbolicator/src/services/cacher.rs
Primarily fixes a regression from the shared cache PR (https://github.com/getsentry/symbolicator/pull/581) which was no longer writing the sentinel/"header" for malformed entries in caches.
Also includes a minor fix that ensures that other non-positive entries in the cache are truncated in case they are overwriting some other content that is slightly longer than their new value. This is highly unlikely to occur, but this is added in as a safeguard if this _does_ ever occur.
This also renames the helper because there's no need for the user to know about the existence of markers at the abstraction level where that would be invoked.
Unit tests have been written because they would have caught this error assuming that they weren't deleted or commented out during the original function's …
> fix(cache): Add back in the marker at the beginning of malformed cache entries

- crates/symbolicator/src/utils/gcs.rs
We accidentally switched to requesting a read-write scope for all
buckets symbolicator tries to access and customers might not have
given our tokens those permissions, resulting in us not being able to
use their symbol source.
Tests probably keep passing since the GCP tests are not configured to
run correctly in CI yet.  Something else to fix, but let's stop this
regression first.
> fix(gcs): Only request read-only access

- crates/symbolicator/src/services/bitcode.rs
- crates/symbolicator/src/services/objects/mod.rs
- crates/symbolicator/src/services/symbolication.rs
This fixes one bug with an ineffective async with_scope,
otherwise it removes some explicit `bind_hub` calls for async functions which are being
`await`ed immediately, cleaning up some Vec allocations while doing so.
This keeps all the `bind_hub` calls that involve spawning futures onto the runtime, or functions that return boxed futures (are not async themselves).
If I understand things correctly, if we `await` futured directly (even with the `join_all` combinator), all of that polling is done in the current thread, so the current thread hub is used for those anyway. No need to explicitly bind another hub. Only spawning things onto the executor would "leave" the current execution context/thread.
#skip-changelog ffs
> fix: Clean up some Hub/Scope manipulation

- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/endpoints/mod.rs
- crates/symsorter/Cargo.toml
This needed some minor changes because of the new `axum` version, otherwise it was just
a normal `cargo update`.
https://getsentry.atlassian.net/browse/NATIVE-397
> ref: Update dependencies (NATIVE-397)

- dangerfile.js
Just a small update on the snapshot instructions to take into account the new integration tests that have been already added to CI. Also includes an additional expansion of some of the existing instructions to provide context on what is being done as well as some gotchas that can only be found if you rummage around in code in other repositories.
> doc: Update and expand instructions on how to update test snapshots on sentry

- crates/symbolicator/src/cache.rs
- crates/symbolicator/src/services/cacher.rs
- crates/symbolicator/src/services/objects/data_cache.rs
- crates/symbolicator/src/services/shared_cache.rs
The SharedCache now lives in the Cacher, and not the Cache.
> fix: Remove dead stores of SharedCache in Cache

- crates/symbolicator/src/services/cacher.rs
I think there was a bug where the lazy computation request was being written into `current_computations` and never cleared from there.
Apart from being a memory leak, that could have potentially returned the error to a non-lazy computation requests based on the `key`.
> fix: Fix lazy computations persisting in `current_computations`

- Cargo.lock
Symbolic changes:
- https://github.com/getsentry/symbolic/pull/441
- https://github.com/getsentry/symbolic/pull/465
> build: Bump symbolic

- crates/symbolicator/src/services/download/mod.rs
- crates/symbolicator/src/services/shared_cache.rs
We accidentally shipped with an upload timeout of 5 seconds, which
explains our relatively high upload failure ratio (vs a zero download
failre ratio).  This adjusts the upload timeout to 60s which should be
sufficient to upload 4GB according to
https://cloud.google.com/storage/docs/uploads-downloads.
It also tweaks the timeout reporting.  The fetch connect timeout was
accidentally reporting as a source downloader.  We still resuse some
of the downloader infrastructure so "gcs" is still reported as a
source tag.  We do not utilise the throughput measurements though, we
already have metrics for throughput with simple counters which is
sufficient for the shared cache.
> fix(shared-cache): Measure and adjust timeouts

- crates/symbolicator/src/cache.rs
The items put on this queue are relatively small so we have no real
worry about memory.  This increases the ratio of concurrency to queue
size to 20:1 instead of 5:1, which is slightly more sensible.  If
anything it is still too concervative.
> ref(shared-cache): Bump default size of upload queue

- crates/symbolicator/src/services/shared_cache.rs
This is bad for sentry grouping.
> fix(shared-cache): Do not put bucket and key in error

- crates/symbolicator/src/services/cacher.rs
- crates/symbolicator/src/services/mod.rs
- crates/symbolicator/src/services/objects/data_cache.rs
- crates/symbolicator/src/services/shared_cache.rs
- crates/symbolicator/src/services/symcaches.rs
If the shared cache is not working for some reason we still want to
ensure symbolicator starts up so that it does not affect the normal
operation.
NATIVE-424
> fix(shared-cache): Ensure startup with broken shared cache

- crates/symbolicator/src/services/shared_cache.rs
This should replace the error reported in NATIVE-427 with
```
"Error fetching from GCS shared cache: Failed to get authentication token,\n caused by: Could not establish connection with server"
```
> fix(shared cache): Improve reporting of auth errors [NATIVE-427]

- Cargo.lock
- crates/symbolicator/Cargo.toml
This should only be temporary until upstream has made a release with
what we need.
In the mean time this allows us to benefit from a few improvements:
- Cheaper token
clones (https://github.com/hrvolapeter/gcp_auth/pull/43 already on
upstream master, not released)
- No thundering herds when refreshing the tokens:
https://github.com/hrvolapeter/gcp_auth/pull/41
> deps: Pull in our gcp_auth fork

- Cargo.lock
- crates/symbolicator/Cargo.toml
The required fixes and features have been merged and released.
> build: Switch back to released gcp_auth version

- crates/symbolicator/src/services/download/sentry.rs
The two timings are basically identical, there's no point in
collecting both, so lets keep the one which captures the timeout.
> ref(downloads): Remove duplicate timing metrics

- crates/symbolicator/src/endpoints/minidump.rs
- crates/symbolicator/src/services/symbolication.rs
I'm not entirely clear if the error we return here would be reported to sentry.
> fix: Discard minidumps with multipart form data [NATIVE-431]

- CHANGELOG.md
- Cargo.lock
- crates/wasm-split/Cargo.toml
- crates/wasm-split/src/main.rs
**Background**
Closes https://github.com/getsentry/symbolicator/issues/614
Note that I brought in a new library to implement the variable-int encoding of the size prefix for the custom section payload. I noticed that the wasmbin library already has an implementation of this [here](https://github.com/GoogleChromeLabs/wasmbin/blob/77f8d736219b5129188c7a6a355c74151bfdc67d/src/builtins/integers.rs#L89). I've filed a ticket on that repo [here](https://github.com/GoogleChromeLabs/wasmbin/issues/6) asking for help.
In the meantime though, this implementation seems to work from my testing. I'm new to rust so please let me know what can improve.
PTAL @Swatinem 
**Testing**
Using a sample wasm binary with debug symbols
```
% wasm-objdump -h main.wasm          
main.wasm:      file format wasm 0x1 …
```
> feat(wasm-split): --external-dwarf-url option

- Cargo.lock
- crates/wasm-split/Cargo.toml
- crates/wasm-split/src/main.rs
Follow-up to https://github.com/getsentry/symbolicator/pull/619.
I wasn't quite sure at the time how to reuse the LEB128 / varint encoding prefix from the `wasmbin` library. It turns out that it is easy to do with the Encode trait.
The library has some basic encoding support for builtin types. Strings get encoded as binary contents, and binary contents (RawBlob) automatically get encoded with the length before the contents, and the length integer gets encoded as a LEB128 / varint. 
Tested by comparing the emscripten output with the wasm-split flag.
```
% emcc -gseparate-dwarf=foobar bazel/hello-world/hello-world.cc -o test.wasm
% wasm-objdump -j external_debug_info -s test.wasm
test.wasm:	file format wasm 0x1
Contents of section Custom:
0050c3c: 1365 7874 6572 6e61 6c5f …
```
> ref(wasm-split): Simplify varint encoding prefix

- CHANGELOG.md
Explanation here https://github.com/getsentry/symbolicator/pull/619/files#r779745210.
PTAL @Swatinem and if possible can you cut a 0.4.2 release afterwards?
> fix incorrect changelog entry from #619

- crates/wasm-split/README.md
I noticed today that our docs are not explaining that this tool is actually available in a precompiled form for some platforms at least.
> doc: added note on wasm-split being precompiled these days

- crates/symbolicator/src/services/shared_cache.rs
At k8s pod startup time the GKE metadata service might not give us
tokens right away, with errors ranging from connection refused to
transient http errors.  So we need to keep trying for a bit longer.
This also adds the timeout on the token retrieval for writing to the
shared cache, otherwise those tasks would indefinitely stall (which
isn't the worst thing ever since they sit in a bounded queue).
Fixes: SYMBOLICATOR-NK
> fix(shared-cache): At startup retry token retrieval

- crates/symbolicator/src/services/shared_cache.rs
This should give us time to inspect traffic etc.
> ref(shared-cache): Set giant timeout

- crates/symbolicator/src/services/cficaches.rs
- crates/symbolicator/src/services/objects/data_cache.rs
- crates/symbolicator/src/services/objects/meta_cache.rs
- crates/symbolicator/src/services/symbolication.rs
This refactors the code, pulling as much of the actual computation out into an async fn.
Moves some refactors out of #628 and this should in the end help with https://github.com/tokio-rs/tracing/issues/1831
#skip-changelog ffs
> ref: Forward CacheItemRequest::compute to async fns

- crates/symbolicator/src/services/shared_cache.rs
Getting the first token may take a little while, this refactors
startup to do this is the background and not block during startup.
When the shared cache becomes available it will be used, it does not
matter much if there are a few cache uses before the shared cache is
available.
> ref(shared-cache): Do not block at process startup

- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/cli.rs
- crates/symbolicator/src/endpoints/mod.rs
- crates/symbolicator/src/services/cacher.rs
- crates/symbolicator/src/services/cficaches.rs
- crates/symbolicator/src/services/download/sentry.rs
- crates/symbolicator/src/services/objects/data_cache.rs
- crates/symbolicator/src/services/symbolication.rs
- crates/symbolicator/src/services/symcaches.rs
- crates/symbolicator/src/utils/sentry.rs
This hooks up the new sentry-tower Http layer to capture request properties, and also start a new transaction.
It also pulls in `tracing` and sprinkles a few `instrument` attrs around, and does explicit trace/transaction forwarding in a couple of places. (so this supercedes #515)
The result is this:
#skip-changelog ffs
> feat: Hook up the new sentry-tower Http Layer (NATIVE-327)

- Cargo.lock
- crates/symbolicator/Cargo.toml
Seems upstream gcp_auth broke the default service account, while they
haven't fixed it yet switch back to our own version of gcp_auth.
> fix(shared-cache): Use a fixed version of gcp_auth

- .github/workflows/ci.yml
Switches from `fucov` to `cargo-llvm-cov`, and pins the nightly Rust version as recent nightlies regressed coverage reports.
> ci: Switch to pinned cargo-llvm-cov

- crates/symbolicator/src/services/bitcode.rs
- crates/symbolicator/src/services/objects/mod.rs
- crates/symbolicator/src/services/symcaches.rs
The bitcode service incorrectly errored out for errors from sources
instead of not providing a result.  This in turn results in any source
errors during bitcode lookups killing the entire symcache lookup, even
if no bitcode could be needed.
Fixes #640
> fix(bitcode): Do not error out for source errors

- crates/symbolicator/src/services/symbolication.rs
Future insta versions no longer use thread but function name.
Refs https://github.com/mitsuhiko/insta/pull/213
> Make a test compatible with future insta versions

- CHANGELOG.md
- crates/symbolicator/src/cache.rs
- crates/symbolicator/src/services/cacher.rs
- crates/symbolicator/src/services/shared_cache.rs
The local cache extends the lifetime of files by bumping the mtime at
most once an hour for files which keep being used.  There are a
surprisingly large number of cache entries which seem to never expire
and always stay in the local cache.
This is not ideal for the shared cache: its entries expire at some
point regardless of whether they are used or not.  And thus the really
common files can expire out, meaning it would be upon a new
symbolicator to repopulate these.
Instead this hooks up the shared cache to also attemp to upload every
time the local cache lifetime was extended.  This will normally only
result in requests but not in actual transfers of data because the
shared cache does not upload when a file already exists.  Only when a
file finally expires out of the shared cache will …
> feat(shared-cache): Upload files on cache extensions as well

- Cargo.lock
- crates/symbolicator/Cargo.toml
Temporarily working off a git dependency for `sentry-rust` while we figure out https://github.com/getsentry/sentry-rust/issues/427.
> build: Switch sentry-rust source to git

- crates/symbolicator/src/services/download/gcs.rs
- crates/symbolicator/src/services/download/mod.rs
- crates/symbolicator/src/services/shared_cache.rs
- crates/symbolicator/src/utils/gcs.rs
When refreshing uploads we make a lot of requests which we expect to
not be needed as the file probably already exists, GCS will not use
those uploads because we use ifGenerationMatch=0.  However as we use a
simple upload mechanism we are transferring the data anyway and that
takes time.
This instead adds an extra check if to see if the file already exists
in the shared cache.  This is racy, however it will already reduce the
duplicate transferred data a lot which should reduce the pressure in
the upload queue.
> feat(shared-cache): Do additional exists check for refresh uploads

- crates/symbolicator/src/services/symbolication.rs
This is one of the changes in https://github.com/getsentry/symbolicator/pull/645.
This requires some type mappery at the interface with `symbolic` because `ProcessState::from_minidump` expects `CodeModuleId`s. See lines 1893–1896, 1911, 1921.
> ref(symbolication): Use DebugId instead of CodeModuleId

- crates/symbolicator/src/services/shared_cache.rs
This gives better context when capturing errors, otherwise you're a
bit lost as to why this is.
> ref(shared-cache): tweak error reporting

- crates/symbolicator/src/services/shared_cache.rs
The metrics indicate that waiting for 3s is pointless, making a cutoff
at 500ms will make a few more requests timeout but that's a reasonable
tradeoff to not wait for 2.5s to get a timeout anyway on most slow
requests.
Some other time we could do some retries with circuit breaking maybe.
Fow now this is fine because the local cache exists as well.
> ref(shared-cache): Shorten the connect timeout

- crates/symbolicator/src/services/symbolication.rs
This is another piece of https://github.com/getsentry/symbolicator/pull/645.
> ref(symbolication): Introduce ProcError struct

- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/cache.rs
- crates/symbolicator/src/logging.rs
- crates/symbolicator/src/services/bitcode.rs
- crates/symbolicator/src/services/objects/data_cache.rs
- crates/symbolicator/src/services/objects/mod.rs
- crates/symbolicator/src/services/symbolication.rs
We can use a released sentry SDK again, and we can replace the
LogError use by tracing which gives us nicer captured errors.
> ref: Use released sentry SDK and remove LogError

- crates/symbolicator/src/services/symbolication.rs
- wrk_minidump.lua
* Avoids some cloning, in particular the whole module list
* Avoids an intermediate `Vec` allocation
* Avoids creating a bunch of short-circuiting Futures, including all the Arc-ing they require
> ref: Optimize Symbolication a bit

- crates/symbolicator/src/services/symbolication.rs
This does a couple of things:
- Switches from `BTreeMap` back to `Vec`, keeping the types that are being serialized over procspawn simpler.
- This is: all modules, missing modules, and cfi caches
- Converting modules to `HashMap`, as lookups should ideally be `O(1)` vs `O(log n)`, though not sure that matters too much.
- Avoid serializing/sending Object Infos for missing modules, the mapping happens *after* procspawn now.
- Only pass the complete module list on the first run, since that should be idempotent.
- Comparison mode will only compare `stacktraces`, as Vec/HashMap have unpredictable sorting order, and the previous optimization makes sure we only get the complete module list once anyway.
The effect is probably hard to quantify. It went from `Requests/sec:    189.40` to …
> ref: Try to optimize stackwalking procspawn usage

- crates/symbolicator/src/services/symbolication.rs
- crates/symbolicator/src/services/symbolication/module_lookup.rs
Ahead of merging the two together (to avoid code duplication, and cloning the module list, and sorting it twice)
> ref: Move SymCache/SourceLookup into their own file

- crates/symbolicator/src/services/symbolication.rs
This adds module lists to the comparison of stackwalking methods in addition to stacktraces.
> ref(symbolication): Compare module lists as well

- crates/symbolicator/src/services/symbolication.rs
When comparing returned module lists between the old and new stackwalking methods, we don't want order to matter.
> ref(symbolication): Compare module lists unordered

- crates/symbolicator/src/utils/paths.rs
For #654. Now it does actually work, at least from my testing on an actual S3 bucket.
Would be nice to have a new release published after this, so people who use tagged versions can actually benefit from this.
> fix: Skip the leading slash for the symstore path

- crates/symbolicator/src/services/snapshots/symbolicator__services__symbolication__tests__minidump_linux_rust_minidump.snap
> test: Accept linux snapshot

- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/services/minidump.rs
- crates/symbolicator/src/services/symbolication.rs
- crates/symbolicator/src/types/mod.rs
This reverts commits that introduced stackwalking comparison code and also does some manual cleanup. We are now doing this work in [the release/rust-minidump branch](https://github.com/getsentry/symbolicator/tree/release/rust-minidump); this functionality shouldn't have been in master.
> ref(symbolication): Return symbolicator to a state of grace

- crates/symbolicator/src/services/symbolication.rs
This sorts the lists of modules instead of converting them to maps. Turns out that the latter is a stupid idea for multiple reasons:
1. what if there are multiple modules with the same (trivial) id
2. serializing a map to json apparently has no defined order
> ref(symbolication): Do module comparison by sorting

- crates/symbolicator/src/services/symbolication.rs
This converts some more methods to simply pass self by reference,
these were left overs from a time when not everything was async-fn.
> ref: Remove some self-cloning methods

- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/services/symbolication.rs
Our rust-minidump branch now contains [this commit](https://github.com/getsentry/rust-minidump/commit/a06a1b60a7391cbc45a70e5ef5ac395149a34597), cherry-picked from upstream. Consequently we need to update the dependency in this branch to make everything work with `DebugId`.
> build: Bump rust-minidump

- Cargo.lock
This is to get the following two fixes in:
1. https://github.com/getsentry/rust-minidump/commit/a4c9dc82cd51f5dac23dfa69b575fbf07f11b6c2
2. https://github.com/getsentry/symbolic/commit/806011c856d71081f447d718a7ce359797c0221b
> build: Bump rust-minidump & symbolic

- crates/symbolicator/src/services/symbolication.rs
- crates/symbolicator/src/services/symbolication/module_lookup.rs
This avoids an unnecessary copy (and subsequent sorting) of the module list,
and fixes the "sources" feature being set on a transient throw-away copy of the module metadata.
> ref: Merge SymCacheLookup and SourceLookup (ISSUE-1365)

- crates/symbolicator/src/services/symbolication.rs
- crates/symbolicator/src/services/symbolication/comparisons.rs
After discussion with @Swatinem and @flub I propose sorting stackwalking differences like this, from most to least interesting:
1. difference in stacktraces, no scanning involved
2. difference in stacktraces, scanning involved
3. difference in modules
4. rust-minidump ran slowly
The reason for separating stacktrace and module differences and treating the latter as less interesting is that we so far all module differences we've seen have been due to fairly benign differences in IDs.
The logic for separating stacktrace differences with and without scanning may be overly simplistic. It just checks whether any frames in the stacktrace returned by breakpad were found by stack scanning.
> ref(symbolication): Triage stackwalking comparisons

- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/services/minidump.rs
- crates/symbolicator/src/services/snapshots/symbolicator__services__symbolication__tests__minidump_linux_rust_minidump.snap
- crates/symbolicator/src/services/symbolication.rs
- crates/symbolicator/src/types/mod.rs
This adapts to the async API of rust-minidump but also does a few other things:
* Changes the FrameTrust mapping to our own struct so we can impl Default etc we need for it.
* Completely ignores registers for now, this is a regression
Apart from the obvious there are still a few test failures that I haven't gotten to the bottom off.
> ref: Target upstream rust-minidump

- CHANGELOG.md
- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symsorter/Cargo.toml
In fact, this pulls in https://github.com/getsentry/symbolic/commit/410812893989e6d7b02086340421c1f70f9d9961, which includes:
- getsentry/symbolic#505
- internal changes
> build: Update symbolic to 8.6.1

- crates/symbolicator/src/services/symbolication.rs
- crates/symbolicator/src/services/symbolication/comparisons.rs
When things are None-like, convert to actually None.
> ref: Follow the modules schema better

- crates/symbolicator/src/services/symbolication/comparisons.rs
Sorting by `debug_id` is apparently not enough.
> fix(symbolication): Sort by image_addr as well

- crates/symbolicator/src/services/shared_cache.rs
These are not the same, having them logged at the same could be
confusing.
> ref(shared-cache): Distinguish forbidden from unauthorised

- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/endpoints/proxy.rs
- crates/symbolicator/src/endpoints/requests.rs
- crates/symbolicator/src/services/cficaches.rs
- crates/symbolicator/src/services/objects/data_cache.rs
- crates/symbolicator/src/services/symcaches.rs
This solves the problem of having a ton of unique `GET /requests/UUID` performance monitoring transactions.
Also updates the Sentry SDK for newly introduced API.
> ref: Give http transactions better names

- crates/symbolicator/src/services/symbolication/mod.rs
This enum is left over from when stackwalking comparison code briefly existed in master. Not sure why this wasn't flagged as dead code.
> fix(symbolication): Remove dead enum

- crates/symbolicator/src/metrics.rs
The "name" tag seems already added by something in our pipeline and
seems to override such a tag that we set here.
> ref(metrics): Use different tag name

- crates/symbolicator/src/services/symcaches.rs
- crates/symbolicator/src/services/symcaches/markers.rs
We want to attach arbitrary markers to symcaches to cater to multiple source files that are used in SymCache creation, and to react to changes to availability of those files.
So far we have used a marker specific to bcsymbolmaps, and this PR keeps backwards compatibility to that marker.
After an initial idea about using JSON, I rather went with just using a u32 bitfield, which will give us enough bits to have 32 markers, and is trivial to parse/compare, instead of JSON which would need to be parsed and potentially allocate.
> ref: Re-design transformed SymCache Markers (NATIVE-499)

- crates/symbolicator/src/services/shared_cache.rs
- crates/symbolicator/src/test.rs
This makes sure that tests from forks which do not have access to the secrets will work seamlessly, just like those tests work seamlessly when you run in local development without the secrets.
The risk of regressing on the GCS functionality is mitigated by the fact CI also runs on master after merging.
> CI: Skip tests when credentials are not available.

- .github/dependabot.yml
- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/endpoints/mod.rs
- crates/symbolicator/src/services/symbolication/module_lookup.rs
- crates/symbolicator/src/services/symcaches.rs
- crates/symbolicator/src/test.rs
Version `0.10.0` was recently tagged with all our latest fixes.
The only blocker as far as I know of is the broken debug-ids that are missing os-specific logic.
> ref: Update rust-minidump, and merge master

- crates/symbolicator/src/services/symbolication/mod.rs
The duration was only measuring the stackwalking itself, not the minidump and symbolfile parsing.
> fix: Measure the correct minidump processing time

- crates/symbolicator/src/services/symbolication/mod.rs
Empty cfi caches likely occur in practice and `rust-minidump`'s parser (quite reasonably) rejects them. Therefore we bail early in such cases.
> fix(TempSymbolProvider): don't parse empty symbol files

- crates/symbolicator/src/services/symbolication/mod.rs
This adds a "method" tag (for breakpad vs. rust-minidump) to "minidump.stackwalking.iterations" and all metrics in `record_symbolication_metrics`.
> ref(symbolication): tag metrics with stackwalking method

- crates/symbolicator/src/services/download/s3.rs
This set_extra() call already happens just a few lines above, no need
to do this twice.
> ref: Remove duplicate configure sentry scope

- crates/symbolicator/src/services/symbolication/mod.rs
The type of `self.cpu_pool.spawn(lazy.bind_hub(sentry::Hub::current())).await` is `Result<Result<StackwalkMinidumpResult, Error>, JoinError>`. Currently the `?` after the `.await` means that we bail in case of a `JoinError` and attach the "Minidump stackwalk future cancelled" context to the inner `Error`. I think this is exactly backwards; the context should be attached to the `JoinError`.
> fix(symbolication): Attach context to the right error

- crates/symbolicator/src/services/symbolication/mod.rs
Since the previous commit removed the choice between stackwalking methods, this metrics tagging no longer works. Not sure why CI didn't catch that. An alternative would be to just statically tag with `"rust-minidump"`.
> fix: Remove metrics tagging

- .github/workflows/dependabot.yml
To smoothen the dependabot workflow a bit let's try out auto-approving
dependabot PRs.  This means we should be able to merge these PRs
without having to do the, checks notes, 4 clicks this takes.  Already
a massive improvement.
> ci: auto-approve dependabot PRs

- .github/workflows/danger.yml
- dangerfile.js
For plain dependency upgrades that require not changes we normally do
not need any changelog entries.  But not having them fails CI which
renders every dependabot PR a huge hassle.
Sadly we can not customise the dependabot PRs to add a #skip-changelog
marker (see e.g.
https://github.com/dependabot/dependabot-core/issues/2091), so lets
resort to changing the check instead.
There is a risk that someone pushes some changes to such a PR that
does require a changelog.  Hopefully we'll recognise this and do the
right thing anyway.
> ci(danger): Do not require changelogs from dependabot

- CHANGELOG.md
- crates/symbolicator/src/logging.rs
> Don't emit ANSI escape codes with auto=false or simplified logging formats

- crates/symbolicator/src/services/symbolication/process_minidump.rs
This changes the logic for iterative stackwalking so that the loop is also broken if the number of missing modules does not decrease between two iterations.
> ref(minidump): Refine iterative stackwalking logic

- crates/symbolicator/src/services/symbolication/process_minidump.rs
The current behavior of the `fill_symbol` method on `SymbolicatorSymbolProvider` trips [a check](https://github.com/rust-minidump/rust-minidump/blob/7eed71e4075e0a81696ccc307d6ac68920de5db5/minidump-processor/src/stackwalker/mod.rs#L295) in the `instruction_seems_valid_by_symbols` method in `rust_minidump`. This results in stack scanning ending prematurely. Always returning an error instead fixes this.
NATIVE-549
> fix(minidump): fill_symbol always returns an error

- crates/symbolicator/src/services/shared_cache.rs
We expect these errors to some extend and do not need them to be
reported to sentry.  Making sure we can uniquely distinguish them in
our metrics is sufficient.
The crux really is introducing the `CacheError` type and using it in
the reporting inside the service methods themselves.  The rest is just
noisy because we need to coerce all the errors into something that is
an anyhow Error so that the `impl From<anyhow::Error> for CacheError`
(which is derived by thiserror) will actually grab the error
correctly.
I have mixed feelings about this entire thing.  It is a bunch of
complexity simply to work around our product being awkward and
expensive.
> ref(shared-cache): Do not report connect timeouts to sentry

- Cargo.lock
- crates/symbolicator/Cargo.toml
Upgrade rusoto crate, replaces the 3 PRs from dependabot which doesn't
do this as a single thing.
> deps: upgrade rusoto

- Cargo.lock
This lets us make use of https://github.com/rust-minidump/rust-minidump/pull/538, which fixes some stackwalking errors.
> deps: Update rust-minidump to 0.10.4 (ISSUE-1424)

- .github/workflows/danger.yml
- .github/workflows/dependabot.yml
Flip the automation around: auto-merge instead of auto-approve.
Auto-approve doesn't work since the approver is not in owners-ingest.
> ci(dependabot): auto-merge approved PRs

- CHANGELOG.md
- Cargo.lock
- Dockerfile
- crates/symsorter/Cargo.toml
Most notably, this pulls in an updated symbolic that generates better CFI for Win-x64 binaries.
Also updates the Rust version we use for our docker builds.
> deps: Update dependencies and Rust version

- CHANGELOG.md
- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/cache.rs
- crates/symbolicator/src/services/download/sentry.rs
- crates/symbolicator/src/services/il2cpp.rs
- crates/symbolicator/src/services/mod.rs
- crates/symbolicator/src/services/symcaches/markers.rs
- crates/symbolicator/src/services/symcaches/mod.rs
- crates/symbolicator/src/sources.rs
- crates/symbolicator/src/utils/paths.rs
This adds a new `Il2cppService`, modeled after `BitcodeService`, that is responsible for downloading il2cpp line mapping files. `SymCacheActor` can then use these files when generating symcaches.
This PR also contains a drive-by refactoring of path handling logic. The function `get_search_target_object_type` computed an object type from a file type and identifier, which was then used to compute an ID. I removed the indirection in favor of computing the ID from the given
file type and identifier directly.
ETA: This depends upon https://github.com/getsentry/symbolic/pull/592.
> feat: Use il2cpp line mappings in symcache creation

- CHANGELOG.md
- crates/symbolicator/src/endpoints/snapshots/symbolicator__endpoints__applecrashreport__tests__basic.snap
- crates/symbolicator/src/services/symbolication/mod.rs
- crates/symbolicator/src/services/symbolication/process_minidump.rs
- crates/symbolicator/src/services/symbolication/snapshots/symbolicator__services__symbolication__tests__apple_crash_report.snap
- crates/symbolicator/src/types/mod.rs
> feat: Read thread names from minidumps and Apple crash reports

- crates/symbolicator/src/services/cficaches.rs
This syncs up cfi computation to bring it in-line with symcache computation, as bot have pretty much the same code with very little variance between them. But this avoids spawning a task (which is not free) for some early-return conditions such as negative caches.
> ref: Avoid spawning tasks for early-returns

- Cargo.lock
- crates/symbolicator-crash/Cargo.toml
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/services/cficaches.rs
- crates/symbolicator/src/services/symbolication/mod.rs
- crates/symbolicator/src/services/symbolication/process_minidump.rs
- crates/symbolicator/src/services/symbolication/snapshots/symbolicator__services__symbolication__tests__source_candidates.snap
- crates/symbolicator/src/services/symbolication/snapshots/symbolicator__services__symbolication__tests__wasm_payload.snap
- crates/symbolicator/src/services/symcaches/mod.rs
- crates/symbolicator/src/utils/paths.rs
This updates dependencies, most notably symbolic & rust-minidump, which now depend on the updated uuid/debugid.
Also adapts the codebase to the breaking changes in symbolic. Those did result in some changes to test snapshots, most notably the changes to absolute / compdir-relative paths.
> ref: Update deps & Symbolic

- crates/symbolicator/src/services/download/mod.rs
- crates/symbolicator/src/services/download/sentry.rs
- crates/symbolicator/src/services/mod.rs
- crates/symbolicator/src/services/objects/data_cache.rs
- crates/symbolicator/src/services/symcaches/mod.rs
This also avoids passing the Config to the SentryDownloader which previously matched an immutable config flag on every single request. Better to do that ahead of time.
> ref: Avoid holding a Config in the Downloader

- crates/symbolicator/src/services/symbolication/apple.rs
- crates/symbolicator/src/services/symbolication/mod.rs
- crates/symbolicator/src/services/symbolication/process_minidump.rs
- crates/symbolicator/src/services/symbolication/symbolication.rs
This splits the main `symbolication/mod.rs` into smaller modules,
in particular this moves all the apple crash report, and symbolication
specific parts out of the main module which now concerns itself with
request dispatching.
However, each of the modules still includes way too much timeout and metrics-related code/wrappers. We might want to clean those up later as well.
These modules could also use a few more comments explaining the separation.
> ref: Split symbolication module into smaller pieces

- CHANGELOG.md
- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/config.rs
- crates/symbolicator/src/server.rs
- docs/index.md
- tests/integration/conftest.py
The config file format has been extended with a bind_https keyword,
as well as
server_config:
https:
certificate_path: cert.pem
key_path: key.pem
> Add support for serving web requests using HTTPS

- CHANGELOG.md
I accidentally added the HTTPS server changelog entry to the 0.5.1 release entries.
> Move HTTPS server changelog entry to Unreleased

- CHANGELOG.md
Fixes https://github.com/getsentry/symbolicator/issues/847
> meta(changelog): Remove duplicate entry for #838

- crates/symbolicator/src/services/cficaches.rs
- crates/symbolicator/src/services/symcaches/mod.rs
This will trigger lazy re-generation of all the CFI caches, to take advantage of higher fidelity CFI generation for Win-x64 binaries.
This is a separate PR from #822 which actually introduces the CFI changes.
> ref: Increase CFI cache version

- crates/symbolicator/src/services/il2cpp.rs
- crates/symbolicator/src/services/symcaches/mod.rs
- crates/symbolicator/src/utils/paths.rs
This way, the unified symbol source (for example local file system) can use object-type specific formatting for those IDs, as for example PDB debug-ids have an additional age appended.
Though this should not have an effect on the sentry source. It seems like things are being looked up correctly, but the file candidates are not being output.
> fix: Use an ObjectId for il2cpp lookup

- .github/workflows/ci.yml
The setup-python action was removed upstream:
https://github.com/getsentry/sentry/pull/36687
> ci: Update sentry integration test for sentry actions

- CHANGELOG.md
- crates/symbolicator/src/services/symbolication/process_minidump.rs
Previously, we would not even try fetching CFI for modules that have no debug_id, though they could have a code_id that we can look up on an external symbol server, which we now do.
This is the symbolicator followup of https://github.com/getsentry/symbolic/pull/653#issuecomment-1204071737
I also removed the `SymbolProvider::stats`, which is now defaulted by rust-minidump and we never use the output of that function anywhere anyway.
> fix: Fetch/use CFI for modules that only have a CodeId

- local.example.yml
This puts some more useful things into the config example:
A link to where sentry employees can find private symbol servers,
and an example of how to set up upstream sentry as a symbol source,
plus some more useful configuration settings.
> ref: Expand configuration example

- Cargo.lock
- crates/process-event/Cargo.toml
- crates/process-event/src/main.rs
This adds a new `-p`/`-pretty` option that will pretty-print the crashing thread of a processed minidump.
> feat: Pretty-print process-event output

- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/metrics.rs
- crates/symbolicator/src/services/cficaches.rs
- crates/symbolicator/src/services/download/locations.rs
- crates/symbolicator/src/services/download/s3.rs
- crates/symbolicator/src/services/symcaches/markers.rs
- crates/symbolicator/src/services/symcaches/mod.rs
- crates/symbolicator/src/types/mod.rs
Updates insta to the newest version with the `yaml` feature,
and fixes some clippy suggestions.
Clippy still complains over something which looks like a false positive however:
https://github.com/rust-lang/rust-clippy/issues/9309
> fix: Some clippy and insta fixes

- Cargo.toml
Even though feature resolver 2 is the default for rust2021 crates,
it still needs to be opted in explicitly for virtual workspaces.
See https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html#details
for more details.
> fix: Use feature resolver 2

- Cargo.lock
- Cargo.toml
- crates/process-event/Cargo.toml
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/metrics.rs
- crates/symsorter/Cargo.toml
This uses a cargo patch section to replace very specific dependencies, instead of whole dependency trees.
The advantage here is that we can get rid of the log running demangle-branch of symbolic, and rather pull in
a targeted `cpp_demangle` dependency which is a transitive dependency of symbolic.
I also took the liberty to do the same for `reqwest`, which also gets rid of a duplication that previously happened
due to reqwest being pulled in as a transitive dependency from cargo through the sentry SDK.
This also means that we now depend on a *published* version of symbolic, which means we need to publish it more often ;-)
> ref: Avoid git dependencies in favor of cargo patch

- crates/symbolicator/src/services/cficaches.rs
- crates/symbolicator/src/services/symcaches/mod.rs
According to our metrics, we are still falling back to very old cache
versions in some cases, even though we are ~3 weeks in rolling out the
latest version. Removing the fallback version means we are eagerly
creating the latest version whenever an event needs a certain cache.
> ref: Remove fallback cache versions

- Cargo.lock
- crates/process-event/Cargo.toml
- crates/symbolicator/Cargo.toml
- crates/symsorter/Cargo.toml
This includes the following fixes:
- Correctly resolve the `DW_AT_producer` attribute of DWARF files ([#676](https://github.com/getsentry/symbolic/pull/676))
- Improve _sigtramp workaround and explanation ([#662](https://github.com/getsentry/symbolic/pull/662))
- Slightly lower demangling recursion limit ([#655](https://github.com/getsentry/symbolic/pull/655))
> deps: symbolic 9.1.1 -> 9.1.2

- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/endpoints/mod.rs
- crates/symbolicator/src/services/download/gcs.rs
- crates/symbolicator/src/services/download/s3.rs
- crates/symbolicator/src/services/download/sentry.rs
This also disables the new default 2M body limit that axum imposes.
supercedes https://github.com/getsentry/symbolicator/pull/877
> ref: Update dependencies

- Cargo.lock
This should fix some EOF errors due to overeager DWARF `Abbreviations` parsing.
> fix: Bump symbolic to 9.1.4

- CHANGELOG.md
- Cargo.lock
- Dockerfile
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/main.rs
This PR does two things:
- It updates our docker base image from EOL stretch to the current stable bullseye.
- The updated base image also comes with an always up-to-date Rust compiler.
- We also use an up-to-date sentry-cli image, as the previous one did not correctly process the debug files.
- Last but certainly not least, this pulls in jemalloc as global allocater for both Rust code as well as C code (via the `unprefixed_malloc_on_supported_platforms` feature).
So far this has been running on canary for some time and has a considerably lower baseline memory usage (~3G vs ~9G) compared to current master, and does not appear to be leaking memory (updating *just* the base image without jemalloc has slow and steady memory growth over time).
> build: Use bullseye as docker base image & use jemalloc

- CHANGELOG.md
- crates/symbolicator/src/cache.rs
- crates/symbolicator/src/services/cacher.rs
Thus far, the cleanup process never removed empty cache directories. For one, the worklist based approach cleaning the parent before the children, did not make this possible in the first place, but also because normal operations would have errored out on failing FS operations, for example when a directory or file could not be created in a non-existent directory.
This changes the cleanup process to be depth-first, cleaning up empty directories as it goes. It also makes the writing side of things extra defensive and retries FS operations in the unlikely case that a directory is being removed while operating in it.
> ref: Clean up empty cache directories

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/process-event/Cargo.toml
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/services/symcaches/mod.rs
- crates/symsorter/Cargo.toml
- tests/integration/test_basic.py
This does a `cargo update`, pulling in a new symbolic and reqwest.
The updated symbolic contains a new symcache version that now uses a LEB128-prefixed string table.
The patched reqwest was also updated to the latest upstream code.
> ref: Update dependencies, symbolic & reqwest

- CHANGELOG.md
- crates/symbolicator/src/cache.rs
- crates/symbolicator/src/services/cacher.rs
- `check_expiry`/`expiration_strategy` would previously do a redundant open/read that would be later duplicated by an open/mmap anyway, which is now deduplicated.
- The shared cache refresh in `lookup_local_cache` was buggy and was refreshing/uploading caches with the `current` version even if the local cache had an older version.
In a very unscientific stress test, RPS increased from ~2.8k to ~3.4k with lot lower latency.
> fix: Avoid a redundant open/read and fix shared cache refresh

- Dockerfile
The way we do docker layer caching of build dependencies means we have to stub out local workspace crates.
> Add symbolicator-sources to Dockerfile stubs

- Dockerfile
> fix: Correctly copy symbolicator-sources source in Docker

- Dockerfile
Our manual approach to Docker layer caching is annoying and fragile. Cargo chef solves exactly that usecase.
How it works and needs to be used is documented on https://github.com/LukeMathWalker/cargo-chef. We rather `cargo install` it than use the pre-published docker images.
> fix: Use cargo-chef for Docker Layer Caching

- .github/workflows/build.yml
Noticed this error after my latest update PR.
Error: https://github.com/getsentry/symbolicator/actions/runs/3371706410
> Fix typo in build.yml

- crates/symbolicator/src/services/cficaches.rs
- crates/symbolicator/src/services/symcaches/mod.rs
- tests/integration/test_basic.py
A previous bug in the shared cache refresh path could have erroneously uploaded an outdated cache version as a newer (up to date) version. (See https://github.com/getsentry/symbolicator/pull/893)
Now that the shared cache upload/refresh is fixed, this forces another cache refresh. This time files uploaded to and downloaded from shared cache should have the correct version they are advertising.
> ref: Bump CFI/Sym Caches proactively

- Cargo.lock
- crates/symbolicator-stress/Cargo.toml
- crates/symbolicator-stress/src/main.rs
- crates/symbolicator/Cargo.toml
The stress test can run a configurable number of concurrent workloads and can help with benchmarking, stress testing, profiling and finally optimizing symbolicator.
> feat: Create a stress test for symbolicator

- crates/symbolicator-service/src/services/symbolication/apple.rs
- crates/symbolicator-service/src/services/symbolication/mod.rs
- crates/symbolicator-service/src/services/symbolication/process_minidump.rs
- crates/symbolicator-service/src/services/symbolication/symbolication.rs
- crates/symbolicator-stress/src/main.rs
- crates/symbolicator/src/service.rs
Moves the timeouts and metrics for the symbolication tasks into the frontend.
This simplifies the `SymbolicationActor` further, also replacing the `SymbolicationError` with `anyhow::Error`. The frontend still uses the enum to distinguish between timeouts and errors.
The metric names were adapted from the previous implementation, and the both the metrics and the timeouts measure something slightly different now. They now measure (and timeout) the *complete* task, as opposed to parts of it. I believe that especially with regard to the timeouts this is more correct, as previously the stackwalking of a minidump *and* the symbolication of it could both take up to an hour, so two hours in total. Now each task is limited to an hour, no matter of the internal time distribution. Similarly, this …
> ref: Move task measure, timeouts and SymbolicationError to frontend

- CHANGELOG.md
- Cargo.lock
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-service/src/config.rs
- docs/index.md
The config was previously used to control the number of procspawn subprocesses. It is being completely unused since procspawn usage was removed.
> ref: Remove unused `processing_pool_size` config

- Cargo.lock
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-service/src/services/symbolication/process_minidump.rs
This replaces the hand-rolled computation deduplication for CFI caches in `SymbolicatorSymbolProvider` with an async cache from the `moka` crate.
> ref: Use moka in SymbolicatorSymbolProvider

- CHANGELOG.md
- crates/symbolicator-service/src/services/objects/data_cache.rs
- crates/symbolicator-service/src/services/symbolication/module_lookup.rs
- crates/symbolicator-service/src/services/symcaches/mod.rs
- crates/symbolicator-service/src/types/objects.rs
- crates/symbolicator-service/tests/integration/main.rs
- crates/symbolicator-service/tests/integration/process_minidump.rs
- crates/symbolicator-service/tests/integration/source_errors.rs
- crates/symbolicator-service/tests/integration/symbolication.rs
- crates/symbolicator-test/src/lib.rs
- tests/integration/test_basic.py
Adds tests for how various download errors manifest themselves in the frame status and module list.
Also fixes a bug where the candidate info was not correctly retained for malformed symbol files.
> ref: Test outcome of various download errors

- CHANGELOG.md
- crates/symbolicator-service/src/cache.rs
- crates/symbolicator-service/src/config.rs
- crates/symbolicator-service/src/services/download/gcs.rs
- crates/symbolicator-service/src/services/download/mod.rs
- crates/symbolicator-service/src/services/download/s3.rs
- crates/symbolicator-service/src/services/download/sentry.rs
- crates/symbolicator/src/service.rs
Makes a few in-memory caches configurable. Right now thats the Sentry Index, S3 Clients and GCS Tokens.
> ref: Add Configuration options for in-memory Caches.

- crates/symbolicator-service/src/cache.rs
- crates/symbolicator-service/src/services/bitcode.rs
- crates/symbolicator-service/src/services/cacher.rs
- crates/symbolicator-service/src/services/cficaches.rs
- crates/symbolicator-service/src/services/il2cpp.rs
- crates/symbolicator-service/src/services/objects/data_cache.rs
- crates/symbolicator-service/src/services/objects/meta_cache.rs
- crates/symbolicator-service/src/services/ppdb_caches.rs
- crates/symbolicator-service/src/services/symbolication/process_minidump.rs
- crates/symbolicator-service/src/services/symcaches/mod.rs
This removes the now unused `path` param to `CacheItemRequest::load` along with the `CachePath` type. Similarly, it removed the `scope` param as well, as all the `CacheItemRequest` types have it on `self` anyways, and it was unused in most cases. Also simplifies usage of sentry `to_scope`/`configure_scope`.
And lastly, fixes shared cache refreshes which are not happening anymore as the `expiration` was refreshed prior to refreshing the shared cache.
> ref: Load CFI from a ByteView not a CachePath

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/danger.yml
- .github/workflows/release.yml
- .github/workflows/weekly.yml
- Cargo.toml
- Updates all the GHA usages, except `actions-rs/audit-check` which is unmaintained and needs a replacement.
- Changes the rustup invocations to pass --no-self-update as a flag.
- Builds only relevant release artifacts via default-members, which also means we build the symbolicator server on Windows.
> ci: Update workflows and release builds

- README.md
- crates/symbolicator/Cargo.toml
This lists the binaries contained in the symbolicator workspace. It also makes `symbolicator` the default binary so that it can be run with `cargo run` without naming a package.
> docs: Update readme

- crates/symbolicator-service/src/services/bitcode.rs
- crates/symbolicator-service/src/services/download/filesystem.rs
- crates/symbolicator-service/src/services/download/gcs.rs
- crates/symbolicator-service/src/services/download/http.rs
- crates/symbolicator-service/src/services/download/mod.rs
- crates/symbolicator-service/src/services/download/s3.rs
- crates/symbolicator-service/src/services/download/sentry.rs
- crates/symbolicator-service/src/services/il2cpp.rs
- crates/symbolicator-service/src/services/objects/data_cache.rs
This is a first step towards #931.
> ref: Thread a `NamedTempFile` through the `DownloadStatus`

- CHANGELOG.md
- crates/symbolicator-service/src/cache.rs
- crates/symbolicator-service/src/services/cficaches.rs
- crates/symbolicator-service/src/services/derived.rs
- crates/symbolicator-service/src/services/mod.rs
- crates/symbolicator-service/src/services/ppdb_caches.rs
- crates/symbolicator-service/src/services/symbolication/module_lookup.rs
- crates/symbolicator-service/src/services/symbolication/process_minidump.rs
- crates/symbolicator-service/src/services/symcaches/mod.rs
- crates/symbolicator-service/src/types/mod.rs
- crates/symbolicator-service/src/types/objects.rs
Introduces a new helper to deduplicate code related to deriving cache files from object meta handles.
Also cleans up some intermediate types and duplicated functions.
> ref: Refactor fetching/computing derived Cache

- CHANGELOG.md
- crates/symbolicator/src/cli.rs
Seems like our `symbolicator-crash` (`sentry-native`) integration was never active because it required explicitly setting a crash db path which was not configured for our deployed version.
This will now use a `.sentry-native` folder inside our configured (or defaulted for docker) cache directory.
> fix: Use a default crash DB if we have a Cache configured

- crates/symbolicator-service/src/services/bitcode.rs
- crates/symbolicator-service/src/services/download/filesystem.rs
- crates/symbolicator-service/src/services/download/gcs.rs
- crates/symbolicator-service/src/services/download/http.rs
- crates/symbolicator-service/src/services/download/mod.rs
- crates/symbolicator-service/src/services/download/s3.rs
- crates/symbolicator-service/src/services/download/sentry.rs
- crates/symbolicator-service/src/services/il2cpp.rs
- crates/symbolicator-service/src/services/objects/mod.rs
- crates/symbolicator-sources/src/remotefile.rs
- Moves `SourceLocationIter` into `symbolicator-sources`.
- Probes all the sources in the `DownloadService`, avoiding a `join_all`.
- Clean up error handling for the `SentrySource`.
- Deduplicate per-source fetching and error handling in the bitcode / il2cpp service.
> ref: Simplify `list_files`

- crates/symbolicator-service/src/cache.rs
- crates/symbolicator-service/src/services/cacher.rs
- crates/symbolicator-service/src/services/derived.rs
- crates/symbolicator-service/src/services/download/mod.rs
- crates/symbolicator-service/src/types/objects.rs
Teaches the `CacheError` to read and write legacy markers, and replace all former usages of `CacheStatus`.
> ref: Replace last `CacheStatus` usages with `CacheEntry`

- crates/symbolicator-service/src/cache.rs
- crates/symbolicator-service/src/services/cficaches.rs
- crates/symbolicator-service/src/services/derived.rs
- crates/symbolicator-service/src/services/download/filesystem.rs
- crates/symbolicator-service/src/services/download/gcs.rs
- crates/symbolicator-service/src/services/download/http.rs
- crates/symbolicator-service/src/services/download/mod.rs
- crates/symbolicator-service/src/services/download/s3.rs
- crates/symbolicator-service/src/services/download/sentry.rs
- crates/symbolicator-service/src/services/fetch_file.rs
- crates/symbolicator-service/src/services/objects/data_cache.rs
- crates/symbolicator-service/src/services/ppdb_caches.rs
- crates/symbolicator-service/src/services/symcaches/mod.rs
- crates/symbolicator-service/src/utils/futures.rs
- crates/symbolicator-service/tests/integration/e2e.rs
- crates/symbolicator-service/tests/integration/source_errors.rs
Also deduplicates a bunch of downloader code that matches on response statuses.
Fixes https://github.com/getsentry/symbolicator/issues/930.
> ref: Remove `DownloadError` in favor of `CacheError`

- crates/symbolicator-service/src/services/bitcode.rs
- crates/symbolicator-service/src/services/cacher.rs
- crates/symbolicator-service/src/services/cficaches.rs
- crates/symbolicator-service/src/services/download/mod.rs
- crates/symbolicator-service/src/services/fetch_file.rs
- crates/symbolicator-service/src/services/il2cpp.rs
- crates/symbolicator-service/src/services/objects/data_cache.rs
- crates/symbolicator-service/src/services/objects/meta_cache.rs
- crates/symbolicator-service/src/services/ppdb_caches.rs
- crates/symbolicator-service/src/services/symcaches/mod.rs
- crates/symbolicator-service/src/utils/compression.rs
Instead of taking and returning a `NamedTempFile`, rather take a `&mut NamedTempFile`, together with `std::mem::swap` in case we create new files. This avoids creating a new file in the hot error (not found) case.
> ref: Make the cacher work with a `&mut NamedTempFile`

- Dockerfile
Oh the irony, https://github.com/getsentry/symbolicator/pull/928 (CC @mattgauntseo-sentry @asottile-sentry) should have added a check that prevents us from breaking our internal cloudbuild. But that very PR broke the internal cloud build, and noone noticed because the cloudbuild status is not exposed anywhere.
Can we expose the cloud build status here in github for master/release branches? Its not necessary to have it for PRs I guess, as long as master is red, people will notice.
> fix: Do not error Docker build on existing /data dir

- .vscode/extensions.json
- docs/index.md
Just a minor cleanup to make markdown render correct indentations. 
> docs: Fix docs rendering and update vscode recommendations

- CHANGELOG.md
- crates/symbolicli/README.md
- crates/symbolicli/src/main.rs
- crates/symbolicli/src/settings.rs
The main use case for this is debugging customer minidumps where attempting to access the Sentry server would just lead to nonstop errors.
> feat(symbolicli): Add offline mode

- Cargo.lock
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-service/src/utils/gcs.rs
> feat: Removes an unused dependency of symbolicator-service

- crates/symbolicator-service/src/cache.rs
- crates/symbolicator-service/src/services/symbolication/process_minidump.rs
It might seem that some concurrent `Hub`/`Scope` access can potentially deadlock.
The PR that originally removed the `bind_hub` was https://github.com/getsentry/symbolicator/pull/933, and we bisected a deadlock in canary deployments to that PR. This PR here that adds back that `bind_hub` is running stably so far for longer time than it took for the non-`bind_hub` version to eventually deadlock.
Also micro-optimizes candidate merge and sprinkles some `#[track_caller]` annotations.
> fix: Add back a `bind_hub` for concurrent CFI access

- crates/symbolicator-service/src/services/download/s3.rs
- crates/symbolicator-service/src/types/mod.rs
- crates/symbolicator-service/src/utils/addr.rs
- crates/symbolicator-service/tests/integration/e2e.rs
- crates/symbolicator-sources/src/sources.rs
- crates/symbolicator-sources/src/sources/s3.rs
- crates/symbolicator-sources/src/types.rs
- crates/symbolicator-test/src/lib.rs
- crates/symbolicator/src/endpoints/requests.rs
Clippy now has an auto-fixable lint to use `#[derive(Default)]` and use `#[default]` on enums.
> fix: Apply clippy lints

- crates/symbolicator-service/src/cache.rs
- crates/symbolicator-service/src/services/cacher.rs
- crates/symbolicator-test/src/lib.rs
We have a steady stream of cache fallbacks since a while which has been baffling me.
I suspect these happen because:
- we have an older cache version to use
- when regenerating the cache, the file can not be found anymore and a `NotFound` marker is written
- the `NotFound` marker was previously always skipped, falling back to the old cache version
Apart from fixing and testing this edge case, this also simplifies the cache versioning code a bit.
> fix: Correctly treat `NotFound` in terms of cache fallback

- .codecov.yml
- .github/workflows/ci.yml
Looks like I never committed the `.codecov.yml` file that makes codecov a lot less annoying :-)
This copies that file from other repos that have the same config, as well as updating the action to the latest version.
> Add codecov.yml and update action

- crates/symbolicator-service/src/services/bitcode.rs
- crates/symbolicator-service/src/services/cacher.rs
- crates/symbolicator-service/src/services/cficaches.rs
- crates/symbolicator-service/src/services/il2cpp.rs
- crates/symbolicator-service/src/services/mod.rs
- crates/symbolicator-service/src/services/objects/data_cache.rs
- crates/symbolicator-service/src/services/objects/mod.rs
- crates/symbolicator-service/src/services/ppdb_caches.rs
- crates/symbolicator-service/src/services/shared_cache.rs
- crates/symbolicator-service/src/services/symcaches/mod.rs
- crates/symbolicator-service/tests/integration/e2e.rs
- crates/symbolicator-service/tests/integration/process_minidump.rs
- crates/symbolicator-service/tests/integration/source_errors.rs
- crates/symbolicator-service/tests/integration/symbolication.rs
- crates/symbolicator-stress/src/main.rs
- crates/symbolicator/src/endpoints/applecrashreport.rs
- crates/symbolicator/src/endpoints/minidump.rs
- crates/symbolicator/src/endpoints/requests.rs
- crates/symbolicator/src/endpoints/symbolicate.rs
- crates/symbolicator/src/main.rs
- crates/symbolicator/src/server.rs
- crates/symbolicator/src/service.rs
- crates/symbolicli/src/main.rs
This avoids some internal indirection and locking, and makes a couple of function non-async, such as the service startup path.
> ref: Use a OnceCell instead of async RwLock in Shared Cache

- crates/symbolicator-service/src/services/bitcode.rs
- crates/symbolicator-service/src/services/cache_key.rs
- crates/symbolicator-service/src/services/cacher.rs
- crates/symbolicator-service/src/services/il2cpp.rs
- crates/symbolicator-service/src/services/mod.rs
- crates/symbolicator-service/src/services/objects/meta_cache.rs
- crates/symbolicator-service/src/services/shared_cache.rs
This is a preliminary refactor moving us a bit closer towards #983:
Adds a different constructor to `CacheKey` and makes it use `String` internally instead of `PathBuf`.
The goal here is that it should make it simpler to move us towards to just use opaque paths/strings for these cache files.
The problem is also that we have different permutations of names:
- For the `Cacher`, the `cache_dir` already includes the `CacheName`, so the `cache_path` added on top does not need it.
- However for the `SharedCache`, the `CacheName` needs to be prepended directly. The shared cache needs the `CacheName` parameter anyway for reasons, so we might as well reuse the same cache key and just prepend the cache name in the shared cache abstraction?
So we end up with the different cases (where `key` = …
> ref: Move `CacheKey` into its own file

- CHANGELOG.md
- crates/symbolicator-service/src/services/cache_key.rs
- crates/symbolicator-service/src/services/cacher.rs
- crates/symbolicator-service/src/services/download/sentry.rs
- crates/symbolicator-service/src/services/objects/data_cache.rs
- crates/symbolicator-service/src/services/symbolication/process_minidump.rs
- crates/symbolicator-service/src/services/symcaches/mod.rs
- crates/symbolicator-service/src/types/mod.rs
This reverts commit ff40e2ca794315986bb87d6e538ba9af754deb7b.
Looks like this is leading to deadlocks in canary. Though the deadlock is only hit ~50 minutes into operation, so might be more difficult to track down than last time :-(
> Revert "ref: Use `moka` for `Cacher` implementation (#979)"

- CHANGELOG.md
- crates/symbolicator-service/src/services/download/http.rs
- crates/symbolicator-service/src/services/download/mod.rs
- crates/symbolicator-service/src/services/symbolication/apple.rs
- crates/symbolicator-service/src/services/symbolication/mod.rs
- crates/symbolicator-service/src/services/symbolication/module_lookup.rs
- crates/symbolicator-service/src/services/symbolication/process_minidump.rs
- crates/symbolicator-service/src/types/mod.rs
- crates/symbolicator-service/tests/integration/snapshots/integration__symbolication__nuget_file.snap
- crates/symbolicator-service/tests/integration/symbolication.rs
- crates/symbolicator-sources/src/paths.rs
- crates/symbolicator-sources/src/sources/http.rs
- crates/symbolicator-sources/src/types.rs
- crates/symbolicator-test/src/lib.rs
- crates/symbolicator/src/service.rs
Adds the `SymbolChecksum` header to HTTP sources if the `ObjectId` has a `debug_checksum` field. Also properly passes through that `debug_checksum` field from the incoming modules definition.
This is still lacking proper tests, for which we would need an event that uses some .NET library that has symbols available on nuget. I suggest we do a proper integration test fetching things from upstream, as the upstream server at least checks for the presence of the header (even though it does not *yet* check the actual checksum, lol).
Apart from this, we should also make sure that the `debug_checksum` field is correctly passed through from sentry itself, and maybe also add the NuGet server as a builtin source in sentry, because why not…
> fix: Properly support NuGet symbols with SymbolChecksum

- crates/symbolicator-service/tests/integration/e2e.rs
- crates/symbolicator-service/tests/integration/main.rs
- crates/symbolicator-service/tests/integration/process_minidump.rs
- crates/symbolicator-service/tests/integration/public_sources.rs
- crates/symbolicator-service/tests/integration/snapshots/integration__public_sources__nuget_source.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__public_sources__ubuntu_source.snap
- crates/symbolicator-service/tests/integration/source_errors.rs
- crates/symbolicator-service/tests/integration/symbolication.rs
- crates/symbolicator-service/tests/integration/utils.rs
- crates/symbolicator-test/src/lib.rs
- Creates a `utils` module that re-exports relevant things from `symbolicator_test`, and is itself re-exported from the root.
- Simplifies creating symbolication requests a bit.
- Moves tests for external public symbol servers to its dedicated file.
> ref: Improve Integration Tests a bit

- docs/advanced/symbol-server-compatibility.md
The docs claim that we support fetching Macho files from `debuginfod` symbol sources, but given https://github.com/getsentry/symbolicator/blob/ddf55813bb3ce01a5285a58539cfb9b1c5a138de/crates/symbolicator-sources/src/paths.rs#L316 this is clearly not the case.
> doc: Correct supported formats for debuginfod

- crates/symbolicator-service/src/services/download/gcs.rs
- crates/symbolicator-service/src/services/download/s3.rs
- crates/symbolicator-service/src/services/download/sentry.rs
- crates/symbolicator-service/src/services/symbolication/process_minidump.rs
- crates/symbolicator-service/src/services/symcaches/mod.rs
We can extract this from #1010, and this should help with https://github.com/moka-rs/moka/issues/212 even if we do not (yet) switch to more widespread moka usage.
> ref: Box::pin all the moka init Futures

- crates/symbolicator-service/src/services/bitcode.rs
- crates/symbolicator-service/src/services/cficaches.rs
- crates/symbolicator-service/src/services/download/mod.rs
- crates/symbolicator-service/src/services/il2cpp.rs
- crates/symbolicator-service/src/services/objects/data_cache.rs
- crates/symbolicator-service/src/services/ppdb_caches.rs
- crates/symbolicator-service/src/services/symcaches/mod.rs
- crates/symbolicator-service/src/utils/futures.rs
- crates/symbolicator-sources/src/remotefile.rs
- crates/symbolicator/src/service.rs
This removes a couple of tags that I don’t believe anyone has every looked at (certainly I haven’t), and which are also not used anywhere in DD.
The `source.download.X` metrics are tagged with the source type (or rather `source_metric_key`) already and are being displayed in a dashboard which should be the source of truth for download related metrics.
I also question the usefulness of the `futures::measure` metrics in general. We use sentry performance monitoring for these as well through `tracing::instrument` which might be a much better way to look at these things in general.
> ref: Reduce cardinality of `futures::measure` metrics

- crates/symbolicli/Cargo.toml
> fix: Remove version numbers from symbolicli deps

- crates/symbolicator-service/src/caching/cleanup.rs
- crates/symbolicator-service/src/caching/config.rs
- crates/symbolicator-service/src/caching/mod.rs
- crates/symbolicator-service/src/services/mod.rs
- crates/symbolicator-service/src/services/sourcemap.rs
- crates/symbolicator-service/src/services/symbolication/sourcemap.rs
So far this only copy-pastes all the relevant infrastructure. (Which we should refactor in such a way that it does not require us to copy-paste tons of boilerplate code)
It is still using a temp_file that we throw away after each use for the time being.
> ref: Add a skeleton `Cacher` for SourceMaps

- CHANGELOG.md
- crates/symbolicator-service/src/caching/cache_key.rs
- crates/symbolicator-service/src/caching/memory.rs
- crates/symbolicator-service/src/services/objects/data_cache.rs
- crates/symbolicator-service/src/services/symbolication/process_minidump.rs
- crates/symbolicator-service/src/types/mod.rs
Reopens https://github.com/getsentry/symbolicator/pull/979:
Replaces the current request coalescing solution with `moka`. This simplifies the channel creation and deduplication logic, as `moka` does that already. This also gives us in-memory caches right now, even though they are not hooked up to configuration yet.
Just opening this for now that its not lost
> ref: Use `moka` for `Cacher` implementation, 2nd try

- crates/symbolicator-service/src/caching/memory.rs
- crates/symbolicator-service/src/caching/mod.rs
This also adds explicit cache metrics for things that could in theory be derived from other metrics, but would then depend on the presence of optional services.
> ref: Document cache metrics

- crates/symbolicator-service/src/services/sourcemap.rs
- crates/symbolicator-service/src/services/symbolication/sourcemap.rs
- crates/symbolicator-service/src/types/mod.rs
First of all, this moves the `collect_stacktrace_artifacts` function and assorted helper functions into the `SourceMapService`.
Second of all, it introduces a new enum `JsProcessingFrameStatus` that is analogous to `FrameStatus` but for Javascript frames. The variants of `FrameStatus` don't really map too well to the problems that can occur during JS symbolication.
Third of all, it makes `js_processing_symbolicate_frame` return the new enum in the error case.
> ref: Error handling in JS symbolication

- Cargo.lock
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-service/src/caching/memory.rs
- crates/symbolicator-service/src/services/download/gcs.rs
- crates/symbolicator-service/src/services/download/s3.rs
- crates/symbolicator-service/src/services/download/sentry.rs
Updates `moka` to `0.10`, and switches to using the entry API in some places.
> ref: Update deps, in particular moka

- CHANGELOG.md
- crates/symbolicator-service/src/caching/memory.rs
- crates/symbolicator-service/src/services/bitcode.rs
- crates/symbolicator-service/src/services/caches/mod.rs
- crates/symbolicator-service/src/services/caches/versions.rs
- crates/symbolicator-service/src/services/cficaches.rs
- crates/symbolicator-service/src/services/il2cpp.rs
- crates/symbolicator-service/src/services/mod.rs
- crates/symbolicator-service/src/services/objects/data_cache.rs
- crates/symbolicator-service/src/services/objects/meta_cache.rs
- crates/symbolicator-service/src/services/objects/mod.rs
- crates/symbolicator-service/src/services/ppdb_caches.rs
- crates/symbolicator-service/src/services/sourcemap.rs
- crates/symbolicator-service/src/services/symcaches/mod.rs
- crates/symbolicator-service/tests/integration/e2e.rs
Moves all the places that define `CacheVersions` into a central place, and makes it mandatory to specify explicit versions.
It also bumps some cache versions, to start lazy recomputation of some of our caches to the new `CacheKey` format, specifically: Bitcode, Il2cpp, PortablePDB, and Objects.
CFI, SymCache and Meta caches in turn depend on other categories, and will be bumped once the first categories have been migrated.
> ref: Consolidate `CacheVersions`

- CHANGELOG.md
- crates/symbolicator-service/src/services/caches/versions.rs
Bumps the versions of all the derived caches to trigger lazy recomputation. That recomputation will then make sure newly written caches use the "new" `CacheKey`s.
lets wait till tomorrow morning to land this :-)
> ref: Bump derived `CacheVersions`

- Cargo.lock
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-service/src/services/download/mod.rs
This adds logging for when a download failure is registered for a host, as well when a host is added to or removed from the deny list. Currently the former is at `trace`, while the latter two are at `info`. Do these levels make sense? I think the adding one could be increased to `warn`.
> feat: Add logging to deny list

- crates/symbolicator-service/src/services/symbolication/sourcemap.rs
Translated from https://github.com/getsentry/sentry/blob/abdfcfdaf0f2e16db06b5348bb80a0f4e268455e/src/sentry/lang/javascript/processor.py#L89-L121
and https://github.com/getsentry/sentry/blob/abdfcfdaf0f2e16db06b5348bb80a0f4e268455e/tests/sentry/lang/javascript/test_processor.py#L1192-L1216
> ref: Add trim_context_line for sourcemap processing

- CHANGELOG.md
- crates/symbolicator-service/src/services/minidump.rs
- crates/symbolicator-service/src/services/symbolication/process_minidump.rs
This checks minidumps for invalid `code_file` and `debug_file` strings in modules before attempting to process them. "Invalid" here means that the name contains a control character or is longer than 255 bytes.
It also moves minidump parsing, which currently happens twice in `stackwalk` and `parse_stacktraces_from_minidump`, one level up to `stackwalk_minidump`.
The minidump parsing is wrapped in an individual call to `maybe_persist_minidump`, but I don't know if we actually want to persist the file if we fail to open or parse it.
> fix: Reject minidumps with invalid file names

- CHANGELOG.md
- crates/symbolicator-service/src/caching/fs.rs
- crates/symbolicator-service/src/caching/memory.rs
- crates/symbolicator-service/src/caching/mod.rs
- crates/symbolicator-service/src/caching/tests.rs
- crates/symbolicator-service/src/config.rs
- crates/symbolicator-service/src/services/cficaches.rs
- crates/symbolicator-service/src/services/objects/data_cache.rs
- crates/symbolicator-service/src/services/symcaches.rs
- crates/symbolicator-service/tests/integration/e2e.rs
- crates/symbolicator-service/tests/integration/source_errors.rs
Fixes https://github.com/getsentry/symbolicator/issues/994 by adding the infrastructure and defaults for in-memory caching.
This implements weighing of cache items (based on a bunch of `size_of`s),
and per-item TTL based on the `ExpirationTime`.
Each cache defaults to ~100k in-memory size, which should be roughly ~1k items.
Except for `object_meta` which defaults to ~100M in-memory and is very hot,
and `cficaches` which defaults to ~400M and are expensive to parse, with variable per-item weight.
> feat: Add support for in-memory caching

- crates/symbolicator-service/src/caching/config.rs
- crates/symbolicator-service/src/caching/fs.rs
- crates/symbolicator-service/src/caching/memory.rs
- crates/symbolicator-service/src/caching/mod.rs
- crates/symbolicator-service/src/caching/tests.rs
- crates/symbolicator-service/src/config.rs
- crates/symbolicator-service/src/services/objects/data_cache.rs
- Increases the in-memory defaults a bit
- Cleans up the buggy `expiration_strategy` handling
- Remove a footgun from cache configuration
- Add more docs to the caching infrastructure
> ref: More docs and Cach cleanups

- crates/symbolicator-service/src/services/symbolication/mod.rs
- crates/symbolicator-service/src/services/symbolication/sourcemap.rs
- crates/symbolicator-service/src/types/mod.rs
- crates/symbolicator-service/tests/integration/sourcemap.rs
- crates/symbolicator/src/endpoints/sourcemap.rs
- crates/symbolicator/src/service.rs
The first commit introduces some changes in naming, specifically:
```
JsProcessingRawFrame => JsProcessingFrame
JsProcessingRawStacktrace => JsProcessingStacktrace
CompleteJsStacktrace => JsProcessingSymbolicatedStacktrace
```
So for JS processing, we now have:
```
JsProcessingFrame {}
JsProcessingSymbolicatedFrame {}
JsProcessingFrameStatus {}
JsProcessingStacktrace {}
JsProcessingSymbolicatedStacktrace {}
JsProcessingCompletedSymbolicationResponse {}
```
As for the `raw_stacktrace` passthrough, there's now `frame.status`, `frame.raw` and `frame.processed` attributes, where `raw` and `processed` are clones of the original frame.
I'm not tied to that name though, and other proposals are `frame.symbolicated` or `frame.changed`, I don't mind either.
This makes all commented-out assertions …
> ref: Apply source context to raw frames as the initial processing step

- Cargo.lock
- crates/process-event/Cargo.toml
- crates/symbolicator-crash/Cargo.toml
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-service/src/services/module_lookup.rs
- crates/symbolicator-sources/Cargo.toml
- crates/symbolicator/Cargo.toml
- crates/symbolicli/Cargo.toml
- crates/symsorter/Cargo.toml
This updates symbolic to a version that has `SourceFileDescriptor`s.
CC @vaind you can update your #1034 once this lands. In the meantime I will work on a generic "file download" cache.
> ref: Update dependencies including symbolic

- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-service/src/services/symbolication/js.rs
Hook up the new infra to sourcemap processing, moving it away from a heavily batched / parallelizes approach to a more straight-line code approach.
Files are fetched as-needed, which was already the case previously as needed for applying source context from individual files.
> Un-batch SourceMap processing

- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__indexed_sourcemap_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__inlined_sources.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_embedded_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_nofiles_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_source_expansion.snap
- crates/symbolicator-service/tests/integration/sourcemap.rs
- crates/symbolicator-service/tests/integration/symbolication.rs
- crates/symbolicator-test/src/lib.rs
- Adds a helper fn to create symbolication requests
- Uses snapshots to simplify assertion
> Simplify SourceMap tests

- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-service/src/services/symbolication/js.rs
- crates/symbolicator-service/src/types/mod.rs
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__malformed_abs_path.snap
This introduces a new ~`MissingSource`~`InvalidAbsPath` variant of the `JsFrameStatus` enum and returns it in the appropriate place. If parsing the abs_path returns an error, we log this at level `warn`.
Also drive-by fixes a docstring.
> ref: Create InvalidAbsPath js frame status

- crates/symbolicator-service/src/services/download/mod.rs
We were checking the `host` for the `"sentry:"` prefix, not the `source_metric_key` as we should have.
lol 🤦🏻‍♂️ 
> Fix host blocking to correctly allow-list sentry sources

- CHANGELOG.md
- crates/symbolicli/README.md
- crates/symbolicli/src/main.rs
- crates/symbolicli/src/settings.rs
This adds a `--log-level` argument to `symbolicli` that controls its log level, replacing the use of the `RUST_LOG` environment variable. All log output that does not originate from `symbolicli` or `symbolicator_service` will be suppressed, regardless of log level.
> ref: Add --log-level argument to symbolicli

- Cargo.lock
- crates/process-event/Cargo.toml
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-service/src/services/caches/versions.rs
- crates/symbolicator-sources/Cargo.toml
- crates/symbolicator-test/Cargo.toml
- crates/symbolicator-test/src/lib.rs
- crates/symbolicator/Cargo.toml
- crates/symbolicli/Cargo.toml
- crates/symsorter/Cargo.toml
- crates/wasm-split/Cargo.toml
- crates/wasm-split/src/main.rs
- Does a `cargo update`
- Bumps the PortablePDB cache version to refresh caches with skipped hidden SequencePoints
- Smaller changes related to updated `tower-http` and `wasmbin`.
> ref: Update dependencies, bump PortablePDB Cache version

- crates/symbolicator-service/src/services/module_lookup.rs
- crates/symbolicator-service/src/services/symbolication/js.rs
- crates/symbolicator-service/src/services/symbolication/mod.rs
- crates/symbolicator-service/src/services/symbolication/source_context.rs
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__indexed_sourcemap_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__inlined_sources.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_embedded_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_nofiles_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__symbolication__dotnet_embedded_sources.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__symbolication__source_candidates.snap
This now uses the same code for native and JS source context, which now works with `&str`, and makes it generic over line trimming and number of context lines.
It also avoids outputting a trailing empty line when there is a trailing lineline in JS files.
Fun fact: The source-context application for native was broken since forever basically. Due to an off-by-one, it would only ever give us 4 lines of `pre_context`.
> ref: Unify Source Context application

- crates/symbolicator-service/src/services/sourcemap.rs
- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-service/src/services/symbolication/js.rs
This removes the `create_sourcemap_lookup` method from `SourceMapService` and changes the signature of `SourceMapLookup::new` to
```rust
pub fn new(service: SourceMapService, request: SymbolicateJsStacktraces) -> Self
```
Since the `request`'s `stacktraces` field is not needed by `new`, we `take` it out before calling `new`.
The `ArtifactFetcher::new` function is removed entirely; inlining it into the one place where it was called should be fine.
During the refactoring a question occurred to me: where do we actually use the `dist` field on `SymbolicateJsStacktraces`?
> ref: Restructure construction of SourceMapLookup

- crates/symbolicator-service/src/caching/mod.rs
The lowers the number of mmap-ed items in cache and clarifies some comments.
> ref: Tune in-memory cache defaults

- Dockerfile
Turns out that our usage of `--only-keep-debug` meant that our debug file never included unwind info (even though symbolicator claims it does?). That meant that we could not properly unwind minidumps.
> ref: Keep the full executable as `.debug`

- Cargo.toml
It is certainly nice to be able to run a debugger on tests. This also gives a recommendation to use the faster lld linker.
> ref: Turn on debuginfo in dev mode

- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-service/src/services/symbolication/js.rs
- crates/symbolicator-service/src/types/mod.rs
- crates/symbolicator-test/Cargo.toml
- crates/symbolicator-test/src/lib.rs
- crates/symbolicator/src/endpoints/mod.rs
Just random chores. Removed unused TODOs, added `(sourcemap)` to remaining one and added fixture tracing for sourcemap tests.
> ref: Cleanup some TODOs comments and add trace logging to test server

- crates/symbolicator-service/src/services/bitcode.rs
- crates/symbolicator-service/src/services/il2cpp.rs
- crates/symbolicator/src/cli.rs
- Increases our transactions sampling rate, fixes #1021.
- Avoids raising internal errors for il2cpp/bitcode fetches. Over all the time we had this error in there, we only ever got `PermissionDenied`.
> ref: Sample more transactions, ignore more errors

- crates/symbolicator-service/src/services/caches/sourcefiles.rs
- crates/symbolicator-service/src/services/mod.rs
- crates/symbolicator-service/src/services/objects/meta_cache.rs
- crates/symbolicator-service/src/services/sourcemap.rs
- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-sources/src/sources/http.rs
So far this creates the code to query and fetch Individual Artifacts or Bundles from an imaginary not yet existing Sentry API.
This is half the code needed for https://github.com/getsentry/symbolicator/issues/1067.
> feat: Prepare to fetch ArtifactBundles from Sentry

- crates/symbolicator/src/cli.rs
Symbolicator currently gets HTTP requests that just spawn the real work. However our custom traces sampler did not really look at that and was thus double-sampling the "real" tasks.
See: https://sentry.my.sentry.io/organizations/sentry/performance/?project=5&query=&referrer=performance-transaction-summary&statsPeriod=24h&unselectedSeries=p100%28%29
> ref: Fix double-sampling of transactions

- crates/symbolicator-service/src/services/download/mod.rs
- crates/symbolicator-service/src/services/download/sentry.rs
- crates/symbolicator-service/src/services/sourcemap_lookup.rs
This should make it work for projects with thousands and thousands of release files, without making tens of hundreds of requests to prefetch release files metadata.
> ref: Use API query param to prefilter release artifact files

- crates/symbolicator-service/src/services/download/gcs.rs
- crates/symbolicator-service/src/services/download/s3.rs
- crates/symbolicator-service/src/services/download/sentry.rs
The various in-memory caches of Downloaders (Sentry Searches, GCS Tokens, S3 Clients) now have streamlined metrics.
> ref: Streamline downloader-related metrics

- crates/symbolicator-service/src/services/download/sentry.rs
- crates/symbolicator-service/src/services/objects/data_cache.rs
Removes instrumentation from `fetch_object_file`, which calls out to `fetch_file` which is already instrumented. Also adds intrumentation to `fetch_sentry_json`, which calls out to the external Sentry API which is linked via the trace but was not explicitly measured in symbolicator itself.
This should improve this view a bit:
> Micro-optimize Sentry Spans

- crates/symbolicator-service/src/services/symcaches.rs
The performance span view was showing nested `fetch_sentry_json` spans, even though that is impossible.
I suspect the problem was with missing future isolation for the bcsymbolmap / il2cpp requests. The first request would call into `fetch_sentry_json` and yield, after which the second future is polled and will then end up as the child of the first one.
> Fix `fetch_sentry_json` Span nesting

- crates/symbolicator-service/src/services/download/sentry.rs
- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-service/src/services/symbolication/js.rs
- crates/symbolicator-sources/src/sources/sentry.rs
Its a bit annoying that the `Debug` output of `Url` is pretty useless :-(
> Add a bunch of trace logs to JS symbolication

- crates/symbolicator-service/src/services/sourcemap_lookup.rs
ref: https://github.com/getsentry/sentry/blob/02bf7f0df65bd662a4caca0c4e53aa281aea1488/src/sentry/models/releasefile.py#L122-L144
> fix: Use correct urls order in get_release_file_candidate_urls

- crates/symbolicator-service/src/types/mod.rs
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__invalid_location.snap
We'll map it on the other side in the monolith.
> ref: Dont rename InvalidLocation fields

- Cargo.lock
- crates/process-event/src/main.rs
- crates/symbolicator-service/src/services/bitcode.rs
- crates/symbolicator-service/src/services/symbolication/apple.rs
- crates/symbolicator-service/src/services/symbolication/js.rs
- crates/symbolicator-service/src/services/symbolication/mod.rs
- crates/symbolicator-service/src/services/symbolication/process_minidump.rs
- crates/symbolicator-stress/src/main.rs
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/service.rs
- crates/symbolicli/src/main.rs
- crates/symbolicli/src/settings.rs
- crates/wasm-split/src/main.rs
This makes sure that when capturing a Symbolication Error, we do get a proper stack trace and chained errors for it. Also cleans up some general anyhow usage across the codebase.
> Clean up anyhow usage and Symbolication Error reporting

- crates/symbolicator-service/src/services/symbolication/mod.rs
Demangling can be an expensive operation, which also happens for every frame and is not deduplicated for the same function names shared across threads. Furthermore, we capture errors for demangling failures, to eventually be able to improve those. However we are being spammed with up to 8 of those errors a second, and they are highly duplicated too, making it difficult to actually find new cases we don’t handle yet.
So lets cache all the things, to avoid duplicated work and spamming S4S events.
The change to `get_relative_caller_addr` is a driveby refactoring as clippy was rightfully complaining about too many fn arguments.
> Cache the result of Demangling

- crates/symbolicator-service/src/services/sourcemap_lookup.rs
We were running into an error in `Url::parse`, because the descriptor `url` is a relative one (aka `~/foo/bar.js`) in most cases, and we need a real *absolute* Url in order to resolve the `sourceMappingURL` reference.
> Use the absolute `abs_path` when resolving Descriptor sourceMappingURLs

- crates/symbolicator-service/tests/integration/public_sources.rs
According to the FAQ at https://ubuntu.com/server/docs/service-debuginfod-faq:
> Once a release goes unsupported, we [...] eventually stop serving debug symbols for its packages.
So I guess with those "stability" guarantees we either have to constantly update the testcase with up-to-date debug-ids, or we just skip it entirely :-(
> Skip Ubuntu symbol server test

- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-service/src/services/symbolication/js.rs
- crates/symbolicator-service/src/types/mod.rs
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__fetch_error.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_embedded_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_source_expansion.snap
This change prevents errors about missing sources for events that should not report one.
When we have a frame that points to a valid JS file but has no `sourceMappingUrl` nor a Debug ID, we shouldn't treat it as an error.
We should also bail from further processing when the initial context lines application fails, as it means that minified source (which is required for creating a `SourceMapCache` in the first place) is not present or is not usable.
> ref(sourcemaps): Make SourceMapCache optional for Module and bail early on processing

- crates/symbolicator-service/src/services/symbolication/mod.rs
A followup to this review comment: https://github.com/getsentry/symbolicator/pull/1124#pullrequestreview-1373197774
> Propagate relative_caller_addr Errors

- CHANGELOG.md
- Cargo.lock
- crates/symbolicator-service/src/services/symbolication/process_minidump.rs
- crates/symbolicator-sources/src/paths.rs
- crates/symbolicator-sources/src/types.rs
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/service.rs
Invalid base-names will be excluded from symbol server lookups, which will certainly not find anything useful. We still output the full (invalid) code file into the symbolicated event, as it might still be useful to customers.
As a drive-by change, this reverts the `capture_anyhow` change that captures real stack traces in S4S, as the stack traces are not that useful, and the grouping is worse.
fixes https://github.com/getsentry/symbolicator/issues/1115, and I verified the minidump linked in https://github.com/getsentry/sentry/issues/46231 processes fine after this change.
> Do not fail processing minidumps on invalid `code_file`

- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-service/src/services/symbolication/js.rs
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__indexed_sourcemap_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__inlined_sources.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_embedded_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_source_expansion.snap
Previously, we just returned the `filename` here. But this is supposed to be a full url, relative to the SourceMap url (or the minified file url as fallback).
> Make the JS `abs_path` actually an absolute path/url

- CHANGELOG.md
- Cargo.lock
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-service/src/utils/compression.rs
Windows symstore.exe added support to compress symbols with /compress ZIP arg.
Rather than simply compressing the file with deflate, it adds it in a ZipArchive.
We use this as CAB compression has a limit on file size (2GB: https://learn.microsoft.com/en-us/archive/blogs/windows_installer_team/what-are-the-upper-limits-of-the-cab-file-format).
From symstore.exe help:
```
/compress [type]    When storing files, store compressed files on the server.
Has two optional arguments "CAB" and "ZIP" to specify the
compression type to use. Defaults to CAB compression if none is
specified. Ignored when storing pointers.
```
Not fluent in rust so don't hesitate with feedback.
> Implement ZipArchive compressed symbols

- crates/symbolicator-service/src/services/download/sentry.rs
- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-service/tests/integration/sourcemap.rs
> Only lookup `url`s with a `release`

- crates/symbolicator-service/src/services/sourcemap_lookup.rs
I suspect that opening/parsing the artifact-bundles is expensive, so lets instrument this.
> Instrument `fetch_artifact_bundle`

- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-service/src/services/symbolication/js.rs
It is possible that the Sentry API lookup can be cached better with on-demand lookup.
Also adds instrumentation to more functions.
> Do not pre-fetch artifacts

- crates/symbolicator-service/src/services/symbolication/js.rs
- crates/symbolicator-service/src/types/mod.rs
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__indexed_sourcemap_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__inlined_sources.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_embedded_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_nofiles_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_source_expansion.snap
It appears this field is being used by python code down the road.
> Add the `data.sourcemap` field to JS stack frames

- Cargo.lock
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-service/src/services/symbolication/js.rs
The monolith has special handling for webpack filenames. This mirrors that logic.
> fix: Special case webpack filenames

- crates/symbolicator-service/src/services/symbolication/source_context.rs
> Be mindful of unicode boundaries when trimming lines

- crates/symbolicator-service/src/services/download/sentry.rs
- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-sources/src/sources/sentry.rs
This avoids hashing the file contents over and over again, which can be slow. Bundles and individual artifacts have a stable identity using the `SentryRemoteFile`. So files that come from Sentry Artifacts or Bundles can use that as the cache key. Scraped files will still use the content-hash however.
> Use FileUri for SourceMap cache keys

- crates/symbolicator-service/src/services/symbolication/js.rs
> fix: Don't go through abs_path when normalizing webpack filenames

- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-service/src/services/symbolication/js.rs
`Url::join` normalizes away `..` segments when joining URLs. We want to preserve these segments to align with the Python behavior.
> fix: Don't normalize .. segments in URLs

- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-service/src/services/symbolication/js.rs
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__malformed_abs_path.snap
> Don't use `Url` type in js processing

- Cargo.lock
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-service/src/services/caches/sourcefiles.rs
- crates/symbolicator-service/src/services/sourcemap_lookup.rs
This accepts any valid `data:` url, also with mismatching mimetype and non-base64 encoding.
fixes #1158
> Make data-url parsing more lenient

- crates/symbolicator-service/src/caching/shared_cache/mod.rs
- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-service/src/services/symbolication/js.rs
- crates/symbolicator-test/src/lib.rs
Using two env filters means the first one is overwritten and does not work anymore.
> Fix tracing output in tests

- .github/workflows/ci.yml
- .github/workflows/image.yml
- .github/workflows/lint-pipelines.yml
- gocd/pipelines/symbolicator-canary.yaml
- gocd/pipelines/symbolicator-lpq.yaml
Adds `concurrency` groups to GitHub Actions, so that in-progress jobs will be cancelled when pushing to PRs in quick succession.
Also changes the canary/lpq GoCD scripts to hardcode `canary`/`lpq` branches, to hopefully be able to deploy these from a non-master branch.
> Cancel in-progress CI and allow deploying from canary/lpq branches

- CHANGELOG.md
Commit 8e46e66383775 for #1139 misplaced the changelog entry under the 23.4.0 section.
#skip-changelog, lol
> Fix misplaced changelog entry for ZipArchive support

- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-service/src/services/symbolication/js.rs
- crates/symbolicator-service/src/types/mod.rs
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__malformed_abs_path.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_embedded_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_source_expansion.snap
This adds a new js module error variant to return when scraping is disabled and refactors js symbolication a bit.
> feat: Return an error if scraping is disabled

- crates/symbolicli/README.md
The location of the documentation for debug file sources in the API
documentation is not obvious, so include a link. Also include an
example .symboliclirc file. It is useful to have a seed to start from
instead of an empty file.
> Improve symboliclirc "sources" documentation

- CHANGELOG.md
- crates/symbolicator-service/src/services/symbolication/apple.rs
- crates/symbolicator-service/src/services/symbolication/js.rs
- crates/symbolicator-service/src/services/symbolication/mod.rs
- crates/symbolicator-service/src/services/symbolication/process_minidump.rs
- crates/symbolicator-service/tests/integration/sourcemap.rs
- crates/symbolicator-service/tests/integration/utils.rs
- crates/symbolicator-stress/src/main.rs
- crates/symbolicator/src/endpoints/symbolicate.rs
- crates/symbolicator/src/endpoints/symbolicate_js.rs
- crates/symbolicator/src/service.rs
- crates/symbolicli/src/main.rs
This exposes a new `apply_source_context` option on JS and Native symbolication requests that skips applying the source context. This is useful for symbolication requests coming from profiling, as that does not need any source context, and will throw it away immediately anyway.
Fixes #1105
> Make source-context application optional

- crates/symbolicator-service/src/services/symbolication/js.rs
- crates/symbolicator-service/src/types/mod.rs
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__e2e_react_native.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__e2e_source_no_header.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_embedded_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_source_expansion.snap
This adds an `in_app` field to `JsFrame`, as well as the logic to set it. `is_in_app_faithful` is a straightforward port of the monolith's logic for determining in-app-ness, while `is_in_app` rewrites it a little more sensibly.
I'm very unsure about the necessity of `NODE_MODULES_RE`. In `is_in_app` we already have checks for whether the `filename` or `abs_path` contain the string `/node_modules/`; `NODE_MODULES_RE` is almost the same thing, except it has a word boundary at the start instead of a `/`. Is this really a meaningful difference?
The fact that we scrutinize both the `filename` and the `abs_path` with no discernible rhyme or reason also bothers me. I wonder if this can be simplified so we only need to look at one or the other.
> WIP: JS in-app logic

- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-service/src/services/symbolication/js.rs
- crates/symbolicator-service/src/types/mod.rs
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__e2e_multiple_smref_scraped.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__e2e_node_debugid.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__e2e_react_native.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__e2e_source_no_header.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__fetch_error.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__indexed_sourcemap_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__inlined_sources.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__invalid_location.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__malformed_abs_path.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_embedded_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_nofiles_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_source_expansion.snap
The `module` might also be set from the SDK side, as is done in react-native.
However when applying sourcemaps, we want to override that with whatever sanitized `module` we get out of the source file path.
> Generate/override the `module` in JS symbolication

- crates/symbolicator-service/src/services/symbolication/js.rs
* Correctly detect cases where filenames begin with `node_modules/`
* Always overwrite the existing `in_app` field if the new value is `Some`
> fix(js): Fix some bugs in in_app logic

- Cargo.lock
- crates/symbolicator-service/Cargo.toml
Servers can sometimes unconditionally send brotli encoded response bodies that lack a self-identifying header and we thus can’t detect them in our decompression utility. However reqwest can handle them transparently just fine based on their response headers. Only thing missing was the feature flag for that.
> Add support for brotli transfer/content-encoding

- CHANGELOG.md
- crates/symbolicator/src/endpoints/symbolicate_js.rs
> fix(js): Make sentry source non-optional

- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-service/tests/integration/sourcemap.rs
Well, looks like the artifact lookup API can sometimes return an all-lowercase `sourcemap` header.
> Make `Sourcemap` header matching case-insensitive

- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-service/src/services/symbolication/js.rs
- crates/symbolicator-service/tests/integration/sourcemap.rs
Older versions of the JS SDK would not correctly strip the `async ` prefix, and that would then end up in the `abs_path`. We can easily work around that and be able to symbolicate such frames.
> Work around "async " abs_path

- CHANGELOG.md
- crates/symbolicli/src/main.rs
Since the purpose of `symbolicli` is to run symbolication, we want to take the `raw_stacktrace`s from events and not the already symbolicated `stacktrace`s.
> fix(symbolicli): Take raw stacktraces from event

- Cargo.lock
- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-service/tests/integration/sourcemap.rs
- crates/symbolicator-stress/Cargo.toml
- crates/symbolicator-stress/src/main.rs
- crates/symbolicator-test/src/lib.rs
This allows stresstesting JS symbolication. For this, the `workload` definition expects two files:
One for the mock lookup API results, the other for the event payload.
The lookup results look like:
```
[
{
"id": "17160921858",
"type": "bundle",
"url": "{url}/bundle-artifacts-820eecca3a4747e9857cf2cd8ff5a6bb.zip"
},
{
"id": "17161142466",
"type": "bundle",
"url": "{url}/bundle-artifacts-b68f8e8cab504fb0a8e43d51107cf1ee.zip"
}
]
```
The `{url}` pattern will be replaced by the local mock server url, and the files will be served from the same dir as the lookup json file. The event payload expects `stacktraces` and `modules`, just like the native stresstest definition.
> Stresstest JS symbolication

- CHANGELOG.md
- crates/symbolicator-service/src/config.rs
- crates/symbolicator-service/src/services/download/gcs.rs
- crates/symbolicator-service/src/services/download/http.rs
- crates/symbolicator-service/src/services/download/mod.rs
- crates/symbolicator-service/src/services/download/s3.rs
- crates/symbolicator-service/src/services/download/sentry.rs
- crates/symbolicator-service/src/utils/http.rs
Introduces a new `DownloadTimeouts` struct to group all the download-related timeouts. Introduces a new distinction between connect/HEAD timeout, and feeds the connect timeout and the global download timeout directly to reqwest.
> Tighten up download related timeouts

- Cargo.lock
- crates/process-event/Cargo.toml
- crates/symbolicator-crash/Cargo.toml
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-sources/Cargo.toml
- crates/symbolicator/Cargo.toml
- crates/symbolicli/Cargo.toml
- crates/symsorter/Cargo.toml
Also does a `cargo update`, as well as avoid a copy of the SourceBundle file contents.
> Update symbolic to fix SourceBundle lock contention

- Cargo.lock
- crates/process-event/Cargo.toml
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-sources/Cargo.toml
- crates/symbolicator/Cargo.toml
- crates/symbolicli/Cargo.toml
- crates/symsorter/Cargo.toml
This gives us https://github.com/getsentry/symbolic/pull/786, which will hopefully resolve https://github.com/getsentry/sentry-dart/issues/1430.
> deps: Update symbolic to 12.1.5

- CHANGELOG.md
- crates/symbolicator-service/src/services/symbolication/js.rs
- crates/symbolicator-service/src/types/mod.rs
- crates/symbolicli/src/main.rs
- crates/symbolicli/src/output.rs
Sentry already [filters out](https://github.com/getsentry/sentry/blob/3d1a915e3a7416106666ee0022c27fac487d5d41/src/sentry/lang/javascript/processing.py#L148) frames without line numbers before sending them to Symbolicator. Therefore, there's no reason for the `lineno` field to be optional. Unfortunately we still need to check if the line is 0.
> ref: Make JsFrame::lineno non-optional

- Cargo.lock
- crates/process-event/Cargo.toml
- crates/process-event/src/main.rs
- crates/symbolicator-stress/Cargo.toml
- crates/symbolicator-stress/src/main.rs
- crates/symbolicator-test/Cargo.toml
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/cli.rs
- crates/symbolicli/Cargo.toml
- crates/symsorter/Cargo.toml
- crates/symsorter/src/app.rs
- crates/wasm-split/Cargo.toml
- crates/wasm-split/src/main.rs
This fixes RUSTSEC issue that has been a long time overdue.
As a nice side-effect, we have a way better and colored help and error outputs.
Closes https://github.com/getsentry/symbolicator/issues/871
Pre/post output logs generated with:
```bash
for bin in {process-event,symbolicator-stress,symbolicator,symbolicli,symsorter,wasm-split}; do cargo run --package $bin -- --help >> post.out 2>&1; done;
```
[pre.log](https://github.com/getsentry/symbolicator/files/11664677/pre.log)
[post.log](https://github.com/getsentry/symbolicator/files/11664676/post.log)
> ref: Migrate from structops to clap for all CLIs

- .craft.yml
- .github/workflows/build.yml
- .github/workflows/docs.yml
- Makefile
I'm about 76% positive that it'll work on the first try.
> ci: Make docs publishing independent from the releases

- docs/api/sourcemaps.md
Whoopsie. It should not be here, it's already translated as the entry in the list.
> docs: Update sourcemaps.md

- crates/symsorter/src/app.rs
- crates/symsorter/src/config.rs
Fixes a panic when running symsorter, [Issue 1215](https://github.com/getsentry/symbolicator/issues/1215)
> Update compression level flag to be a u8 everywhere.

- crates/symbolicator-service/src/services/download/s3.rs
These were previously raising internal errors, but some of these include unique identifiers and break grouping.
> Silence S3 Unhandled errors

- crates/symbolicator-service/src/services/symbolication/js.rs
- crates/symbolicator-service/src/types/mod.rs
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__e2e_multiple_smref_scraped.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__e2e_node_debugid.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__e2e_react_native.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__e2e_source_no_header.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__indexed_sourcemap_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__inlined_sources.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_embedded_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_nofiles_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__webpack.snap
This adds a boolean field `symbolicated` to `JsFrame` so that we can check at a glance in Sentry if the frame was successfully symbolicated.
> feat(js): Track whether frames are symbolicated

- gocd/generated-pipelines/symbolicator-next-monitor.yaml
- gocd/generated-pipelines/symbolicator-next-us.yaml
- gocd/generated-pipelines/symbolicator-next.yaml
- gocd/templates/jsonnetfile.lock.json
This doesn't change the pipelines functionality, it puts the pipelines into a single group and orders them.
> Order pipelines and use a single gocd group

- crates/symbolicator-service/src/types/mod.rs
- crates/symbolicli/src/main.rs
* `JsFrameData::symbolicated` needs a default annotation or `symbolicli` crashes when trying to parse native frames.
* Exceptions and threads don't always have a `raw_stacktrace`, so we take the `raw_stacktrace` or `stacktrace`, whichever we find first.
> fix(symbolicli): Fix stacktrace & frame parsing

- crates/symbolicator-service/src/services/symbolication/js.rs
In that case we *did* technically resolve the sourcemap.
Question: Does it make sense to record this as well in either of the other cases? For instance, if we get a "scraping disabled" error, you could argue we should make note of the fact that we *tried* to resolve the sourcemap by scraping.
> fix(js): Record resolved_with for malformed sourcemaps

- crates/symbolicli/src/main.rs
Unfortunately `tracing_subscriber` logs to `stdout` by default. This makes it very annoying to e.g. pipe the JSON output to `jless`. This PR switches logging to `stderr`.
> fix(symbolicli): Log to stderr

- crates/symbolicli/src/settings.rs
It was possible (likely, in fact) for `symbolicli` to load `~/.symboliclirc` twice, once as the global config file, then again as the project config file.
> fix(symbolicli): Don't double read global config

- CHANGELOG.md
- crates/symbolicli/src/main.rs
- crates/symbolicli/src/settings.rs
This adds a `--symbols` argument that lets you pass an ad-hoc local symbol directory.
> feat(symbolicli): Add --symbols argument

- crates/symbolicator-service/src/caching/cache_key.rs
- crates/symbolicator-sources/src/sources/filesystem.rs
Filesystem URIs were printing one slash too many.
> fix: Remove superfluous slash

- crates/symbolicator-service/src/services/download/mod.rs
- crates/symbolicator-service/src/services/objects/mod.rs
- crates/symbolicator-service/src/types/objects.rs
- crates/symbolicator-service/tests/integration/e2e.rs
- crates/symbolicator-service/tests/integration/source_errors.rs
- crates/symbolicator-sources/src/remotefile.rs
This documents the invariant that `AllObjectCandidates` is always sorted and unique by `(source, location)` and makes sure that it is always maintained.
> fix: Deduplicate object candidates

- crates/symbolicator-service/src/types/mod.rs
This was added in https://github.com/getsentry/sentry/pull/52080 for the files that were looked up with the new artifact bundle index.
> Add new `ResolvedWith::Index`

- CHANGELOG.md
- crates/symbolicator-service/src/services/mod.rs
- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-service/src/services/symbolication/apple.rs
- crates/symbolicator-service/src/services/symbolication/js.rs
- crates/symbolicator-service/src/services/symbolication/mod.rs
- crates/symbolicator-service/src/services/symbolication/process_minidump.rs
- crates/symbolicator-service/tests/integration/utils.rs
- crates/symbolicator-stress/src/main.rs
- crates/symbolicator/src/endpoints/symbolicate.rs
- crates/symbolicator/src/service.rs
- crates/symbolicli/src/main.rs
- docs/api/symbolication.md
I'm not sure if `enabled` should even be a thing for Source Context, but I wanted to reuse the same `ScrapingConfig` everywhere (which is now extracted from JS modules code).
Closes https://github.com/getsentry/symbolicator/issues/1244
> feat: Add authentication to Source Context fetching via scraping config

- Makefile
- gocd/generated-pipelines/rollback-symbolicator-next.yaml
- gocd/generated-pipelines/symbolicator-next-monitor.yaml
- gocd/generated-pipelines/symbolicator-next-us.yaml
- gocd/templates/jsonnetfile.json
- gocd/templates/jsonnetfile.lock.json
- gocd/templates/pipelines/symbolicator.libsonnet
- gocd/templates/symbolicator.jsonnet
This PR does the following:
- Update the jsonnet libs which have a slight structure change (/v1.0.0 -> /libs)
- Order of the pipelines changes to s4s -> saas
- Add a rollback pipeline to make rolling back with pipedream easier
> Update jsonnet libs and add rollback pipeline

- crates/symbolicli/src/settings.rs
When using `symbolicli` you really don't want to cache missed downloads for an hour. Most likely you just forgot to add a symbol source and want to try again immediately.
> feat(symbolicli): Immediately retry missed downloads

- Cargo.lock
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-service/src/caching/cleanup.rs
This is a hotfix to give us more headroom while investigating stuck cleanup jobs. See the comment in the relevant function.
> Cleanup caches in random order

- crates/symbolicator-service/src/services/objects/mod.rs
The `From` impl of `AllObjectCandidates` already sorts and dedupes, no need to do that manually via a custom insertion-sort.
> Remove manual insertion-sort from `create_candidates`

- crates/symbolicator-service/src/services/download/mod.rs
> fix: Emit download failure metric for Sentry sources

- crates/symbolicator-service/src/services/download/mod.rs
This function's results are passed to `select_meta`, which expects them to be sorted by preference. Therefore we can't sort them by source id willy-nilly here.
> fix: Don't sort/deduplicate in list_files

- crates/symbolicator-service/src/services/sourcemap_lookup.rs
> Make extracting a the `download_id` more robust

- gocd/generated-pipelines/rollback-symbolicator.yaml
- gocd/generated-pipelines/symbolicator-monitor.yaml
- gocd/generated-pipelines/symbolicator-us.yaml
- gocd/generated-pipelines/symbolicator.yaml
- gocd/pipelines/symbolicator.yaml
- gocd/templates/symbolicator.jsonnet
This switches the symbolicator pipelines over to pipedream which will deploy to monitor (s4s) and then saas.
At the moment the pipeline has 2 manual steps, one for deploying canary and one for deploying primary, this is done for both s4s AND saas deployments, **should I remove these manual steps or leave them as is for now?**
NOTE: The old pipelines will still be available but will be moved to a new group "symbolicator-old" in case they are needed during the transition.
> Switch pipelines to pipedream

- gocd/pipelines/symbolicator.yaml
I didn't realize that new groups like *-old would not have correct permissions for viewing and operating.
Moving the old pipelines back to address this.
> Move symbolicator back to original group

- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-service/src/services/symbolication/js.rs
- crates/symbolicator-service/src/types/mod.rs
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__bundle_index.snap
- crates/symbolicator-sources/src/sources/sentry.rs
When using the `BundleIndex`, we will report back to Sentry the actually used `ArtifactBundle`s. This way, auto-expiration can work properly when using the `BundleIndex`, and it is even more accurate than using the `artifact-lookup` API.
> Report used `ArtifactBundle`s back to Sentry

- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-service/tests/integration/e2e.rs
- crates/symbolicator-sources/src/remotefile.rs
Looks like we immediately ran into a problem where the `BundleIndex` says a file has to be in a certain bundle, but it is not.
This will now keep track and log the following things in that case:
- The `BundleIndex` being used
- The `ArtifactBundle` that is claimed to contain the file
- The exact `lookup_key` that is supposed to be found inside the bundle
> Add more logging to failed `BundleIndex` lookups

- .github/workflows/validate-pipelines.yml
- Makefile
- gocd/templates/jsonnetfile.json
- gocd/templates/jsonnetfile.lock.json
This change does the following:
- Update the gocd-jsonnet libs such that it supports output multiple files OR a single file. The single file will be used by the GoCD jsonnet plugin (the pipelines will be exactly the same in GoCD)
- Update the validation workflow to use the single file fixing the gocd validation action.
> Fix GoCD pipedream validation

- gocd/generated-pipelines/rollback-symbolicator.yaml
- gocd/generated-pipelines/symbolicator-customer-3.yaml
- gocd/generated-pipelines/symbolicator-customer-4.yaml
- gocd/generated-pipelines/symbolicator-customer-5.yaml
- gocd/generated-pipelines/symbolicator-customer-6.yaml
- gocd/templates/jsonnetfile.json
- gocd/templates/jsonnetfile.lock.json
This change adds customer 3 and 4 to pipedream and test deployments for customers 5 and 6
NOTE: This is the final addition of deployments that I've planned
> Update gocd-jsonnet to v1.4.1

- gocd/generated-pipelines/rollback-symbolicator.yaml
- gocd/generated-pipelines/symbolicator-customer-1.yaml
- gocd/generated-pipelines/symbolicator-customer-2.yaml
- gocd/generated-pipelines/symbolicator-customer-3.yaml
- gocd/generated-pipelines/symbolicator-customer-4.yaml
- gocd/generated-pipelines/symbolicator-customer-5.yaml
- gocd/generated-pipelines/symbolicator-customer-6.yaml
- gocd/generated-pipelines/symbolicator-s4s.yaml
- gocd/generated-pipelines/symbolicator-us.yaml
- gocd/templates/jsonnetfile.json
- gocd/templates/jsonnetfile.lock.json
- gocd/templates/pipelines/symbolicator.libsonnet
Removing the canary stage entirely for non-saas deployments makes sense since only the US deployment has any canary pods.
_*Question*_: I think it's safe to skip the "create sentry release" step in canary and just run the prod create sentry release, but could you take a look and confirm.
This PR also removed the manual step from the canary deployment in the US.
The result of these changes is that deployments will have one manual step per deployment (the deploy-prod step.
**In the future it might be worth considering changing this remaining manual step to only be needed for US regions**, even better would be to add automatic checks to the canary deployment in the US using the approaches listed here: https://www.notion.so/sentry/Block-deployments-on-canary-cd96781d331242c097f6959117d70ef3 …
> Remove canary from non-us regions and remove canary manual step

- crates/symbolicator-service/src/caching/shared_cache/mod.rs
- crates/symbolicator-service/src/config.rs
- crates/symbolicator-service/src/services/bitcode.rs
- crates/symbolicator-service/src/services/cficaches.rs
- crates/symbolicator-service/src/services/download/mod.rs
- crates/symbolicator-service/src/services/il2cpp.rs
- crates/symbolicator-service/src/services/objects/data_cache.rs
- crates/symbolicator-service/src/services/ppdb_caches.rs
- crates/symbolicator-service/src/services/symcaches.rs
- crates/symbolicator/src/service.rs
- Lowers the global per-task timeout from 60 to 15 minutes.
- Remove a ton of intermediate `measure` usage, replacing those with tracing instead.
- Also remove intermediate timeouts, as those should rather be propagated from the global timeout.
- Adds a stream timeout to the shared cache download code, and a timeout around spawning the download.
- Make sure that we get performance tracing transactions for tasks that are timing out.
- Also reduces the number of cache stores for refreshes.
> Tighten up some internal timeouts

- Cargo.lock
Downgrading `hyper` did not alleviate https://github.com/getsentry/sentry/issues/52516. Therefore we're reverting 2f3f57f33ca176ef160b2629deb0a72d8b5a4b02.
> Revert "deps: Downgrade hyper to 0.14.26 (#1286)"

- CHANGELOG.md
- crates/symsorter/src/app.rs
- crates/symsorter/src/utils.rs
This will now complete skip any object kinds that do not make any sense to be processed by Symsorter.
fixes https://github.com/getsentry/symbolicator/issues/1280
fixes https://github.com/getsentry/symbolicator/issues/1240
> Do not process `.o` files in Symsorter

- crates/symbolicator-service/src/js/metrics.rs
- crates/symbolicator-service/src/js/mod.rs
- crates/symbolicator-service/src/lib.rs
- crates/symbolicator-service/src/services/download/sentry.rs
- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-service/src/services/symbolication/js.rs
- crates/symbolicator-service/src/types/mod.rs
In order to better measure the success of JS symbolication, this introduces more fine grained metrics that represent a funnel:
We capture metrics for source files and sourcemaps separately, with the following tags:
- found via debug-id
- found via release
- found via release-old
- found via scraping
- not found
- not needed (for sourcemaps)
This reuses existing metrics names as much as possible for now.
Additionally, this also captures more metrics for engineers that go into detail via which method the bundle was found.
fixes https://github.com/getsentry/sentry/issues/49950
> Introduce more metrics for JS File Lookup

- CHANGELOG.md
- Cargo.lock
- crates/process-event/Cargo.toml
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-sources/Cargo.toml
- crates/symbolicator/Cargo.toml
- crates/symbolicli/Cargo.toml
- crates/symsorter/Cargo.toml
This pulls in https://github.com/getsentry/symbolic/pull/809, which means that source mapping URLs will be read without query strings or fragments.
> deps: Update symbolic to 12.4.0

- crates/symbolicator-service/src/services/download/mod.rs
> feat: Emit number of currently blocked hosts

- crates/symbolicator-service/src/caching/memory.rs
This should cut the number of files that are written on production builds in half, reducing pressure on the cleanup job.
> Only write cache metadata on debug builds

- Cargo.lock
- crates/symbolicator-stress/Cargo.toml
- crates/symbolicator-stress/src/logging.rs
- crates/symbolicator-stress/src/main.rs
- crates/symbolicator-stress/src/stresstest.rs
- crates/symbolicator-stress/src/workloads.rs
- crates/symbolicator/src/logging.rs
This adds the stacktraces, tracing, sentry and metrics to the stresstest.
The purpose of this is to also measure and profile the effect that various instrumentation has on the performance.
For this, all the various pieces of instrumentation are being initialized with configuration that is as close to real-world as possible, except all the logging and instrumentation is going to the void.
This is not yet fully complete, it is still missing dummy HTTP and UDP servers that Sentry envelopes and metrics data can be sent to.
> Add instrumentation to Stresstest

- .vscode/launch.json
- crates/symbolicator-service/src/services/symbolication/process_minidump.rs
We were previously discarding all minidump modules that did not have a debug-id. However you can still at least get a reasonable function name in most cases from the symbol table of a code file using the code-id.
> Capture minidump modules with usable code-id

- Cargo.lock
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-stress/Cargo.toml
- crates/symbolicator/Cargo.toml
The newly released Sentry SDK should slightly improve performance by using faster random IDs.
> Cargo update, in particular Sentry SDK

- crates/symbolicator-service/src/services/download/mod.rs
Instead of auto-blocking all bad symbol servers, only restrict this to http, as we got increasing complaints about gcs being blocked.
> Only block http symbol servers

- gocd/templates/jsonnetfile.json
- gocd/templates/jsonnetfile.lock.json
- gocd/templates/pipelines/symbolicator.libsonnet
- gocd/templates/symbolicator.jsonnet
Also rename deploy_* to deploy-* to match getsentry pipelines (this may be helpful in the future for eng-pipes wanting to easily detect the end of a pipeline).
> Update gocd-jsonnet to 2.2.2

- crates/symbolicator-service/src/services/symbolication/apple.rs
- crates/symbolicator-service/src/services/symbolication/process_minidump.rs
- crates/symbolicator-service/tests/integration/process_minidump.rs
- crates/symbolicator-service/tests/integration/symbolication.rs
- crates/symbolicator-stress/src/workloads.rs
- crates/symbolicator/src/endpoints/applecrashreport.rs
- crates/symbolicator/src/endpoints/minidump.rs
- crates/symbolicator/src/service.rs
- crates/symbolicli/src/main.rs
Originally, the ScrapingConfig was only passed down to symbolicate requests. Now it is also being handled for minidump requests.
> Thread scraping config through minidump requests

- .craft.yml
- .github/workflows/build.yml
> meta: Provide symbolicli binaries

- .github/workflows/ci.yml
This should add a hosts alias from the internal test server addr to `host.docker.internal`.
> Try to fix integration test CI

- crates/symbolicator-service/src/services/cficaches.rs
- crates/symbolicator-service/src/services/symbolication/process_minidump.rs
We have seen customer minidumps that do not have proper DebugIds in them. However, there is a valid CodeId, which would allow the executable to be fetched from an external SSQP symbol server. We transform this executable to a CfiCache, which in theory could have a breakpad `MODULE` entry. Though in practice it does not (yet), as we never output one.
This would allow backfilling the missing DebugID in the minidump with the one found in the executable that we use to generate the CfiCache.
> Backfill missing DebugId from CFI Cache

- crates/symbolicator-service/src/services/sourcemap_lookup.rs
We can have non-minified files identified by DebugId which do not have a corresponding SourceMap. In that case we do not want to raise an internal error when no SourceMap is found based on the BundleIndex.
> Silence BundleIndex error

- Cargo.lock
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-service/src/services/symbolication/process_minidump.rs
The recent dependency update introduced a memory leak, which might be related to the `moka` update, so try downgrading that.
> Downgrade `moka`

- gocd/templates/jsonnetfile.json
- gocd/templates/jsonnetfile.lock.json
- gocd/templates/symbolicator.jsonnet
This fixes an issue in rollbacks that can cause multiple deploys of the same commit. Now rollbacks have a final manual stage that unpauses and unlocks the pipelines once an incident is complete.
For the curious: The I removed the pipeline-complete stage in a previous version, this caused pipelines to be unlocked after a rollback is complete (a problem folks were running into), however this meant the final stage in the deploy was the stage the rollback re-ran. Since this final stage was run, it triggered the downstream pipeline to run which was unintentional.
> Update GoCD Jsonnet library

- .vscode/extensions.json
Update VS Code extension recommendation from a deprecated one to it's current suggested alternative: https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml
> chore: update deprecated BetterTOML recommendation

- crates/symbolicator-service/src/services/sourcemap_lookup.rs
- crates/symbolicator-service/src/services/symbolication/js.rs
- crates/symbolicator-service/src/types/mod.rs
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__bundle_index.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__e2e_multiple_smref_scraped.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__e2e_node_debugid.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__e2e_react_native.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__e2e_source_no_header.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__fetch_error.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__indexed_sourcemap_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__inlined_sources.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_embedded_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_nofiles_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__sourcemap_source_expansion.snap
- crates/symbolicator-service/tests/integration/snapshots/integration__sourcemap__webpack.snap
- crates/symbolicator-test/src/lib.rs
This records the outcome of every attempt to scrape a JS source or sourcemap file from the web and returns these attempts in `CompletedJsSymbolicationResponse`.
It also records a "not attempted" attempt whenever a file is found via another method.
> feat: Return "scraping attempts" from JS symbolication

- Cargo.lock
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-service/src/services/symbolication/process_minidump.rs
This does a `cargo update`, and also updates the `moka` dependency again. It was downgraded in #1310 because of a memory leak, which should now be solved. See https://github.com/moka-rs/moka/issues/329.
> Update `moka` and other dependencies

- crates/symbolicator-service/src/services/sourcemap_lookup.rs
> Record the `file_id` for failed BundleIndex downloads

- crates/symbolicator-js/src/bundle_index_cache.rs
- crates/symbolicator-service/src/caching/cache_error.rs
- crates/symbolicator-service/src/caching/cache_key.rs
- crates/symbolicator-service/src/caching/memory.rs
- crates/symbolicator-service/src/services/bitcode.rs
- crates/symbolicator-service/src/services/il2cpp.rs
- crates/symbolicator-service/src/services/objects/data_cache.rs
- crates/symbolicator-service/src/services/objects/mod.rs
- crates/symbolicator-sources/src/remotefile.rs
It is a bit wasteful to look up our internally hosted Symbols on GCS, just to store them on GCS again in the form of the shared cache.
We can avoid doing this needless duplication of roundtrips and storage.
We could also avoid using the shared cache for objects and bundle indexes that are stored in Sentry, but here the benefits are less clear, as avoiding shared cache would mean going through the Python abstraction. Right now, we rather waste a bit of storage in favor of avoiding Python.
These tradeoffs could potentially change in the future with a more efficient filestore implementation though.
> Avoid using shared cache for internally stored files

- gocd/templates/jsonnetfile.json
- gocd/templates/jsonnetfile.lock.json
This should be a noop as it just contains cleanup from v2.3.1
> Update to v2.3.2 of gocd-jsonnet

- Cargo.lock
- crates/symbolicator-native/Cargo.toml
- crates/symbolicator-native/src/symbolication/apple.rs
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-service/src/caching/memory.rs
- crates/symbolicator-service/src/metrics.rs
- crates/symbolicator-service/src/utils/http.rs
- crates/symbolicator-sources/Cargo.toml
- crates/symbolicator-sources/src/paths.rs
- crates/symsorter/Cargo.toml
- crates/symsorter/src/config.rs
- crates/symsorter/src/utils.rs
This replaces the `lazy_static` and `parking_lot` crates with `once_cell` and `std` types.
Also does a `cargo update` for good measure.
Based on #1324 , so will wait and rebase after that lands.
> Modernize some crate dependencies

- Cargo.lock
- crates/symbolicator-native/src/symbolication/process_minidump.rs
- crates/symbolicator-service/Cargo.toml
A `cargo update` with a few manual crate updates, plus a clippy run.
> Update dependencies and fix clippy

- Dockerfile
This should get us uptodate system packages / dependencies.
Should hopefully fix #1326, though there is still this thing called Docker layer caching, which might just cache all of this for longer term.
#skip-changelog ffs
> Run `apt-get upgrade` in Docker

- Cargo.lock
This does a `cargo update` which pulls in the newest crates, and in particular also bumps our patched `reqwest`.
> Update crate dependencies

- Cargo.toml
- crates/symbolicator-service/src/caching/memory.rs
Related to https://github.com/getsentry/symbolicator/issues/1334 CC @zamazan4ik 
This is so far just doing the first step, using 1 CGU and LTO to optimize the compiler output, without relying on instrumentation and gathering profiling.
Using cargo `--timings`, I get local bound times of ~260s of Rust build + ~640s of linking time (LLVM does code generation at link time with LTO if I understand things correctly) for a total of ~15 minutes.
The first part we can mostly solve with dependency caching, but not the last linking step. So our docker builds will most likely take in the order of 10 minutes.
I would actually like to land this and maybe let it run over the weekend in a canary, so we can compare that to the baseline.
> Enable LTO for release builds

- cloudbuild.yaml
looks like LTO builds are dieing for some reason, possibly related to low memory.
> Increase cloudbuild Machine

- Dockerfile
In the hope of slightly improving the compile/link times in cloudbuild / docker
> Use Mold linker in Docker

- Cargo.lock
- Cargo.toml
- Dockerfile
- crates/symbolicator-crash/Cargo.toml
- crates/symbolicator-crash/build.rs
- crates/symbolicator-js/Cargo.toml
- crates/symbolicator-native/Cargo.toml
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-service/src/caching/cache_key.rs
- crates/symbolicator-stress/Cargo.toml
- crates/symbolicator-stress/src/logging.rs
- crates/symbolicator-test/Cargo.toml
- crates/symbolicator-test/src/lib.rs
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/endpoints/proxy.rs
- crates/symbolicator/src/server.rs
This updates `axum/server` and the Sentry SDK to the latest versions along with doing a `cargo update` and applying nightly clippy fixes.
Also splits LTO builds into a separate profile, as doing local `release` builds is way too slow when using 1 CGU + LTO.
So instead, create a new profile for that and use it in docker builds.
> Update Axum & deps, Split LTO into separate profile

- crates/symbolicator-service/src/metrics.rs
- crates/symbolicator-service/src/utils/futures.rs
Instead of defining a custom wrapper type to add global tags, use the built in cadence functionality to do so.
---
This is the cleanups from https://github.com/getsentry/symbolicator/pull/1351, but without the part that actually sends things to Sentry.
> Clean up Metrics usage a bit

- crates/symbolicator-service/src/download/gcs.rs
- crates/symbolicator-service/src/utils/gcs.rs
Avoid `format!`-ing a String for each request, and remove an `Arc` indirection.
> Micro-optimize GCS token access

- crates/symbolicator-js/src/lookup.rs
> docs: Document FileInBundleCache

- crates/symbolicator-native/Cargo.toml
- crates/symbolicator-native/src/symbolication/process_minidump.rs
Profiling has shown that `moka` might be a bit overkill for the `SymbolProvider`. The `SymbolProvider` is never used for long term caching, but only as a short term `HashMap`. This removed `moka` from this code path, and also avoids a bunch of Clones and other work from the `process_minidump` flow.
```
Workload 0 (concurrency: 10): 6746 operations, 224.86667 ops/s
Workload 1 (concurrency: 10): 5405 operations, 180.16667 ops/s
Workload 2 (concurrency: 10): 8014 operations, 267.13333 ops/s
Workload 0 (concurrency: 10): 7610 operations, 253.66667 ops/s
Workload 1 (concurrency: 10): 6075 operations, 202.5 ops/s
Workload 2 (concurrency: 10): 8770 operations, 292.33334 ops/s
```
Looks like a ~10% win
> Avoid using `moka` in the `SymbolProvider`

- Cargo.toml
- crates/symbolicator-js/src/bundle_lookup.rs
- crates/symbolicator-js/src/lib.rs
- crates/symbolicator-js/src/lookup.rs
- crates/symbolicator-js/src/service.rs
When profiling (via `symbolicator-stress`) processing of javascript events, the majority of the time is spent extracting minified / sourcemap files from artifact bundles (which are essentially zip files).
We introduce yet another cache which can avoid this costly unzip process by keeping these unzipped files in memory.
For the above mentioned stresstest, this has lead to a throughput increase of 1000x. Though not surprisingly, the stresstest processes the exact same event over and over and has thus a 100% cache hit rate.
> Add another Cache for accessing files in `ArtifactBundle`s

- crates/symbolicator-js/src/lookup.rs
We added this at one point to look at the `host`, but I doubt noone ever did this, or not in any recent history.
Overhead from this should be negligible, but no code is still faster than fast code :-D
#skip-changelog, because ofc
> Remove `scrape_js_file` transaction

- Cargo.lock
- crates/symbolicator-service/src/metrics.rs
- crates/symbolicator-stress/Cargo.toml
- crates/symbolicator-stress/src/logging.rs
- crates/symbolicator-stress/src/main.rs
- crates/symbolicator-stress/src/stresstest.rs
I added a local UDP sink to fully test metrics submission. It turns out the default `cadence` sink and the UDP submissions it does are *extremely* slow (at least on my machine).
Switching to the queueing and buffering sink speeds up the stresstest considerably.
```
Workload 0 (concurrency: 10): 176 operations, 11.733334 ops/s
Workload 1 (concurrency: 10): 137 operations, 9.133333 ops/s
Workload 2 (concurrency: 10): 190 operations, 12.666667 ops/s
Workload 3 (concurrency: 100): 169 operations, 11.266666 ops/s
Workload 4 (concurrency: 100): 388 operations, 25.866667 ops/s
Workload 5 (concurrency: 50): 563 operations, 37.533333 ops/s
Workload 0 (concurrency: 10): 2613 operations, 174.2 ops/s
Workload 1 (concurrency: 10): 1978 operations, 131.86667 ops/s
Workload 2 (concurrency: 10): 3681 …
```
> Add metrics to stresstest and optimize `cadence` usage

- crates/symbolicator-js/src/bundle_lookup.rs
- crates/symbolicator-js/src/lib.rs
- crates/symbolicator-js/src/lookup.rs
- crates/symbolicator-js/src/service.rs
- crates/symbolicator-js/src/sourcemap_cache.rs
- crates/symbolicator-js/src/symbolication.rs
According to metrics, the cache is quite effective in ST and on LPQ instances. Less so in production, most likely because the cache is too small.
To increase the effective size of the cache, we do not store the actual sourcemap contents in it anymore. These contents are only used for sourcemapcache generation, and are not usually required.
> Do not persist SourceMap contents in `FileInBundleCache`

- gocd/templates/jsonnetfile.json
- gocd/templates/jsonnetfile.lock.json
This update to the GoCD jsonnet library adds DE in as a test region to pipedream.
https://github.com/getsentry/gocd-jsonnet/releases/tag/v2.8
> Bumping GoCD jsonnet to include de

- Cargo.lock
- crates/symbolicator-native/Cargo.toml
- crates/symbolicator-service/src/download/s3.rs
- crates/symbolicator/src/logging.rs
Since basically forever, `rust-minidump` has been spewing unactionable warnings related to `XSTATE` which are being logged as Sentry breadcrumbs.
Also, a ton of S3 related `NoSuchBucket` errors have been logged internally which should ideally have been handled silently, but it looks like the S3 SDK does not properly handle those errors itself.
> Update dependencies and silence errors

- crates/symbolicator-service/src/download/sentry.rs
The debug files endpoint in Sentry supports querying by a list of file formats:
https://github.com/getsentry/sentry/blob/e23668f702957cc09d47977cacfa2b9c8b384928/src/sentry/api/endpoints/debug_files.py#L248
https://github.com/getsentry/sentry/blob/e23668f702957cc09d47977cacfa2b9c8b384928/src/sentry/api/endpoints/debug_files.py#L281-L287
Therefore we can already do the filtering by file type when we make the query to the Sentry source, instead of getting all files and filtering afterwards.
> doc(sources): Document rationale for Sentry list_file behavior

- crates/symbolicator-proguard/src/interface.rs
This adds frame, stacktrace, &c., types, as well as `SymbolicateJvmRequest`. Unlike other symbolication request types, we have exceptions here. I kept the structure the same as in events, i.e., stacktraces are contained in exceptions. 
Modules consist of just uuids for now, we might expand them.
> feat(proguard): Add types for JVM requests

- crates/symbolicator-proguard/src/interface.rs
- crates/symbolicator-proguard/src/lib.rs
- crates/symbolicator-proguard/src/service.rs
- crates/symbolicator-proguard/src/symbolication.rs
- crates/symbolicator-proguard/tests/integration/proguard.rs
- tests/fixtures/proguard/02/proguard.txt
This implements exception remapping as seen in https://github.com/getsentry/sentry/blob/526b69cc0e27f3b44fb9c808e5a5dae85ddfcb7c/src/sentry/lang/java/plugin.py#L73-L92. There's a unit test as well as an "end-to-end" test making an actual request.
I've split apart exceptions and stacktraces in `SymbolicateJvmStacktraces` because they should really be processed separately. Moreover, I've added a rudimentary `CompletedJvmSymbolicationResponse` that only contains the remapped exceptions for now.
> feat(proguard): Implement exception remapping

- crates/symbolicator-js/src/bundle_lookup.rs
- crates/symbolicator-service/src/download/mod.rs
- crates/symbolicator-service/src/utils/futures.rs
- crates/symbolicator/src/endpoints/metrics.rs
Some of the improvements were extracted from #1379
- Avoid `format!`-ing metric keys
- Use macros instead of manual invocations
- Add a metrics for the JS `file_in_bundle` cache
> Slight metrics improvements

- crates/symbolicator-service/src/metrics.rs
It looks like distribution-like metrics do not make it through `veneur` properly, possibly because of sending multiple at once.
Sending them individually should solve this problem, hopefully.
> Send distribution-like metrics individually

- Cargo.lock
- crates/symbolicator-native/Cargo.toml
I was working on a bunch of improvements upstream which we are now pulling in. This new version also has support for unwinding directly using object files, so we can also work towards removing breakpad ASCII conversion sometime in the future.
> Update `minidump` along with other dependencies

- crates/symbolicator-service/src/caching/cache_error.rs
Related to #1386. We have observed that cache cleanup fails because of a corrupted file.
That file contained a valid `CacheError` prefix, but then gigabytes worth of NUL-bytes, plus some garbage.
This change works around this corrupted file by only reading the valid `CacheError` prefix, and not more.
> Do not read garbage `CacheError` markers

- crates/symbolicator-js/src/bundle_lookup.rs
- crates/symbolicator-js/src/service.rs
- crates/symbolicator-service/src/config.rs
JS symbolication is very sensitive to this cache size.
We noticed a significant reduction in CPU usage with a cache size of ~2G, which
resulted in a hit ratio of ~60-65%. Lets give it a bit more then and see what happens, and make it configurable for the future, so it can be tuned per-deployment.
---
The PR is currently on top of https://github.com/getsentry/symbolicator/pull/1397, but I can also rebase, no problem.
> Increase `FileInBundleCache` size and make it configurable.

- crates/symbolicator-proguard/src/interface.rs
- crates/symbolicator-proguard/src/symbolication.rs
Add `raw_stacktraces` to the `CompletedJvmSymbolicationResponse`. For now they're always identical to the input stacktraces; this will become relevant when we implement source context.
> ref(proguard): Return raw stacktraces

- crates/symbolicator-proguard/src/interface.rs
- crates/symbolicator-proguard/src/service.rs
- crates/symbolicator-proguard/src/symbolication.rs
This maps the `CacheErrors` that may occur when fetching and processing a proguard file to a typed representation before returning it in `CompletedJvmSymbolicationResponse`. This is so we can map the errors to `EventErrors` in Sentry. Having to scrutinize error messages is unfortunately quite ugly.
Strangely enough, on the Sentry side there is no `EventError` variant for invalid proguard files—indeed, the validity is never checked at all. This makes we wonder if we're being overly strict on the Symbolicator side, although I can't really imagine what the use of not rejecting an invalid file would be.
ETA: This PR also removes some `#[allow_unused]` annotations, as well as a useless struct field.
> ref(proguard): Return typed errors

- crates/symbolicator-proguard/src/interface.rs
- crates/symbolicator-proguard/src/symbolication.rs
This reverts commit 6d6163b964bed7555939c071478d98b519068ecf.
As pointed out in the discussion of https://github.com/getsentry/symbolicator/pull/1399, adding source context to the raw (obfuscated) stacktrace is not really useful. That makes returning the raw stacktrace pointless.
> Revert "ref(proguard): Return raw stacktraces (#1399)"

- crates/symbolicator-service/src/download/mod.rs
- crates/symbolicator-service/src/utils/http.rs
This removes the `config` parameter from `create_client`. The only config setting that was used in the function was `connect_to_reserved_ips`, and that was OR-ed with the `trusted` parameter, so we just do that outside the function now.
This also adds an `accept_invalid_certs` parameter in preparation for #1402.
> ref: Simplify create_client

- CHANGELOG.md
- crates/symbolicator-service/src/config.rs
- crates/symbolicator-service/src/download/mod.rs
This makes two fundamental changes to the `HostDenyList`.
1. It's now optional and can be disabled by setting `deny_list_enabled` to `false` (default is `true` so everything keeps working as before).
2. It allows you to exclude a list of hosts, meaning they will never be blocked. This list is configured via `deny_list_never_block_hosts` (defaults to `[]`).
> ref(download): Improve configurability of `HostDenyList`

- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-service/src/metrics.rs
This is an updated alternative to #1351 
It is now integrated into the metrics aggregator, and sends Sentry metrics from there.
The performance impact is quite visible in the flamegraphs, but overall numbers do not look that bad.
It is a bit unfortunate that the Sentry API expects `Cow<'static, str>`, which pretty much means incurring `String` allocations for this all the time, which is quite inefficient, but does not seem to hurt performance that much.
I would say this is ready to be tested in canary.
> Hook up Sentry Metrics to Metrics Aggregator

- .github/workflows/build.yml
reverts https://github.com/getsentry/symbolicator/pull/1380
upload-artifact v4 introduces a blocking change where artifact files cannot be uploaded with the same name. In order to get us on the newer version, we need to ensure the artifact file names that are uploaded have different names.
> Use upload-artifact v3

- crates/symbolicator-proguard/src/interface.rs
- crates/symbolicator-proguard/src/symbolication.rs
This serializes error variants in snake_case. I didn't originally add this because I thought it was the default.
ETA: Also adds an error log message when we encounter an invalid proguard file.
> fix(proguard): Fix error casing

- CHANGELOG.md
- crates/symbolicator-proguard/src/interface.rs
- crates/symbolicator-proguard/src/symbolication.rs
- crates/symbolicator-proguard/tests/integration/proguard.rs
Symbolication can expand one raw JVM frame into multiple frames. When we return the symbolicated stacktraces, we want it to be possible to tell which symbolicated frames came from which raw frames. To this end, we add an index to frames that you need to pass in and that gets copied to the symbolicated frames.
Example: You send a stacktrace to Symbolicator containing frames with indices `[0, 1, 3, 4]` (frame `2` has been filtered out for one reason or another). Symbolicator expands frame `3` to 3 frames. Then you'll get back frames with indices `[0, 1, 3, 3, 3, 4]`.
> ref(proguard): Keep track of frame indices

- CHANGELOG.md
- crates/symbolicator-proguard/src/interface.rs
- crates/symbolicator-proguard/src/symbolication.rs
- crates/symbolicator-proguard/tests/integration/proguard.rs
- crates/symbolicator-proguard/tests/integration/snapshots/integration__proguard__source_lookup_with_proguard.snap
Based on #1414.
Without a line number, we can still at least try to remap a frame's class name. Of course, source context doesn't work at all without a line number.
> ref(proguard): Make line numbers optional

- crates/symbolicator-proguard/src/service.rs
- crates/symbolicator-service/src/caching/mod.rs
- crates/symbolicator-service/src/config.rs
By default, in-memory caches have a size of 100KiB. This is sufficient for file types where we only cache some bookkeeping structs in memory. In the case of Proguard, we cache `ProguardMapper` structs, and those can be quite hefty. In brief experiments I found a mapper to be slightly less than twice the size of the mapping file on disk, and those files can take up hundreds of megabytes.
Therefore:
* We estimate the memory footprint of a `ProguardMapper` as twice the size of the file on disk;
* We set the in-memory cache capacity for Proguard to 2GiB.
> ref(proguard): Properly size the in-memory cache

- CHANGELOG.md
- Cargo.lock
- crates/symbolicator-proguard/Cargo.toml
- crates/symbolicator-proguard/src/interface.rs
- crates/symbolicator-proguard/src/symbolication.rs
The signature will be properly converted from bytecode types to java types, plus the method parameters will be used to map the frame in absence of line numbers.
> feat(proguard): add support for frame signature

- crates/symbolicator-proguard/src/symbolication.rs
The Python implementation only applies source context if the line number is > 0.
> fix(proguard): Don't apply source context to frames with lineno 0

- CHANGELOG.md
- crates/symbolicator-proguard/src/symbolication.rs
Add the translated and deobfuscated signature even in case the whole frame could not be remapped.
> Add deobfuscated signature unconditionally

- crates/symbolicator-js/src/lookup.rs
- crates/symbolicator-native/src/symbolication/source_context.rs
- crates/symbolicator-service/src/types.rs
- crates/symbolicator-sources/src/sources/http.rs
This adds a flag `use_ssl` to `ScrapingConfig` (defaults to `true`). This flag determines whether Symbolicator uses the normal client or the "no ssl" client we added in https://github.com/getsentry/symbolicator/pull/1404 when scraping files from the web.
The other side part that needs to be done is to actually send the flag with the scraping config from Sentry (https://github.com/getsentry/sentry/pull/68682).
> feat: Allow scraping without SSL/TLS

- crates/symbolicator-proguard/src/service.rs
- crates/symbolicator-proguard/src/symbolication.rs
Adds tracing spans for proguard symbolication and opening a proguard mapper. For the former, we log the number of exceptions and frames, for the latter the size of the mapping file.
> feat(proguard): Add some tracing

- crates/symbolicator-service/src/config.rs
In our preliminary tests with 50% load, we saw in-memory cache hit rate settle at about 50%. Thus, we increase the in-memory cache size so more proguard mappers can be kept in memory.
Further increases may follow if in-memory hit rate is still not satisfactory.
> ref(proguard): Increase in-memory cache size to 5GiB

- crates/symbolicator-proguard/src/symbolication.rs
In porting the Python code, I mistakenly split on the last `$` character instead of the first.
> fix(proguard): Correctly compute source file name

- crates/symbolicator-proguard/src/symbolication.rs
This was a subtle difference between Symbolicator and Python: we erroneously set a frame's `in_app` field even if we didn't map it. This fixes that problem and also adds a test.
> fix(proguard): Don't set `in_app` if frame wasn't mapped

- crates/symbolicli/src/main.rs
The code already handles `"csharp"` events correctly, it was just refusing to parse them.
> fix(symbolicli): Add C# platform

- crates/symbolicator-js/src/symbolication.rs
- crates/symbolicator-native/src/symbolication/module_lookup.rs
- crates/symbolicator-proguard/src/symbolication.rs
- crates/symbolicator-service/src/source_context.rs
The Python code always trims source lines. Since we don't have column numbers in jvm, we just pass 0 so the line is trimmed to 140 characters.
> fix: Always trim source context lines

- crates/symbolicator-proguard/src/symbolication.rs
With the help of @romtsn I figured out that the current behavior (using 0 as the line number if there isn't one) accords with Google's implementation of `retrace`. Their `retrace`, however, can also resolve such cases without any line number at all. We should update our remapping logic to achieve the same thing.
> meta(proguard:) Update comments about remapping

- crates/symbolicator-js/src/symbolication.rs
- crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__no_source_contents.snap
- crates/symbolicator-js/tests/integration/sourcemap.rs
- tests/fixtures/sourcemaps/11_no_source_contents/embedded.js
- tests/fixtures/sourcemaps/11_no_source_contents/embedded.js.map
We clone the minified frame before applying source context to it, because otherwise the unminified frame might end up with nonsensical source context.
> fix(js): Don't apply minified source context to symbolicated frame

- crates/symbolicator-native/tests/integration/source_errors.rs
The test is slightly flaky, so let's increase the download timeout a little bit.
> test: Increase download timeout in deny list test

- crates/symbolicator-js/src/lookup.rs
- gocd/templates/jsonnetfile.json
- gocd/templates/jsonnetfile.lock.json
Updated `gocd-jsonnet` version to [v2.10](https://github.com/getsentry/gocd-jsonnet/releases/tag/v2.10.0).
> updated gocd-jsonnet version

- CHANGELOG.md
- crates/symbolicator-proguard/src/symbolication.rs
- crates/symbolicator-proguard/tests/integration/snapshots/integration__proguard__source_lookup_with_proguard.snap
This just applies the file name returned by the proguard mapper, if any, to the filename and abs path.
This is actually done, I'm just making it a draft because I don't want to merge it before we're done with our A/B testing.
Closes https://github.com/getsentry/team-processing/issues/139.
> feat(proguard): Remap filename and abs_path

- crates/symbolicator-proguard/src/service.rs
- crates/symbolicator-proguard/src/symbolication.rs
I would like to be able to tell where `symbolicate_jvm` spends its time.
> feat(proguard): Instrument some more functions

- docs/api/proxy.md
I don't know if `symbols` was ever correct but it certainly isn't now.
> docs(proxy): Fix route

- crates/symbolicator-proguard/src/symbolication.rs
Different proguard errors should result in different issues here. I suspect most of them are going to be `notfound`.
> ref(proguard): Ungroup errors

- crates/symbolicator-js/src/interface.rs
- crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__e2e_multiple_smref_scraped.snap
- crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__e2e_node_debugid.snap
- crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__e2e_react_native.snap
- crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__e2e_source_no_header.snap
- crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__fetch_error.snap
- crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__indexed_sourcemap_source_expansion.snap
- crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__inlined_sources.snap
- crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__invalid_location.snap
- crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__malformed_abs_path.snap
- crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__no_source_contents.snap
- crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__source_expansion.snap
- crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__sourcemap_embedded_source_expansion.snap
- crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__sourcemap_expansion.snap
- crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__sourcemap_nofiles_source_expansion.snap
- crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__sourcemap_source_expansion.snap
- crates/symbolicator-js/tests/integration/snapshots/integration__sourcemap__webpack.snap
If `data` is not serialized at all, it can be hard to tell whether a frame even went through symbolication. Therefore we now always serialize at least `data.symbolicated` to make it clear that Symbolicator has processed the frame.
> ref(js): Always serialize `symbolicated` flag

- crates/symbolicator-proguard/src/symbolication.rs
Debug files not being found is entirely routine.
> ref(proguard): Don't log "not found" errors

- crates/symbolicator-service/src/config.rs
We can probably handle more concurrent requests.
> config: Turn max_concurrent_requests up to 200

- crates/symbolicator-native/src/symbolication/demangle.rs
Stops emitting an error on demangling failures, falling back to the underlying symbol directly.
> Do not emit demangling errors (for now)

- Cargo.lock
The `cargo update` pulls in an updated `symbolic` that pins an older non-regressed `zip` version.
> Downgrade broken `zip` by running `cargo update`

- crates/symbolicator-service/src/caching/cleanup.rs
We have seen caches eating through the available disk space in production. This should make it easier which caches are taking up the most space on which hosts.
> feat(cache): Emit current size metric on cleanup

- Cargo.lock
- crates/wasm-split/Cargo.toml
In this PR I purpose to add `exception-handling` feature to wasmbin dependencies.
With reference to these issuses: 
* [symbolicator/issues/969](https://github.com/getsentry/symbolicator/issues/969), 
* [GoogleChromeLabs/wasmbin/issues/7](https://github.com/GoogleChromeLabs/wasmbin/issues/7),
* [GoogleChromeLabs/wasmbin/pull/9](https://github.com/GoogleChromeLabs/wasmbin/pull/9),  
in order for the symbolizer and wasm-split to support -fwasm-exceptions, is needed to set `exception-handling` feature in the wasmbin dependency.
PS: Just to be sure, I also asked the author of wasmbin [LINK](https://github.com/RReverser/wasmbin/issues/2) for confirmation that these changes were safe. But looking at the sourcecode it looks like it should be safe.
> Support for -fwasm-exceptions in wasm-split and others

- Cargo.lock
- Cargo.toml
- crates/symbolicator-proguard/Cargo.toml
- crates/symbolicator-proguard/src/service.rs
- crates/symbolicator-proguard/src/symbolication.rs
- crates/symbolicator-service/src/caches/versions.rs
Based on https://github.com/getsentry/rust-proguard/pull/42.
> feat: Use proguard cache format

- crates/symbolicator-proguard/src/service.rs
- crates/symbolicator-service/src/caching/mod.rs
- crates/symbolicator-service/src/config.rs
* Previously there wasn't much point sharing proguard files via the shared cache because we were downloading them exclusively from Sentry anyway. But now we don't use actual proguard files anymore, we compute cache files from them and use those. So it makes sense to share the cache files between Symbolicators.
* For the same reason we wanted a very large in-memory cache for proguard files. Since `ProguardCache` files have a small (on the order of dozens of bytes) constant size, this is not necessary and we can simply use the same logic as for Symcaches.
> feat: Adjust proguard caching

- CHANGELOG.md
- crates/symbolicator-proguard/src/interface.rs
- crates/symbolicator-proguard/src/symbolication.rs
- crates/symbolicator-proguard/tests/integration/proguard.rs
- crates/symbolicator-proguard/tests/integration/snapshots/integration__proguard__basic_source_lookup.snap
- crates/symbolicator-proguard/tests/integration/snapshots/integration__proguard__remap_exception.snap
- crates/symbolicator-proguard/tests/integration/snapshots/integration__proguard__resolving_inline.snap
- crates/symbolicator-proguard/tests/integration/snapshots/integration__proguard__source_lookup_with_proguard.snap
- crates/symbolicator/src/endpoints/symbolicate_jvm.rs
This allows sending an additional list of class names not attached to any stack frame or exception with a proguard request. These classes will be deobfuscated and returned in the form of a map from obfuscated to deobfuscated names.
The intended use case is deobfuscating view hierarchies.
> feat(proguard): Remap additional class names

- .github/workflows/build.yml
Since macos-11 is no longer supported, we need to bump to a newer version.
> chore(ci): Bump macos image to 14

- Cargo.lock
- crates/process-event/Cargo.toml
- crates/symbolicator-js/Cargo.toml
- crates/symbolicator-native/Cargo.toml
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-sources/Cargo.toml
- crates/symbolicator-sources/src/filetype.rs
- crates/symbolicator/Cargo.toml
- crates/symbolicli/Cargo.toml
- crates/symsorter/Cargo.toml
Because of https://github.com/getsentry/symbolic/pull/849, this means Elf/Wasm debug files can now contain source information. We update `FileType::sources` to reflect this.
> deps: Update symbolic to 12.10.0

- crates/symbolicator-js/src/utils.rs
We have seen webpack paths with a prefix of `webpack-internal`, not just `webpack`. They should be handled analogously to those starting with `webpack:`.
> feat(js): Handle `webpack-internal` prefix

- crates/symbolicator-js/src/utils.rs
The original logic for deciding whether a JS frame should be in-app (seen [here](https://github.com/getsentry/sentry/blob/69ee8d0fcbff3494f2d2a6fb9fb59195fc49b575/src/sentry/lang/javascript/processor.py#L1573-L1603)) is quite convoluted and difficult to understand. The `is_in_app` function reproduces it faithfully, but with some refactoring. In any case, for webpack, only file names beginning with `./` would be considered as in-app, but judging from examples that's too strict. Therefore we change the logic for webpack as follows: A file name is considered _not_ in-app if either of these is true:
* It starts with `~/` (according to the documentation in the original Python version, this means it's "coming from node_modules").
* It contains `/node_modules/` as a substring.
Otherwise it's …
> fix(js): Recognize more abs_paths as in-app

- crates/symbolicator-service/src/config.rs
- crates/symbolicator/src/cli.rs
This adds a configurable platform tag to metrics. If this is set, the platform ~(determined based on the Symbolicator's hostname)~ (read from the `SYMBOLICATOR_PLATFORM` env variable) will be reported with every metric.
Fixes #1509.
> feat(metrics): Add platform tag

- CHANGELOG.md
- crates/symbolicator-service/src/config.rs
- crates/symbolicator/src/cli.rs
- local.example.yml
Addressing: #1515 still some todo's that need to be tackled but opened to invite feedback.
TODO's:
> Making performance trace sample rate configurable

- crates/symbolicator/src/cli.rs
We're getting a lot of these "platform not available" errors in S4S, for unclear reasons. Maybe logging the error message will shed some light on whether the env var is not set or it contains an invalid value.
> fix: Log "platform not available" error

- docs/index.md
#1517 did not update the documentation, this does it now.
> docs: Document transaction_sample_rate option

- Cargo.lock
- crates/process-event/Cargo.toml
- crates/symbolicator-js/Cargo.toml
- crates/symbolicator-native/Cargo.toml
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-sources/Cargo.toml
- crates/symbolicator/Cargo.toml
- crates/symbolicli/Cargo.toml
- crates/symsorter/Cargo.toml
This pulls in https://github.com/getsentry/symbolic/pull/868, allowing us to process some CFI in DWARF files that we previously rejected as broken.
> deps: Update symbolic to 12.11.1

- .github/workflows/build.yml
Supersedes https://github.com/getsentry/symbolicator/pull/1503 by using artifacts/merge to merge together multiple artifacts from different jobs into the single one named github.sha that craft expects.
Summarily, upload-artifact v3 is deprecated but v4 doesn't support mutating an artifact with the name name by uploading different filepaths to the same artifact. Because we need a single artifact "github.sha", we have to use actions/merge to create it. Alternatively craft could be modified but this is the easiest way forward and I like the idea of a unified artifact, it makes craft simpler.
ref: https://github.com/getsentry/craft/issues/552
> ci: update actions/upload-artifact to v4 with merge

- docs/api/index.md
- docs/api/response.md
- docs/api/symbolicate-jvm.md
Fix: #1476
Tried to mimic the style of the already existing documentation, content is based on notion documentation and code/tests.
> docs: Document symbolicate-jvm endpoint

- CHANGELOG.md
- crates/symbolicator-service/src/caching/cleanup.rs
- crates/symbolicator-service/src/caching/tests.rs
- crates/symbolicator/src/cli.rs
Adds a `dry-run` flag to the cleanup command that will make it simulate the cleanup without deleting files.
> feat(cleanup): Add dry-run mode

- crates/symbolicator-service/src/download/s3.rs
Symbolicator errors in S4S look really bad right now because every individual S3 error is its own issue.
> fix: Don't log entire S3 error as part of the message

- crates/symbolicator-service/src/download/s3.rs
There's nothing to do on our end for these errors, users need to fix their S3 setups.
> fix(s3): Don't log PermanentRedirect errors

- crates/symbolicator-js/src/interface.rs
- crates/symbolicator-js/src/lookup.rs
- crates/symbolicator-js/tests/integration/sourcemap.rs
- crates/symbolicator-sources/src/paths.rs
- crates/symbolicator-sources/src/types.rs
- crates/symbolicator-stress/src/workloads.rs
- crates/symbolicator/src/endpoints/symbolicate_js.rs
- crates/symbolicli/src/main.rs
This is part of the effort to unify Symbolicator's symbolication endpoints. It may seem strange to split types apart in the pursuit of unification, so let
me explain. Currently, it's fine to use the same type for native and JS modules because we are always using them in the context of symbolicating exactly one of these platforms. But once there is only one symbolication endpoint, it will be convenient to be able to split modules according to their platforms.
This change is totally transparent from Sentry's side: the modules it sends for JS symbolication must already have exactly the fields in the new `JsModule` struct. See  https://github.com/getsentry/sentry/blob/59f5d94901166bd457ce13edfc560c661f16e3f1/src/sentry/lang/javascript/processing.py#L92-L98.
> ref: Split apart native and JS modules

- crates/symbolicator-service/src/types.rs
- crates/symbolicli/src/main.rs
These don't do a whole lot yet, but will allow us to distinguish frames down the line when we process mixed stacktraces.
This also includes a drive-by refactor of `symbolicli` to take advantage of this enum instead of awkwardly rolling its own.
> feat: Introduce platform enums

- crates/symbolicator-js/src/metrics.rs
- crates/symbolicator-js/src/symbolication.rs
- crates/symbolicator-proguard/src/lib.rs
- crates/symbolicator-proguard/src/metrics.rs
- crates/symbolicator-proguard/src/symbolication.rs
We never emitted stacktrace metrics (number of stacktraces/frames per request) for JS¹ and JVM. This adds the most important metrics for those platforms.
¹ Well we did for JS but under a different name.
> feat(js/jvm): Emit stacktrace metrics

- CHANGELOG.md
- crates/symbolicator-js/src/interface.rs
- crates/symbolicator-js/tests/integration/sourcemap.rs
- crates/symbolicator-native/src/interface.rs
- crates/symbolicator-native/src/symbolication/apple.rs
- crates/symbolicator-native/src/symbolication/native.rs
- crates/symbolicator-native/src/symbolication/process_minidump.rs
- crates/symbolicator-native/src/symbolication/symbolicate.rs
- crates/symbolicator-native/tests/integration/process_minidump.rs
- crates/symbolicator-native/tests/integration/symbolication.rs
- crates/symbolicator-native/tests/integration/utils.rs
- crates/symbolicator-proguard/src/interface.rs
- crates/symbolicator-proguard/src/symbolication.rs
- crates/symbolicator-proguard/tests/integration/proguard.rs
- crates/symbolicator-stress/src/workloads.rs
- crates/symbolicator/src/endpoints/applecrashreport.rs
- crates/symbolicator/src/endpoints/minidump.rs
- crates/symbolicator/src/endpoints/symbolicate.rs
- crates/symbolicator/src/endpoints/symbolicate_js.rs
- crates/symbolicator/src/endpoints/symbolicate_jvm.rs
- crates/symbolicator/src/service.rs
- crates/symbolicli/src/main.rs
- docs/api/applecrashreport.md
- docs/api/minidump.md
- docs/api/sourcemaps.md
- docs/api/symbolicate-jvm.md
- docs/api/symbolication.md
This adds `platform` values to all stack frame and symbolication request types and endpoints.
We're intentionally using `Platform` everywhere instead of the more narrow types appropriate to native, JS, or JVM, just in case Sentry sends an unexpected value.
> feat: Add platforms to events and frames

- crates/symbolicator-js/src/metrics.rs
- crates/symbolicator-js/src/symbolication.rs
- crates/symbolicator-native/src/metrics.rs
- crates/symbolicator-native/src/symbolication/symbolicate.rs
- crates/symbolicator-proguard/src/metrics.rs
- crates/symbolicator-proguard/src/symbolication.rs
- crates/symbolicator-service/src/types.rs
Each count is tagged with the platform of the individual frames as well as that of the whole event.
As a drive-by, this also implements `AsRef<str>` for the platform types.
> feat: Tag "number of frames" metrics with platforms

- crates/symbolicator-proguard/src/metrics.rs
This is to make sure that gating JVM events behind platform values is actually sound. We know that's the case for stacktraces, but we don't know it for exceptions or classes.
> feat(jvm): Tag class & exception metrics with platform

- devservices/config.yml
- devservices/symbolicator/config.yml
This config will control how symbolicator is brought up
> feat(devservices): Add devservices config

- crates/symbolicator-js/src/metrics.rs
- crates/symbolicator-js/src/symbolication.rs
- crates/symbolicator-proguard/src/metrics.rs
- crates/symbolicator-proguard/src/symbolication.rs
This counts both symbolicated and unsymbolicated frames by platform. Also, for JVM, it properly counts symbolicated and unsymbolicated exceptions and classes.
It pushes the tracking of frames by platform into the symbolication procedures themselves, which is why the diff is so big.
What I would really like to see is no successfully symbolicated exceptions, frames, or classes that don't have the right platform. That would mean that we really can use the platform as the sole discriminant (an issue particularly in JVM).
> ref(metrics): Refactor JVM & JS symbolication stats

- devservices/config.yml
Adding a label to the docker compose config to signify that devservices is the orchestrator.
> deat(devservices): Add devservices label for symbolicator container

- .github/workflows/build.yml
- .github/workflows/image.yml
Adjusts the "Release build" and "image" jobs to run on Ubuntu 20.04 instead of latest.
Fixes #1466.
> build: Build Symbolicator on Ubuntu 20.04

- Cargo.lock
- crates/symbolicator/Cargo.toml
Requires https://github.com/getsentry/symbolic/pull/883.
ref: https://github.com/getsentry/symbolic/issues/882
> chore(deps): Bump symbolic to 12.12.4

- crates/symbolicator-js/src/sourcemap_cache.rs
- crates/symbolicator-native/src/caches/ppdb_caches.rs
- crates/symbolicator-native/src/caches/symcaches.rs
- crates/symbolicator-service/src/caching/memory.rs
- crates/symbolicator-service/src/caching/tests.rs
This adds an early return in `memory.rs` so that if an `InternalError` is returned by a cache computation¹, we don't attempt to write the error and don't persist the temp file. This kills two birds with one stone:
1. It fixes the "Internal errors should never be written out" issue we see in Sentry.
2. More importantly, if a computation fails with an `InternalError` because of lack of disk space, we discard the resulting file immediately instead of preserving its (likely useless) contents.
Moreover, I also added some extra validation after `symcache`/`ppdbcache`/`sourcemapcache` conversion. Now, if _somehow_ the write goes through but the file is invalid, we also return an `InternalError` and it will be deleted. This costs us nothing because parsing these files is essentially free. I …
> fix: Don't persist cache files that error while writing

- crates/symbolicator-service/src/caching/memory.rs
- crates/symbolicator-service/src/caching/tests.rs
Currently, when we recompute a cache entry for which a fallback version exists, we just add the new version and leave the fallback in place. The idea was that the fallback version would fall out of use and *eventually* be cleaned up by the cleanup task.
While this is true, "eventually" is doing a lot of work here. In the immediate term, it's massively wasteful. Therefore, we now delete the fallback versions in `spawn_refresh` immediately after the new cache entry has been computed.
Fixes #1577.
ETA: Changed this to always deleting old versions on compute, not just on lazy recomputes. That way it also covers incompatible cache version bumps.
> fix(caching): Eagerly cleanup old versions

- crates/symbolicator-js/src/api_lookup.rs
- crates/symbolicator-js/src/lookup.rs
- crates/symbolicator-service/src/objects/mod.rs
This adds `tracing::instrument` calls to a number of functions in the code path of JS symbolication, specifically the fetching of sourcemaps/source files.
> ref(js): Add instrumentation to JS file fetching

- crates/symbolicator-service/src/download/s3.rs
These errors show up in Sentry to no practical effect other than spam. We can keep adding exceptions every time we see an error we don't care about or we can make a clean slate and only log them at a low level. Note that they will still show up as download errors in users' events.
> fix(s3): Demote S3 errors to debug

- crates/symbolicator-service/src/download/mod.rs
- crates/symbolicator-sources/src/remotefile.rs
This adds some visibility to how often we're hitting internal symbol sources and with what outcome.
> feat: Report download metrics for internal symbol sources

- .github/workflows/ci.yml
As we get closer to the release of the revamped devservices, we want CI in symbolicator to use the new devservices when running integration tests. Especially since the older `sentry devservices` will be deprecated soon.
Using the changes from https://github.com/getsentry/sentry/pull/83415
> feat(devservices): Use new devservices for sentry integration tests

- Cargo.toml
Thin LTO to speed up the build. Going to have a look if performance noticeably changes, but from looking into it for Relay, there were no noticeable changes.
> ref(build): Switch LTO profile to thin

- cloudbuild.yaml
The trigger is already gone, images are only built in github actions and pushed from github actions.
> build: remove google cloud build

- .github/workflows/image.yml
This PR uses the new free arm runners for CI.
Related to: https://github.com/getsentry/relay/pull/4465
> feat(ci): Use free arm64 runner

- crates/symbolicator-service/src/metrics.rs
Inspired by https://github.com/getsentry/relay/pull/4446/commits/2fce818c498ff090ffdf4b1fbc7f83a0981d8495.
> feat(metrics): Add sets

- .github/workflows/image.yml
> ci(gocd): Upload missing gocd artifacts

- .github/workflows/ci.yml
This flag is now removed in https://github.com/getsentry/sentry/pull/84184, so removing this in all places that use it
> chore(ci): Remove use new devservices flag

- Cargo.lock
- crates/symbolicator-js/Cargo.toml
- crates/symbolicator-js/src/lookup.rs
This captures 1 in 10_000 cases of a source or sourcemap lookup failing even though a debug id is available as a Sentry error. This is to gain some insight into how that can happen.
> feat(js): Temporarily sample failing lookups with debug ids

- crates/symbolicator-native/src/caches/ppdb_caches.rs
Temporarily update warning about .NET with Windows PDB to an error so we can aggregate by `request.scope` on the sentry error to see how many projects are affected.
ref: https://github.com/getsentry/symbolic/issues/871
> instr(pdb): Upgrade warning to error

- crates/symbolicator-service/src/caching/cache_error.rs
- crates/symbolicator-service/src/caching/cleanup.rs
- crates/symbolicator-service/src/caching/fs.rs
The cleanup job does not need to `mmap` the entire cache file contents, we can just peek into the file, try to parse an error and immediately stop.
We've seen that this causes huge amounts of cache memory usage, which is not a problem in practice but may cause issues in containerized environments, specifically Kubernetes 1.30.
> ref(symbolicator): Make cleanup job not mmap cache file contents

- CHANGELOG.md
- crates/symsorter/src/app.rs
I recently observed a behavior in `symsorter` when running with `--ignore-errors` that is probably unintentional:
A ZIP archive it detected in the input path failed to read, leading to immediate termination, printing an error message in the top-level error logger, and unhelpful information that suggested I could use `--ignore-errors`.
Of course, what I really would expect in such a situation is the following:
* `symsorter` prints the error with the context of the ZIP archive path for which the error happens
* `symsorter` continues to process all other files
* `symsorter` does not suggest to use a flag which was already enabled
* `symsorter` returns a 0
This PR
* moves CLI parsing to `main()` so that the top-level error logger doesn't suggest using `--ignore-errors` when it is already in …
> fix: rectify symsorter `--ignore-errors` handling for ZIP archives.

- CHANGELOG.md
- crates/symbolicator-native/src/caches/symcaches.rs
- crates/symbolicator-service/src/caching/fs.rs
- crates/symbolicator-service/src/caching/tests.rs
- crates/symbolicator-service/src/config.rs
This adds a setting `retry_missing_after_public` to downloaded and derived cache configs. The effect of this setting is to control the time after which negative (missing, failed download, &c.) cache entries from _public_ sources. Whether a file comes from a public source is determined by reading its metadata, which we added in #1617 and started writing in #1618.
The default value for this setting is 24h. This means that each Symbolicator only makes one request per day to public symbol sources for each missing debug file, as opposed to one per hour like before.
The bulk of this PR is test changes.
> feat: Add retry_missing_after_public config setting

- crates/symbolicator-service/src/caching/cleanup.rs
This adds the combined size of removed and kept metadata files to the stats emitted by the cleanup job.
> feat(cleanup): Emit stats for metadata files

- crates/symbolicator-native/src/caches/symcaches.rs
- crates/symbolicator-native/tests/integration/e2e.rs
- crates/symbolicator-service/src/caching/cache_key.rs
- crates/symbolicator-service/src/caching/memory.rs
- crates/symbolicator-service/src/caching/metadata.rs
- crates/symbolicator-service/src/caching/tests.rs
Previously we wrote .txt files with the human-readable contents of cache keys next to cache files, but only in debug mode. Since we now have JSON metadata files, we subsume these debug text files into a `debug` field in the `Metadata` struct that only gets written in debug mode.
> ref(caching): Remove debug .txt files

- crates/symbolicator-service/src/download/mod.rs
The public NuGet symbol source returns a permission denied error when trying to download a portable pdb file without a debug checksum. We capture an error whenever we try to download from this source without such a checksum to see if this is the cause of our many permission denied errors.
> fix(nuget): Capture error when no debug checksum

- crates/symbolicator-service/src/download/mod.rs
This reverts commit 15ac27d0a746b75eaceeb97dff6094f7de3586b7. We have collected enough events for this error for now.
> Revert "fix(nuget): Capture error when no debug checksum (#1626)"

- crates/symbolicator-js/src/sourcemap_cache.rs
- crates/symbolicator-native/src/caches/bitcode.rs
- crates/symbolicator-native/src/caches/cficaches.rs
- crates/symbolicator-native/src/caches/il2cpp.rs
- crates/symbolicator-native/src/caches/ppdb_caches.rs
- crates/symbolicator-native/src/caches/symcaches.rs
- crates/symbolicator-proguard/src/service.rs
- crates/symbolicator-service/src/caches/mod.rs
- crates/symbolicator-service/src/caches/sourcefiles.rs
- crates/symbolicator-service/src/caches/versions.rs
- crates/symbolicator-service/src/caching/cache_key.rs
- crates/symbolicator-service/src/caching/memory.rs
- crates/symbolicator-service/src/caching/mod.rs
- crates/symbolicator-service/src/caching/tests.rs
- crates/symbolicator-service/src/objects/data_cache.rs
- crates/symbolicator-service/src/objects/meta_cache.rs
This is part 1 of a more principled/correct solution to #1630. It introduces a `CachePathFormat` enum (which for now only has 1 variant) that is attached to each cache version and determines how a cache key should be formatted into a cache file path for this version.
> feat(caches): Introduce cache path layouts

- crates/symbolicator-service/src/caching/cleanup.rs
This lets the cleanup remove directories that are "morally" empty but e.g. still contain leftover metadata files.
> fix(cleanup): Use remove_dir_all

- .github/workflows/release-ghcr-version-tag.yml
This adds the same logic that is being added to Relay (https://github.com/getsentry/relay/pull/4532) to symbolicator.
That is, this PR adds the logic to tag  images we release to the Github Container Registry (ghcr) with the release version.
> feat(release): Tag images with release version.

- Cargo.lock
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-service/src/caching/cleanup.rs
This uses `try_fold` and `try_reduce` from `rayon` to clean up cache directories in parallel.
> ref(cleanup): Parallelize cleanup using rayon

- crates/symbolicator-service/src/download/mod.rs
Temporarily log whenever we successfully download a file from the Electron symbol server. These are few and far between, so the volume should be no problem.
The purpose of this is to validate that we only find files with very specific debug file names (my current assumption). If that is true, we can use path patterns to significantly limit what we request from Electron.
> ref: Log successful downloads from Electron

- CHANGELOG.md
- Cargo.toml
- crates/symbolicator-js/src/sourcemap_cache.rs
- crates/symbolicator-native/src/caches/ppdb_caches.rs
- crates/symbolicator-native/src/caches/symcaches.rs
- crates/symbolicator-proguard/src/service.rs
Marks the Sym- and SourceMap-Caches for random access to the byteview.
This is supposed to reduce the readahead of the operating system for data that is not actually needed. Running `symbolicli` with and without a patch to apply `MADV_RANDOM` revealed for  a single lookup we can reduce the amount of bytes read from `1628KiB` to just `84KiB`.
> ref(caches): Mark certain caches as random access

- crates/symbolicator-sources/src/paths.rs
This adds a test to make sure that the debug/code files we successfully download from the Electron symbol source can be covered by a small set of path patterns.
See https://github.com/getsentry/team-ingest/issues/461 for context and information on how these file paths were obtained.
> feat(sources): Add test for Electron patterns

- crates/symbolicator-native/src/symbolication/module_lookup.rs
This restricts the logging for successful downloads from the Electron source to only the first image (the one with the lowest load address). This is to find which debug/code file names can occur in the first image, which is the one we're planning to rename.
> ref: Log succesful Electron downloads of the 1st image

- crates/symbolicator-native/src/interface.rs
- crates/symbolicator-native/src/symbolication/process_minidump.rs
- crates/symbolicator-native/tests/integration/process_minidump.rs
- crates/symbolicator-stress/src/workloads.rs
- crates/symbolicator/src/endpoints/minidump.rs
- crates/symbolicator/src/service.rs
- crates/symbolicli/src/main.rs
This introduces a `ProcessMinidump` request struct in analogy to `SymbolicateStacktraces` &c. This changes no functionality, it only bundles parameters together.
> ref: Introduce ProcessMinidump struct

- crates/symbolicator-native/Cargo.toml
- crates/symbolicator-native/src/symbolication/module_lookup.rs
Since instituting the renaming logic, successful downloads from Electron have gone up, but so have unsuccessful ones. We log the unsuccessful attempts for renamed files to figure out if this is a cause for concern.
> feat(electron): Log download failures for renamed modules

- crates/symbolicator-native/src/symbolication/module_lookup.rs
Slight modification to #1653: log the successful candidates as well as the unsuccessful ones.
> feat(electron): Log successful and failed candidates

- crates/symbolicator-service/src/download/filesystem.rs
- crates/symbolicator-service/src/download/gcs.rs
- crates/symbolicator-service/src/download/http.rs
- crates/symbolicator-service/src/download/mod.rs
- crates/symbolicator-service/src/download/s3.rs
- crates/symbolicator-service/src/download/sentry.rs
The downloaders for the various source types each have a `download_source` method that currently takes a `tokio::fs::File` as its destination. We can instead target `tokio::io::AsyncWrite`, which also lets us download into e.g. an in-memory buffer instead of a file.
> ref: Make download_source functions generic

- crates/symbolicator-service/src/caching/memory.rs
- crates/symbolicator-service/src/caching/shared_cache/mod.rs
This splits some very long and complicated methods on `Cacher` apart (compute, compute_memoized). This should make the logic more understandable, but the diff is unfortunately not easy to grasp.
> ref(caching): Split up `Cacher` methods

- Cargo.lock
- crates/symbolicator-native/Cargo.toml
Contains changes of this [rust-minidump PR](https://github.com/rust-minidump/rust-minidump/pull/1088), which improves frame pointer resolution for Windows.
Fixes: https://github.com/getsentry/sentry/issues/85336
> ref(minidump): Update rust minidump with better windows fp resolution

- crates/symbolicator-service/src/download/http.rs
By itself, this change is inert: the only headers we actually get from Sentry are basic auth, so setting the user agent before or after makes no difference. However, this allows us to override the user agent for individual source configs.
> ref(HTTP sources): Set user agent before custom headers

- Cargo.lock
- crates/symbolicator-service/Cargo.toml
- crates/symbolicator-service/src/download/destination.rs
- crates/symbolicator-service/src/download/filesystem.rs
- crates/symbolicator-service/src/download/gcs.rs
- crates/symbolicator-service/src/download/http.rs
- crates/symbolicator-service/src/download/mod.rs
- crates/symbolicator-service/src/download/partial.rs
- crates/symbolicator-service/src/download/s3.rs
- crates/symbolicator-service/src/download/sentry.rs
- crates/symbolicator-service/src/utils/futures.rs
- crates/symbolicator-test/src/lib.rs
Parallelize large downloads with multiple parallel streams using [range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Range_requests).
Symbolicator after this PR will make the first request to a resource with a `Range` header containing a large initial range, which should already satisfy most small files.
If the server responds with a `Content-Range` which is not already covered by the initial `Range`, symbolicator will split the remaining bytes into multiple smaller ranges and request them concurrently. A response which does not contain a `Content-Range` header in the response is treated as previously and is assumed to contain the fully requested file (as per spec).
The concurrent streams are written concurrently into the `Destination`, this is currently only …
> feat(download): Parallelize downloading large files with multiple independent partial streams

- crates/symbolicator-service/src/download/mod.rs
We can be a bit more lenient and use the restricted time for the entire content instead of the partials, especially with the electron source this seems to help.
> ref(download): Use the total length instead of the partial length to determine timeouts

- crates/symbolicator-service/src/download/destination.rs
Renamed field `std` to `file` in PR 1, used field `std` in PR 2 and merged both -> now it's broken.
> fix(download): Correct failed merge, accessing a renamed field

- crates/symbolicator-js/src/lookup.rs
This adds a `tracing::error` in JS symbolication if querying Sentry for files/artifact bundles fails.
This is intended less for SaaS and more for self-hosted, where there may be communication problems between Sentry and Symbolicator.
> feat(js): Error when failing to query Sentry

- crates/symbolicator-service/src/download/index.rs
The last ID fetching logic was set up so that the result (good or bad) of fetching the last ID from the index would be cached for 24h. This had some problems:
* The 24h period was set up with _successful_ downloads in mind. If the fetching fails, we likely want to retry much sooner than that.
* A download failure would return an error for the whole index, even if there is a perfectly good index still available for the previous last ID.
Really, what we want is something like this:
* If downloading the last ID succeeded, cache it for a day.
* If downloading the last ID failed and there is no previous good value, cache the error for 10min.
* If downloading the last ID failed and there is a previous good value, reuse it for another 24 hours.
This means that as soon as a download of the last …
> fix(index): Improve Symstore last ID logic

- crates/symsorter/src/app.rs
In cases where multiple input files are sorted into the same folder, e.g. app.exe and the corresponding app.pdb, the meta file only contains information of the last file written.  Add a `--keep-meta` option which causes new metadata entries to be appended instead, resulting in jsonl files instead.
> feat(symsorter): Save separate metadata for each file

- crates/symbolicator-service/src/download/index.rs
This emits a gauge for the last ID of every Symstore index. If the last ID wasn't successfully fetched, 0 is used as a placeholder. The metric is emitted when a fetch was attempted, even if the old lastid value is reused.
> feat(index): Add gauge metric for Symstore lastid

- crates/symbolicator-native/src/symbolication/symbolicate.rs
By mistake, the `SymbolicationActor` created a new SourceIndexService instead of cloning the one passed to it through `SharedServices`.
> fix(index): Avoid creating duplicate index service

- .github/workflows/build.yml
- .github/workflows/image.yml
See https://github.com/getsentry/symbolicator/actions/runs/14475232477/job/40600459400
``` 
--
This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101
 
<br class="Apple-interchange-newline">
```
> fix(ci): Bump ubuntu to 22.04

- Cargo.lock
- Cargo.toml
- crates/symbolicator-native/tests/integration/e2e.rs
- crates/symbolicator-service/src/caches/versions.rs
This updates `symbolic` to 12.15.4 for https://github.com/getsentry/symbolic/pull/915. It also (compatibly) bumps the symcache cache version to 9 so symcaches get recomputed with the fix.
> fix(symcache): Fix symcache generation from symbol tables

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Bumps symbolic to 12.5.5 which fixes a crash when demangling swift symbols.
> ref(symbolic): Update symbolic to 12.12.5

- crates/symbolicator-service/src/download/mod.rs
The errors were useful when initially verifying the implementation, after manual verification and spot checks, it works as expected.
> ref(download): Change error to debug/trace logs

- crates/symbolicator-js/src/api_lookup.rs
- crates/symbolicator-native/tests/integration/source_errors.rs
- crates/symbolicator-service/src/config.rs
- crates/symbolicator-service/src/download/gcs.rs
- crates/symbolicator-service/src/download/http.rs
- crates/symbolicator-service/src/download/mod.rs
- crates/symbolicator-service/src/download/s3.rs
- crates/symbolicator-service/src/download/sentry.rs
- crates/symbolicator-service/src/objects/data_cache.rs
- crates/symbolicator-service/src/utils/http.rs
Previously we had individual download timeout settings in the config and then a struct bundling them in the `utils` module. The default values were inconsistent between them (meaning the ones on the struct didn't matter) and this was just unnecessary duplication in general.
This moves the `DownloadTimeouts` struct into the config. No changes to config parsing.
> ref: Unify download timeout configuration

- .github/workflows/image.yml
Nightly images should be pushed to DockerHub. This is the only repository that don't do that.
> ci: push nightly images to dockerhub

- .github/workflows/image.yml
This is the only one that is missing from all repositories.
> ci: push nightly to ghcr

- Cargo.lock
- crates/symbolicator-native/Cargo.toml
Follow-up to #1667. https://github.com/rust-minidump/rust-minidump/pull/1088 has been released as part of 0.26.0, so we can switch back to upstream.
> deps: Update minidump to upstream 0.26.0

- crates/symbolicator-native/src/symbolication/native.rs
It's very noisy, non actionable.
Refs: #1727
> ref(instr): Lower log level of noisy underflow message

- .github/workflows/build.yml
Seems like symbolicator release is failing due to deprecated windows version: https://github.com/getsentry/symbolicator/actions/runs/16299649338/job/46030635724
> fix(ci): Update from windows 2019 to windows 2022

- .github/workflows/image.yml
- scripts/create-sentry-release
At the moment we only upload amd64 debug files into Sentry which causes Symbolication to fail.
This changes it such that we also upload the debug files for arm64
> ci: Upload ARM debug files

- Dockerfile
3.0.17 seems to segfault, temporary fix to pin the version.
> fix(docker): Pin openssl and libssl versions in dockerfile

- .github/workflows/image.yml
This changes the `assemble` job to run on `ubuntu-latest` (same as `assemble-ar`) and the `assemble-ar` job to also push the image as `:nightly` (same as `assemble`).
The latter part in particular is important because the `devservices` config expects the current image to be found at
`us-central1-docker.pkg.dev/sentryio/symbolicator/image:nightly`, and that image was last pushed on 2025-01-17.
> fix(ci): Align image/assemble and assemble-ar jobs

- crates/symbolicator/src/logging.rs
Similar to #1755. `"section #1 size 27167680 out of bounds"` from `goblin` is another very common warning-level log message that isn't actionable for us. Therefore we limit logs from `goblin` to errors.
ref: SYMBOLI-25
> fix(logging): Reduce goblin warning spam

- CHANGELOG.md
- crates/symbolicator-service/src/config.rs
- crates/symbolicator/src/server.rs
This adds a new config option `enable_cache_cleanup` (default `false`) that causes the `run` command to also start a periodic cache cleanup background thread. The time between cleanup runs is determined by the `cache_cleanup_interval` config option.
Implements https://github.com/getsentry/symbolicator/issues/1758. Implements SYMBOLI-34.
> feat(cleanup): Allow running cleanup from within Symbolicator

- Cargo.lock
- Cargo.toml
This updates `symbolic` to 12.16.2 to get access to https://github.com/getsentry/symbolic/pull/932. This doesn't require a cache version bump because only the lookup function changed, all cache contents stay the same.
> fix(js): Tokens only extend to the end of the line

- CHANGELOG.md
- crates/symsorter/src/utils.rs
Hi again,
long time no see.
We build unreal engine applications which use Perforce, and use a "nice" encoding of the p4 format - .e.g. if you were working on the main stream of project Lyra at CL 12345, your "depot path" would be //lyra/main and your CL is 12345. Unreal combines these together and replaces / with + to give you paths that can be stored, so you can uniquely identify a build by ++lyra+main-CL-12345 (There's more for shelves etc but out of scope). I'm playing with SymSorter, and I noticed that it didn't accept this format so I modified the regex to allow for a + character. 
I'm unsure of the implication this has on the storage formats, but I wanted to suggest it.
> Add extra characters to Symsorter allowed bundle ID characters

- crates/symbolicator-service/src/config.rs
- crates/symbolicator-service/src/download/mod.rs
* Increased the failure threshold default value to 60
* Decreased the block time default to 1h
* Added the error to download failure and block logs
* Short-circuit `register_download_failure` for already blocked hosts
ref: INGEST-547
> fix(download): Tune `HostDenyList`

- Cargo.lock
- crates/symbolicator/Cargo.toml
- crates/symbolicator/src/cli.rs
- crates/symbolicator/src/healthcheck.rs
- crates/symbolicator/src/logging.rs
- crates/symbolicator/src/main.rs
Similar work to https://github.com/getsentry/relay/pull/5044 due to distroless migration
This works on relay and this is making CI's red right now.
Changes made:
- Adds a new `healthcheck` sub-command
- Defaults to the values from the config
- Changes logger to use `stderr` to still allow for logging and parsing of the healthcheck output (Relay uses the same mechanism here)
> feat(symbolicator): Healthcheck command for self-hosted
